In [1]:
import pandas as pd
df_menu = pd.read_excel('C:/Users/YangTeng/Downloads/SpectraPremium_menu.xlsx', header=0)
list_url = df_menu['Url'].to_list()

print('总数量：' + str(len(list_url)))
list_url

总数量：450

['https://ecat.spectrapremium.com/en/parts/CRP16A',
 'https://ecat.spectrapremium.com/en/parts/CRP18A',
 'https://ecat.spectrapremium.com/en/parts/CRP19A',
 'https://ecat.spectrapremium.com/en/parts/CRP19B',
 'https://ecat.spectrapremium.com/en/parts/CRP25A',
 'https://ecat.spectrapremium.com/en/parts/CRP26A',
 'https://ecat.spectrapremium.com/en/parts/CRP28A',
 'https://ecat.spectrapremium.com/en/parts/CRP29A',
 'https://ecat.spectrapremium.com/en/parts/CRP30A',
 'https://ecat.spectrapremium.com/en/parts/CRP31A',
 'https://ecat.spectrapremium.com/en/parts/CRP32A',
 'https://ecat.spectrapremium.com/en/parts/CRP33A',
 'https://ecat.spectrapremium.com/en/parts/CRP33B',
 'https://ecat.spectrapremium.com/en/parts/CRP34A',
 'https://ecat.spectrapremium.com/en/parts/CRP35A',
 'https://ecat.spectrapremium.com/en/parts/CRP35B',
 'https://ecat.spectrapremium.com/en/parts/CRP37A',
 'https://ecat.spectrapremium.com/en/parts/CRP38A',
 'https://ecat.spectrapremium.com/en/parts/CRP39A',
 'https://ecat.spectrapremium.com/en/parts/CRP40A',
 'https://ecat.spectrapremium.com/en/parts/CRP41A',
 'https://ecat.spectrapremium.com/en/parts/CRP42A',
 'https://ecat.spectrapremium.com/en/parts/CRP43A',
 'https://ecat.spectrapremium.com/en/parts/CRP44A',
 'https://ecat.spectrapremium.com/en/parts/CRP44B',
 'https://ecat.spectrapremium.com/en/parts/CRP45A',
 'https://ecat.spectrapremium.com/en/parts/CRP46A',
 'https://ecat.spectrapremium.com/en/parts/CRP47A',
 'https://ecat.spectrapremium.com/en/parts/CRP49A',
 'https://ecat.spectrapremium.com/en/parts/CRP50A',
 'https://ecat.spectrapremium.com/en/parts/CRP51A',
 'https://ecat.spectrapremium.com/en/parts/CRP52A',
 'https://ecat.spectrapremium.com/en/parts/CRP53A',
 'https://ecat.spectrapremium.com/en/parts/CRP54A',
 'https://ecat.spectrapremium.com/en/parts/CRP55A',
 'https://ecat.spectrapremium.com/en/parts/CRP56A',
 'https://ecat.spectrapremium.com/en/parts/CRP57A',
 'https://ecat.spectrapremium.com/en/parts/CRP57B',
 'https://ecat.spectrapremium.com/en/parts/CRP58A',
 'https://ecat.spectrapremium.com/en/parts/CRP59A',
 'https://ecat.spectrapremium.com/en/parts/CRP60A',
 'https://ecat.spectrapremium.com/en/parts/CRP61A',
 'https://ecat.spectrapremium.com/en/parts/CRP62A',
 'https://ecat.spectrapremium.com/en/parts/CRP63A',
 'https://ecat.spectrapremium.com/en/parts/CRP64A',
 'https://ecat.spectrapremium.com/en/parts/CRP65A',
 'https://ecat.spectrapremium.com/en/parts/CRP66A',
 'https://ecat.spectrapremium.com/en/parts/CRP67A',
 'https://ecat.spectrapremium.com/en/parts/CRP68A',
 'https://ecat.spectrapremium.com/en/parts/CRP69A',
 'https://ecat.spectrapremium.com/en/parts/CRP16A',
 'https://ecat.spectrapremium.com/en/parts/CRP18A',
 'https://ecat.spectrapremium.com/en/parts/CRP19A',
 'https://ecat.spectrapremium.com/en/parts/CRP19B',
 'https://ecat.spectrapremium.com/en/parts/CRP25A',
 'https://ecat.spectrapremium.com/en/parts/CRP26A',
 'https://ecat.spectrapremium.com/en/parts/CRP28A',
 'https://ecat.spectrapremium.com/en/parts/CRP29A',
 'https://ecat.spectrapremium.com/en/parts/CRP30A',
 'https://ecat.spectrapremium.com/en/parts/CRP31A',
 'https://ecat.spectrapremium.com/en/parts/CRP32A',
 'https://ecat.spectrapremium.com/en/parts/CRP33A',
 'https://ecat.spectrapremium.com/en/parts/CRP33B',
 'https://ecat.spectrapremium.com/en/parts/CRP34A',
 'https://ecat.spectrapremium.com/en/parts/CRP35A',
 'https://ecat.spectrapremium.com/en/parts/CRP35B',
 'https://ecat.spectrapremium.com/en/parts/CRP37A',
 'https://ecat.spectrapremium.com/en/parts/CRP38A',
 'https://ecat.spectrapremium.com/en/parts/CRP39A',
 'https://ecat.spectrapremium.com/en/parts/CRP40A',
 'https://ecat.spectrapremium.com/en/parts/CRP41A',
 'https://ecat.spectrapremium.com/en/parts/CRP42A',
 'https://ecat.spectrapremium.com/en/parts/CRP43A',
 'https://ecat.spectrapremium.com/en/parts/CRP44A',
 'https://ecat.spectrapremium.com/en/parts/CRP44B',
 'https://ecat.spectrapremium.com/en/parts/CRP45A',
 'https://ecat.spectrapremium.com/en/parts/CRP46A',
 'https://ecat.spectrapremium.com/en/parts/CRP47A',
 'https://ecat.spectrapremium.com/en/parts/CRP49A',
 'https://ecat.spectrapremium.com/en/parts/CRP50A',
 'https://ecat.spectrapremium.com/en/parts/CRP51A',
 'https://ecat.spectrapremium.com/en/parts/CRP52A',
 'https://ecat.spectrapremium.com/en/parts/CRP53A',
 'https://ecat.spectrapremium.com/en/parts/CRP54A',
 'https://ecat.spectrapremium.com/en/parts/CRP55A',
 'https://ecat.spectrapremium.com/en/parts/CRP56A',
 'https://ecat.spectrapremium.com/en/parts/CRP57A',
 'https://ecat.spectrapremium.com/en/parts/CRP57B',
 'https://ecat.spectrapremium.com/en/parts/CRP58A',
 'https://ecat.spectrapremium.com/en/parts/CRP59A',
 'https://ecat.spectrapremium.com/en/parts/CRP60A',
 'https://ecat.spectrapremium.com/en/parts/CRP61A',
 'https://ecat.spectrapremium.com/en/parts/CRP62A',
 'https://ecat.spectrapremium.com/en/parts/CRP63A',
 'https://ecat.spectrapremium.com/en/parts/CRP64A',
 'https://ecat.spectrapremium.com/en/parts/CRP65A',
 'https://ecat.spectrapremium.com/en/parts/CRP66A',
 'https://ecat.spectrapremium.com/en/parts/CRP67A',
 'https://ecat.spectrapremium.com/en/parts/CRP68A',
 'https://ecat.spectrapremium.com/en/parts/CRP69A',
 'https://ecat.spectrapremium.com/en/parts/CRP70A',
 'https://ecat.spectrapremium.com/en/parts/CRP72A',
 'https://ecat.spectrapremium.com/en/parts/CRP73A',
 'https://ecat.spectrapremium.com/en/parts/CRP74A',
 'https://ecat.spectrapremium.com/en/parts/CRP75A',
 'https://ecat.spectrapremium.com/en/parts/CRP76A',
 'https://ecat.spectrapremium.com/en/parts/CRP78A',
 'https://ecat.spectrapremium.com/en/parts/DTP01A',
 'https://ecat.spectrapremium.com/en/parts/DTP02A',
 'https://ecat.spectrapremium.com/en/parts/DTP03A',
 'https://ecat.spectrapremium.com/en/parts/DTP04A',
 'https://ecat.spectrapremium.com/en/parts/DTP04B',
 'https://ecat.spectrapremium.com/en/parts/DTP05A',
 'https://ecat.spectrapremium.com/en/parts/DTP06A',
 'https://ecat.spectrapremium.com/en/parts/FP01A',
 'https://ecat.spectrapremium.com/en/parts/FP01B',
 'https://ecat.spectrapremium.com/en/parts/FP02A',
 'https://ecat.spectrapremium.com/en/parts/FP02B',
 'https://ecat.spectrapremium.com/en/parts/FP03A',
 'https://ecat.spectrapremium.com/en/parts/FP05A',
 'https://ecat.spectrapremium.com/en/parts/FP05B',
 'https://ecat.spectrapremium.com/en/parts/FP06A',
 'https://ecat.spectrapremium.com/en/parts/FP07A',
 'https://ecat.spectrapremium.com/en/parts/FP07B',
 'https://ecat.spectrapremium.com/en/parts/FP08A',
 'https://ecat.spectrapremium.com/en/parts/FP08B',
 'https://ecat.spectrapremium.com/en/parts/FP09A',
 'https://ecat.spectrapremium.com/en/parts/FP09B',
 'https://ecat.spectrapremium.com/en/parts/FP09C',
 'https://ecat.spectrapremium.com/en/parts/FP11A',
 'https://ecat.spectrapremium.com/en/parts/FP11B',
 'https://ecat.spectrapremium.com/en/parts/FP11C',
 'https://ecat.spectrapremium.com/en/parts/FP12A',
 'https://ecat.spectrapremium.com/en/parts/FP14A',
 'https://ecat.spectrapremium.com/en/parts/FP14B',
 'https://ecat.spectrapremium.com/en/parts/FP15B',
 'https://ecat.spectrapremium.com/en/parts/FP16B',
 'https://ecat.spectrapremium.com/en/parts/FP17A',
 'https://ecat.spectrapremium.com/en/parts/FP18A',
 'https://ecat.spectrapremium.com/en/parts/FP18B',
 'https://ecat.spectrapremium.com/en/parts/FP18D',
 'https://ecat.spectrapremium.com/en/parts/FP19A',
 'https://ecat.spectrapremium.com/en/parts/FP19B',
 'https://ecat.spectrapremium.com/en/parts/FP19C',
 'https://ecat.spectrapremium.com/en/parts/FP20A',
 'https://ecat.spectrapremium.com/en/parts/FP20B',
 'https://ecat.spectrapremium.com/en/parts/FP21A',
 'https://ecat.spectrapremium.com/en/parts/FP21B',
 'https://ecat.spectrapremium.com/en/parts/FP22A',
 'https://ecat.spectrapremium.com/en/parts/FP24B',
 'https://ecat.spectrapremium.com/en/parts/CRP70A',
 'https://ecat.spectrapremium.com/en/parts/CRP72A',
 'https://ecat.spectrapremium.com/en/parts/CRP73A',
 'https://ecat.spectrapremium.com/en/parts/CRP74A',
 'https://ecat.spectrapremium.com/en/parts/CRP75A',
 'https://ecat.spectrapremium.com/en/parts/CRP76A',
 'https://ecat.spectrapremium.com/en/parts/CRP78A',
 'https://ecat.spectrapremium.com/en/parts/DTP01A',
 'https://ecat.spectrapremium.com/en/parts/DTP02A',
 'https://ecat.spectrapremium.com/en/parts/DTP03A',
 'https://ecat.spectrapremium.com/en/parts/DTP04A',
 'https://ecat.spectrapremium.com/en/parts/DTP04B',
 'https://ecat.spectrapremium.com/en/parts/DTP05A',
 'https://ecat.spectrapremium.com/en/parts/DTP06A',
 'https://ecat.spectrapremium.com/en/parts/FP01A',
 'https://ecat.spectrapremium.com/en/parts/FP01B',
 'https://ecat.spectrapremium.com/en/parts/FP02A',
 'https://ecat.spectrapremium.com/en/parts/FP02B',
 'https://ecat.spectrapremium.com/en/parts/FP03A',
 'https://ecat.spectrapremium.com/en/parts/FP05A',
 'https://ecat.spectrapremium.com/en/parts/FP05B',
 'https://ecat.spectrapremium.com/en/parts/FP06A',
 'https://ecat.spectrapremium.com/en/parts/FP07A',
 'https://ecat.spectrapremium.com/en/parts/FP07B',
 'https://ecat.spectrapremium.com/en/parts/FP08A',
 'https://ecat.spectrapremium.com/en/parts/FP08B',
 'https://ecat.spectrapremium.com/en/parts/FP09A',
 'https://ecat.spectrapremium.com/en/parts/FP09B',
 'https://ecat.spectrapremium.com/en/parts/FP09C',
 'https://ecat.spectrapremium.com/en/parts/FP11A',
 'https://ecat.spectrapremium.com/en/parts/FP11B',
 'https://ecat.spectrapremium.com/en/parts/FP11C',
 'https://ecat.spectrapremium.com/en/parts/FP12A',
 'https://ecat.spectrapremium.com/en/parts/FP14A',
 'https://ecat.spectrapremium.com/en/parts/FP14B',
 'https://ecat.spectrapremium.com/en/parts/FP15B',
 'https://ecat.spectrapremium.com/en/parts/FP16B',
 'https://ecat.spectrapremium.com/en/parts/FP17A',
 'https://ecat.spectrapremium.com/en/parts/FP18A',
 'https://ecat.spectrapremium.com/en/parts/FP18B',
 'https://ecat.spectrapremium.com/en/parts/FP18D',
 'https://ecat.spectrapremium.com/en/parts/FP19A',
 'https://ecat.spectrapremium.com/en/parts/FP19B',
 'https://ecat.spectrapremium.com/en/parts/FP19C',
 'https://ecat.spectrapremium.com/en/parts/FP20A',
 'https://ecat.spectrapremium.com/en/parts/FP20B',
 'https://ecat.spectrapremium.com/en/parts/FP21A',
 'https://ecat.spectrapremium.com/en/parts/FP21B',
 'https://ecat.spectrapremium.com/en/parts/FP22A',
 'https://ecat.spectrapremium.com/en/parts/FP24B',
 'https://ecat.spectrapremium.com/en/parts/CRP70A',
 'https://ecat.spectrapremium.com/en/parts/CRP72A',
 'https://ecat.spectrapremium.com/en/parts/CRP73A',
 'https://ecat.spectrapremium.com/en/parts/CRP74A',
 'https://ecat.spectrapremium.com/en/parts/CRP75A',
 'https://ecat.spectrapremium.com/en/parts/CRP76A',
 'https://ecat.spectrapremium.com/en/parts/CRP78A',
 'https://ecat.spectrapremium.com/en/parts/DTP01A',
 'https://ecat.spectrapremium.com/en/parts/DTP02A',
 'https://ecat.spectrapremium.com/en/parts/DTP03A',
 'https://ecat.spectrapremium.com/en/parts/DTP04A',
 'https://ecat.spectrapremium.com/en/parts/DTP04B',
 'https://ecat.spectrapremium.com/en/parts/DTP05A',
 'https://ecat.spectrapremium.com/en/parts/DTP06A',
 'https://ecat.spectrapremium.com/en/parts/FP01A',
 'https://ecat.spectrapremium.com/en/parts/FP01B',
 'https://ecat.spectrapremium.com/en/parts/FP02A',
 'https://ecat.spectrapremium.com/en/parts/FP02B',
 'https://ecat.spectrapremium.com/en/parts/FP03A',
 'https://ecat.spectrapremium.com/en/parts/FP05A',
 'https://ecat.spectrapremium.com/en/parts/FP05B',
 'https://ecat.spectrapremium.com/en/parts/FP06A',
 'https://ecat.spectrapremium.com/en/parts/FP07A',
 'https://ecat.spectrapremium.com/en/parts/FP07B',
 'https://ecat.spectrapremium.com/en/parts/FP08A',
 'https://ecat.spectrapremium.com/en/parts/FP08B',
 'https://ecat.spectrapremium.com/en/parts/FP09A',
 'https://ecat.spectrapremium.com/en/parts/FP09B',
 'https://ecat.spectrapremium.com/en/parts/FP09C',
 'https://ecat.spectrapremium.com/en/parts/FP11A',
 'https://ecat.spectrapremium.com/en/parts/FP11B',
 'https://ecat.spectrapremium.com/en/parts/FP11C',
 'https://ecat.spectrapremium.com/en/parts/FP12A',
 'https://ecat.spectrapremium.com/en/parts/FP14A',
 'https://ecat.spectrapremium.com/en/parts/FP14B',
 'https://ecat.spectrapremium.com/en/parts/FP15B',
 'https://ecat.spectrapremium.com/en/parts/FP16B',
 'https://ecat.spectrapremium.com/en/parts/FP17A',
 'https://ecat.spectrapremium.com/en/parts/FP18A',
 'https://ecat.spectrapremium.com/en/parts/FP18B',
 'https://ecat.spectrapremium.com/en/parts/FP18D',
 'https://ecat.spectrapremium.com/en/parts/FP19A',
 'https://ecat.spectrapremium.com/en/parts/FP19B',
 'https://ecat.spectrapremium.com/en/parts/FP19C',
 'https://ecat.spectrapremium.com/en/parts/FP20A',
 'https://ecat.spectrapremium.com/en/parts/FP20B',
 'https://ecat.spectrapremium.com/en/parts/FP21A',
 'https://ecat.spectrapremium.com/en/parts/FP21B',
 'https://ecat.spectrapremium.com/en/parts/FP22A',
 'https://ecat.spectrapremium.com/en/parts/FP24B',
 'https://ecat.spectrapremium.com/en/parts/FP25A',
 'https://ecat.spectrapremium.com/en/parts/FP26A',
 'https://ecat.spectrapremium.com/en/parts/FP27A',
 'https://ecat.spectrapremium.com/en/parts/FP41A',
 'https://ecat.spectrapremium.com/en/parts/FP42A',
 'https://ecat.spectrapremium.com/en/parts/FP43A',
 'https://ecat.spectrapremium.com/en/parts/FP45A',
 'https://ecat.spectrapremium.com/en/parts/FP45B',
 'https://ecat.spectrapremium.com/en/parts/FP46A',
 'https://ecat.spectrapremium.com/en/parts/FP46B',
 'https://ecat.spectrapremium.com/en/parts/FP47A',
 'https://ecat.spectrapremium.com/en/parts/FP48A',
 'https://ecat.spectrapremium.com/en/parts/FP49A',
 'https://ecat.spectrapremium.com/en/parts/FP50A',
 'https://ecat.spectrapremium.com/en/parts/FP51A',
 'https://ecat.spectrapremium.com/en/parts/FP52A',
 'https://ecat.spectrapremium.com/en/parts/FP53A',
 'https://ecat.spectrapremium.com/en/parts/FP54A',
 'https://ecat.spectrapremium.com/en/parts/FP54B',
 'https://ecat.spectrapremium.com/en/parts/FP54C',
 'https://ecat.spectrapremium.com/en/parts/FP55A',
 'https://ecat.spectrapremium.com/en/parts/FP56A',
 'https://ecat.spectrapremium.com/en/parts/FP57A',
 'https://ecat.spectrapremium.com/en/parts/FP58A',
 'https://ecat.spectrapremium.com/en/parts/FP61A',
 'https://ecat.spectrapremium.com/en/parts/FP63A',
 'https://ecat.spectrapremium.com/en/parts/FP64A',
 'https://ecat.spectrapremium.com/en/parts/FP65A',
 'https://ecat.spectrapremium.com/en/parts/FP66A',
 'https://ecat.spectrapremium.com/en/parts/FP66B',
 'https://ecat.spectrapremium.com/en/parts/FP67A',
 'https://ecat.spectrapremium.com/en/parts/FP68A',
 'https://ecat.spectrapremium.com/en/parts/FP69A',
 'https://ecat.spectrapremium.com/en/parts/FP70A',
 'https://ecat.spectrapremium.com/en/parts/FP71A',
 'https://ecat.spectrapremium.com/en/parts/FP72A',
 'https://ecat.spectrapremium.com/en/parts/FP73A',
 'https://ecat.spectrapremium.com/en/parts/FP74A',
 'https://ecat.spectrapremium.com/en/parts/FP75A',
 'https://ecat.spectrapremium.com/en/parts/FP76A',
 'https://ecat.spectrapremium.com/en/parts/FP77A',
 'https://ecat.spectrapremium.com/en/parts/FP78A',
 'https://ecat.spectrapremium.com/en/parts/FP78B',
 'https://ecat.spectrapremium.com/en/parts/FP79A',
 'https://ecat.spectrapremium.com/en/parts/FP80A',
 'https://ecat.spectrapremium.com/en/parts/FP81A',
 'https://ecat.spectrapremium.com/en/parts/FP82A',
 'https://ecat.spectrapremium.com/en/parts/FP83A',
 'https://ecat.spectrapremium.com/en/parts/FP86A',
 'https://ecat.spectrapremium.com/en/parts/FP87A',
 'https://ecat.spectrapremium.com/en/parts/FP88A',
 'https://ecat.spectrapremium.com/en/parts/FP89A',
 'https://ecat.spectrapremium.com/en/parts/FP90A',
 'https://ecat.spectrapremium.com/en/parts/FP92A',
 'https://ecat.spectrapremium.com/en/parts/FP94A',
 'https://ecat.spectrapremium.com/en/parts/FP95A',
 'https://ecat.spectrapremium.com/en/parts/FP96A',
 'https://ecat.spectrapremium.com/en/parts/GMP01A',
 'https://ecat.spectrapremium.com/en/parts/GMP01B',
 'https://ecat.spectrapremium.com/en/parts/GMP02A',
 'https://ecat.spectrapremium.com/en/parts/GMP02B',
 'https://ecat.spectrapremium.com/en/parts/GMP03A',
 'https://ecat.spectrapremium.com/en/parts/GMP04A',
 'https://ecat.spectrapremium.com/en/parts/GMP05A',
 'https://ecat.spectrapremium.com/en/parts/GMP07A',
 'https://ecat.spectrapremium.com/en/parts/GMP07B',
 'https://ecat.spectrapremium.com/en/parts/GMP08A',
 'https://ecat.spectrapremium.com/en/parts/GMP08B',
 'https://ecat.spectrapremium.com/en/parts/GMP09A',
 'https://ecat.spectrapremium.com/en/parts/GMP100A',
 'https://ecat.spectrapremium.com/en/parts/GMP101A',
 'https://ecat.spectrapremium.com/en/parts/GMP102A',
 'https://ecat.spectrapremium.com/en/parts/GMP103A',
 'https://ecat.spectrapremium.com/en/parts/GMP105A',
 'https://ecat.spectrapremium.com/en/parts/GMP109A',
 'https://ecat.spectrapremium.com/en/parts/GMP10A',
 'https://ecat.spectrapremium.com/en/parts/GMP112A',
 'https://ecat.spectrapremium.com/en/parts/GMP113A',
 'https://ecat.spectrapremium.com/en/parts/GMP114A',
 'https://ecat.spectrapremium.com/en/parts/GMP115A',
 'https://ecat.spectrapremium.com/en/parts/GMP11A',
 'https://ecat.spectrapremium.com/en/parts/GMP11B',
 'https://ecat.spectrapremium.com/en/parts/GMP121A',
 'https://ecat.spectrapremium.com/en/parts/GMP123A',
 'https://ecat.spectrapremium.com/en/parts/GMP124A',
 'https://ecat.spectrapremium.com/en/parts/GMP125A',
 'https://ecat.spectrapremium.com/en/parts/GMP127A',
 'https://ecat.spectrapremium.com/en/parts/GMP128A',
 'https://ecat.spectrapremium.com/en/parts/GMP129A',
 'https://ecat.spectrapremium.com/en/parts/GMP12A',
 'https://ecat.spectrapremium.com/en/parts/GMP14A',
 'https://ecat.spectrapremium.com/en/parts/GMP15A',
 'https://ecat.spectrapremium.com/en/parts/GMP19A',
 'https://ecat.spectrapremium.com/en/parts/GMP20A',
 'https://ecat.spectrapremium.com/en/parts/GMP20B',
 'https://ecat.spectrapremium.com/en/parts/GMP21A',
 'https://ecat.spectrapremium.com/en/parts/GMP24A',
 'https://ecat.spectrapremium.com/en/parts/GMP24B',
 'https://ecat.spectrapremium.com/en/parts/GMP25A',
 'https://ecat.spectrapremium.com/en/parts/GMP25B',
 'https://ecat.spectrapremium.com/en/parts/BMP02A',
 'https://ecat.spectrapremium.com/en/parts/BMP03A',
 'https://ecat.spectrapremium.com/en/parts/BMP05A',
 'https://ecat.spectrapremium.com/en/parts/BMP06A',
 'https://ecat.spectrapremium.com/en/parts/BMP07A',
 'https://ecat.spectrapremium.com/en/parts/BMP08A',
 'https://ecat.spectrapremium.com/en/parts/BMP09A',
 'https://ecat.spectrapremium.com/en/parts/BMP10A',
 'https://ecat.spectrapremium.com/en/parts/BMP11A',
 'https://ecat.spectrapremium.com/en/parts/BMP12A',
 'https://ecat.spectrapremium.com/en/parts/BMP13A',
 'https://ecat.spectrapremium.com/en/parts/BMP14A',
 'https://ecat.spectrapremium.com/en/parts/BMP15A',
 'https://ecat.spectrapremium.com/en/parts/BMP16A',
 'https://ecat.spectrapremium.com/en/parts/BMP17A',
 'https://ecat.spectrapremium.com/en/parts/BMP19A',
 'https://ecat.spectrapremium.com/en/parts/BMP20A',
 'https://ecat.spectrapremium.com/en/parts/BMP21A',
 'https://ecat.spectrapremium.com/en/parts/BMP22A',
 'https://ecat.spectrapremium.com/en/parts/BMP23A',
 'https://ecat.spectrapremium.com/en/parts/BMP24A',
 'https://ecat.spectrapremium.com/en/parts/CATP04A',
 'https://ecat.spectrapremium.com/en/parts/CATP05A',
 'https://ecat.spectrapremium.com/en/parts/CMP01A',
 'https://ecat.spectrapremium.com/en/parts/CMP02A',
 'https://ecat.spectrapremium.com/en/parts/CMP03A',
 'https://ecat.spectrapremium.com/en/parts/CMP04A',
 'https://ecat.spectrapremium.com/en/parts/CMP05A',
 'https://ecat.spectrapremium.com/en/parts/CMP06A',
 'https://ecat.spectrapremium.com/en/parts/CMP08A',
 'https://ecat.spectrapremium.com/en/parts/CRP01A',
 'https://ecat.spectrapremium.com/en/parts/CRP02A',
 'https://ecat.spectrapremium.com/en/parts/CRP03A',
 'https://ecat.spectrapremium.com/en/parts/CRP03B',
 'https://ecat.spectrapremium.com/en/parts/CRP04A',
 'https://ecat.spectrapremium.com/en/parts/CRP04B',
 'https://ecat.spectrapremium.com/en/parts/CRP05A',

In [2]:
df = pd.DataFrame(columns=['Url',
                           'Src',
                           'status'])

df

Empty DataFrame
Columns: [Url, Src, status]
Index: []

In [3]:
import requests
i = 1

resp = requests.get(list_url[i]).text

resp

'<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="utf-8"/>    <link href="/safari-pinned-tab.svg" color="#036" rel="mask-icon"/>    <meta content="ie=edge" http-equiv="x-ua-compatible"/>    <meta name="description" content="Spectra Premium believes in a green and sustainable economy. That&#039;s why it uses its core competencies of metallurgical transformation, heat transfer and high quality assembly capacity, as well as its extensive expertise, to stand out in the booming vehicle electrification sector in Quebec."/>    <link href="/favicon.ico" type="image/x-icon" rel="icon"/><link href="/favicon.ico" type="image/x-icon" rel="shortcut icon"/>    <link href="/apple-touch-icon.png" rel="apple-touch-icon"/>    <link href="/manifest.php?locale=en" rel="manifest"/>    <link href="https://fonts.googleapis.com" rel="preconnect"/>    <link href="https://fonts.gstatic.com" crossorigin="" rel="preconnect"/>    <meta name="msapplication-TileColor" content="#036"/>    <meta property="og:image" content="https://ecat.spectrapremium.com/logo-spectra--open-graph.jpg"/>    <meta property="og:title" content="CRP18A"/>    <meta property="og:type" content="website"/>    <meta property="og:url" content="https://ecat.spectrapremium.com/en/parts/CRP18A"/>    <meta name="theme-color" content="#036"/>    <meta name="viewport" content="width=device-width, initial-scale=1"/>                <style>:root { --view:\'View\'; --year:\'Year\'; --fuel:\'Fuel\'; --fueldel:\'Fuel Del.\'; --asp:\'ASP.\'; --engvin:\'Eng. VIN\'; --engdesg:\'Eng. Desg.\'; --cc:\'CC\'; --cid:\'CID\'; }</style>\n                <link rel="stylesheet" href="/css/pages/part.css?id=3557f03f6ffadace3fa5fe6aa806b9d2"/>    <title>CRP18A</title>\n            <!-- Google Tag Manager (head du document) -->\n\n<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':\nnew Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],\nj=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\n\'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);\n})(window,document,\'script\',\'dataLayer\',\'GTM-MHFHCJL\');</script>\n\n<!-- End Google Tag Manager -->\n        <script src="https://www.google.com/recaptcha/api.js?hl=en" async="async" defer="defer"></script></head>\n<body class="produits view part">\n            <!-- Google Tag Manager (noscript) -->\n\n<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MHFHCJL"\nheight="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>\n\n<!-- End Google Tag Manager (noscript) -->\n            <header class="header">\n    <nav class="header__nav">\n        <a href="/en">\n            <picture>\n                <source media="(max-width: 767px)" srcset="/img/logo-spectra--small.svg">\n                <source media="(min-width: 768px)" srcset="/img/logo-spectra--medium.svg">\n                <img src="/img/logo-spectra--medium.svg" alt="Spectra Premium" class="header__logo" height="42" width="161"/>            </picture>\n        </a>\n        <div class="header__colonne-droite">\n                            <button id="login-btn" class="btn btn--login">Login</button>\n                <form method="post" accept-charset="utf-8" class="form header__login-form" id="login-form" action="/en/users/login"><div style="display:none;"><input class="input input--hidden" type="hidden" name="_csrfToken" autocomplete="off" value="y0RTJKBOQRCbWFkocfSgvjCNFz2f7SEhcUvnqp4m0Z3i1w6uu7NxdnruCP2T1dUbajVMUo9hk0VqcGiiRNHiRUJfa8JgLH9dCb8kDK3dRRkVc4Sd/RHoqIHiPp6C0URFTdtryKrn5S8MUCplu1Klcw=="/></div><aside class="header__login-form__info">\n    <span class="material-icons header__login-form__info-icon">info</span>\n    <div class="header__login-form__info-container">\n        <p class="header__login-form__paragraph">Enter your personal login and password.</p>\n        <p class="header__login-form__paragraph">Caution: Sharing the same username among colleagues or opening the session on different computers may create order conflicts and disrupt the email confirmation of the receipts.</p>\n        <p class="header__login-form__paragraph">Your administrator may create your own account. If you have any questions, email us at <a href="mailto:internaldataservice@spectrapremium.com" class="link">internaldataservice@spectrapremium.com</a>.</p>\n    </div>\n</aside>\n<div class="header__login-form__title">Login</div>\n<div class="input-container input-container--text"><input class="input input--text" type="text" name="username" id="username-login-form" placeholder="Username" aria-label="Username"/></div><div class="input-container input-container--password"><input class="input input--password" type="password" name="password" autocomplete="current-password" id="password-login-form" placeholder="Password" aria-label="Password"/></div><div class="input-container input-container--checkbox"><input class="input input--hidden" type="hidden" name="remember_me" value="0"/><label for="remember-me">Remember Me<input class="checkbox" type="checkbox" name="remember_me" value="1" id="remember-me"></label></div><button class="btn" type="submit">Login</button><a href="/en/pages/embedded-forms?name=open-a-commercial-account" class="link">Open a commercial account</a><span id="forgot-password-span" class="link">Forgot your password?</span>\n<p class="header__login-form__paragraph">For any problem or inquiry please consult our <a href="https://ecat.spectrapremium.com/documents/guides/ecommerce_user_guide.pdf" class="link">user guide</a> or email us at <a href="mailto:techinfo@spectrapremium.com" class="link">techinfo@spectrapremium.com</a>.</p>\n<div style="display:none;"><input class="input input--hidden" type="hidden" name="_Token[fields]" autocomplete="off" value="8dc234b94feb0d78e1d2e29af393df2cd3ab302c%3A"/><input class="input input--hidden" type="hidden" name="_Token[unlocked]" autocomplete="off" value=""/></div></form>                <form method="post" accept-charset="utf-8" class="form header__forgot-password-form" id="forgot-password-form" action="/en/users/forgot-password"><div style="display:none;"><input class="input input--hidden" type="hidden" name="_csrfToken" autocomplete="off" value="y0RTJKBOQRCbWFkocfSgvjCNFz2f7SEhcUvnqp4m0Z3i1w6uu7NxdnruCP2T1dUbajVMUo9hk0VqcGiiRNHiRUJfa8JgLH9dCb8kDK3dRRkVc4Sd/RHoqIHiPp6C0URFTdtryKrn5S8MUCplu1Klcw=="/></div><div class="header__forgot-password-form__title">Forgot your password?</div>\n<p class="header__forgot-password-form__paragraph header__forgot-password-form__paragraph--brand-color">Please enter your username. We will send you an email explaining how to reset your password (it may be in your spam folder).</p>\n<div class="input-container input-container--text"><input class="input input--text" type="text" name="username" id="username-forgot-password-form" placeholder="Username" aria-label="Username"/></div><button class="btn" type="submit">Submit</button><p class="header__login-form__paragraph">If you don’t remember your username, contact your company account administrator. For any other problem or inquiry, email us at <a href="mailto:internaldataservice@spectrapremium.com" class="link">internaldataservice@spectrapremium.com</a>.</p>\n<div style="display:none;"><input class="input input--hidden" type="hidden" name="_Token[fields]" autocomplete="off" value="63b7f519931f73231a0198f1daf6509db080888e%3A"/><input class="input input--hidden" type="hidden" name="_Token[unlocked]" autocomplete="off" value=""/></div></form>                        <button id="menu-btn" class="material-icons md-48 header__btn-menu">menu</button>\n            <ul id="menu-list" class="header__menu"><li class="header__menu__item"><a href="https://ecat.spectrapremium.com/es/parts/CRP18A" class="link header__menu__link">Español</a></li><li class="header__menu__item"><a href="https://ecat.spectrapremium.com/fr/parts/CRP18A" class="link header__menu__link">Français</a></li><li class="header__menu__item"><hr></li><li class="header__menu__item"><a href="/en/find-a-store" class="link header__menu__link">Find a store</a></li><li class="header__menu__item"><a href="https://www.spectrapremium.com/en/contact" class="link header__menu__link" target="_blank">Contact us</a></li></ul>        </div>\n    </nav>\n</header>\n    <main class="main">\n        <div class="main__container">\n            <div class="search-container">\n    <div class="search">\n                <div class="search__icon-searches">\n            <span class="material-icons md-48">search</span>\n            <ul class="search__searches">\n                <li class="search__search"><button id="btn-vehicle-search" class="btn btn--search" data-search="vehicleSearch">Vehicle | VIN</button></li>\n                <li class="search__search"><button id="btn-part-number-search" class="btn btn--search" data-search="partNumberSearchForm">Part | Interchange #</button></li>\n                <li class="search__search"><button id="btn-advanced-search" class="btn btn--search" data-search="advancedSearchForm">Advanced Search</button></li>\n            </ul>\n        </div>\n        <div id="vehicle-search" class="search__vehicle-search">\n    <form method="get" accept-charset="utf-8" class="form search__vehicle-search-form" data-error-message="Please fill out this field." id="vehicle-search-form" action="/en/parts/CRP18A">        <div class="input-container input-container--select required"><select class="select" name="year" id="vehicle-search-year" required="required"><option value="">Year</option><option value="2024">2024</option><option value="2023">2023</option><option value="2022">2022</option><option value="2021">2021</option><option value="2020">2020</option><option value="2019">2019</option><option value="2018">2018</option><option value="2017">2017</option><option value="2016">2016</option><option value="2015">2015</option><option value="2014">2014</option><option value="2013">2013</option><option value="2012">2012</option><option value="2011">2011</option><option value="2010">2010</option><option value="2009">2009</option><option value="2008">2008</option><option value="2007">2007</option><option value="2006">2006</option><option value="2005">2005</option><option value="2004">2004</option><option value="2003">2003</option><option value="2002">2002</option><option value="2001">2001</option><option value="2000">2000</option><option value="1999">1999</option><option value="1998">1998</option><option value="1997">1997</option><option value="1996">1996</option><option value="1995">1995</option><option value="1994">1994</option><option value="1993">1993</option><option value="1992">1992</option><option value="1991">1991</option><option value="1990">1990</option><option value="1989">1989</option><option value="1988">1988</option><option value="1987">1987</option><option value="1986">1986</option><option value="1985">1985</option><option value="1984">1984</option><option value="1983">1983</option><option value="1982">1982</option><option value="1981">1981</option><option value="1980">1980</option><option value="1979">1979</option><option value="1978">1978</option><option value="1977">1977</option><option value="1976">1976</option><option value="1975">1975</option><option value="1974">1974</option><option value="1973">1973</option><option value="1972">1972</option><option value="1971">1971</option><option value="1970">1970</option><option value="1969">1969</option><option value="1968">1968</option><option value="1967">1967</option><option value="1966">1966</option><option value="1965">1965</option><option value="1964">1964</option><option value="1963">1963</option><option value="1962">1962</option><option value="1961">1961</option><option value="1960">1960</option><option value="1959">1959</option><option value="1958">1958</option><option value="1957">1957</option><option value="1956">1956</option><option value="1955">1955</option><option value="1954">1954</option><option value="1953">1953</option><option value="1952">1952</option><option value="1951">1951</option><option value="1950">1950</option><option value="1949">1949</option><option value="1948">1948</option><option value="1947">1947</option><option value="1946">1946</option><option value="1945">1945</option><option value="1944">1944</option><option value="1943">1943</option><option value="1942">1942</option><option value="1938">1938</option><option value="1937">1937</option></select></div>        <div class="input-container input-container--select required"><select class="select" name="make" id="vehicle-search-make" required="required"><option value="">Make</option></select></div>        <div class="input-container input-container--select required"><select class="select" name="model" id="vehicle-search-model" required="required"><option value="">Model</option></select></div>        <div class="input-container input-container--select required"><select class="select" name="vehiculeIds" id="vehicle-search-submodel" required="required"><option value="">Submodel</option></select></div>        <div class="input-container input-container--select search__vehicle-search-form__motorization"><select class="select" name="vehicule_id" id="vehicle-search-motorization"><option value="">Motorization</option></select></div>    </form>    <div class="search__vin-btn">\n        <span class="search__vin-btn__or">or</span>\n        <form method="get" accept-charset="utf-8" class="form search__vin-search-form" id="vin-search-form" action="/en/vehicules/get-vehicle">            <div class="g-recaptcha"\n                data-sitekey="6Ldad98ZAAAAAF8FuwzhSxxLDDjevI_pY2VMXt9A"\n                data-callback="googleRecaptchaOnSubmit"\n                data-size="invisible">\n            </div>\n            <div class="input-container input-container--text required"><input class="input input--text" type="text" name="vin" id="vin-search-vin" pattern="((?![IOQ])[a-zA-Z0-9]){17}" placeholder="VIN" required="required" title="A VIN is made of alphanumeric characters. A VIN must have 17 characters. 1981 vehicles through present. 17 characters which do not include the letters I (i), O (o), or Q (q) (to avoid confusion with numerals 1 and 0)." aria-required="true" aria-label="VIN"/></div>        </form>        <button class="btn btn--search-search" id="vehicle-search-search-btn" type="submit">Search</button>        <button class="btn btn--search-back" id="vehicle-search-back-btn" type="reset">Back</button>    </div>\n</div>\n        <form method="get" accept-charset="utf-8" class="form search__part-number-search-form" id="part-number-search-form" action="/en/produits/get-product">    <div class="input-container input-container--text required"><input class="input input--text" type="text" name="part-number" id="part-number-search-part-number" maxlength="20" placeholder="Part #" required="required" aria-required="true" aria-label="Part #"/></div>    <div class="search__part-number-search-form__buttons">\n        <button class="add-spinner btn btn--search-search" id="part-number-search-search-btn" type="submit">Search</button>        <button class="btn btn--search-back" id="part-number-search-back-btn" type="reset">Back</button>    </div>\n</form>        <form method="get" accept-charset="utf-8" class="form search__advanced-search-form" id="advanced-search-form" action="/en/parts">    <div class="input-container input-container--select required"><select class="select" name="line" id="advanced-search-line" required="required"><optgroup label="Heating &amp; Cooling"><option value="ags">Active Grille Shutter</option><option value="radiators">Automotive Radiator</option><option value="charge_air_coolers">Charge Air Cooler</option><option value="coolant_test_strips">Coolant Test Strip</option><option value="cooling_fan_assem">Cooling Fan Assembly</option><option value="fluid_coolers">Fluid Cooler</option><option value="indus_complete_radiators">HD Radiator</option><option value="heaters">Heater</option><option value="heavy_duty_heater">Heavy duty heater</option><option value="intercoolers">Intercooler</option></optgroup><optgroup label="Fuel Delivery"><option value="fuel_injection_pumps">Fuel Injection Pump</option><option value="fuel_modules">Fuel Module</option><option value="fuel_pumps">Fuel Pump</option><option value="fuel_pump_drivers">Fuel Pump Driver Module</option><option value="fuel_system_acc">Fuel System Accessory</option><option value="fuel_tank_assemblies">Fuel Tank Assembly</option><option value="sending_units">Sending Unit</option><option value="strainers">Strainer</option></optgroup><optgroup label="Ignition &amp; Engine Management"><option value="camshaft_phasers">Camshaft Phasers</option><option value="camshaft_position_sensors">Camshaft Position Sensor</option><option value="crankshaft_position_sensors">Crankshaft Position Sensor</option><option value="electronic_throttle_bodies">Electronic Throttle Body</option><option value="emission_components">Emission Component</option><option value="egr_sensors">Exhaust Sensors</option><option value="ignition_coils">Ignition Coil</option><option value="manifold_pressure_sensors">Manifold Absolute Pressure Sensor</option><option value="maf_sensors">Mass Airflow Sensor</option><option value="oxygen_sensors">Oxygen Sensor</option><option value="variable_timing_products">Variable Timing Products</option><option value="vvt">Variable Valve Timing Solenoid</option></optgroup><optgroup label="Air conditioning"><option value="accumulators">Accumulator</option><option value="blower_motors">Blower Motor</option><option value="compressors">Compressor</option><option value="condensers">Condenser</option><option value="evaporators">Evaporator</option><option value="heavy_duty_condenser">Heavy duty condenser</option></optgroup><optgroup label="Undercar"><option value="filler_necks">Filler Neck</option><option value="filler_neck_acc">Filler Neck Accessory</option><option value="filler_neck_hoses">Filler Neck Hose</option><option value="wiring_harnesses">Fuel Pump Accessory</option><option value="fuel_tanks">Fuel Tank</option><option value="gaskets">Gasket</option><option value="lock_rings">Lock Ring</option><option value="oil_pans">Oil Pan</option><option value="straps">Strap</option></optgroup><optgroup label="Classic parts"><option value="body_panels">Body Panel</option><option value="classic_fuel_tank">Classic Fuel Tank</option><option value="classic_inj_fuel_tanks">Classic Injection Fuel Tank</option><option value="sending_unit_classic">Sending Unit Classic</option></optgroup></select></div>    <div class="search__advanced-search-form__buttons">\n        <button class="add-spinner btn btn--search-search" id="advanced-search-search-btn" type="submit">Search</button>        <button class="btn btn--search-back" id="advanced-search-back-btn" type="reset">Back</button>    </div>\n</form>    </div>\n</div>\n<div class="part__container">\n    <ul class="fil-ariane"><li><a href="/en" class="fil-ariane__link">Home</a></li><li><span class="material-icons">navigate_next</span></li><li><a href="/en/parts/CRP18A" class="fil-ariane__link">CRP18A</a></li></ul>    <div class="part__canada-ligne-image-formulaire-code-specifications-container">\n        <div class="part__canada-ligne-image-formulaire">\n            <div class="part__canada-ligne-image-formulaire-container">\n                <div class="part__canada-ligne-image-magic-scroll">\n                    <div class="part__canada-ligne-image">\n                        <div class="part__canada-ligne">\n                                                        Oil Pan                        </div>\n                        <div class="part__zoom-gallery">\n                                                                                                <div id="magic-360-container" class="magic-360-container">\n                                                                                <a href="/img/produits/CRP18A-01-01.jp

In [4]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(resp, 'lxml')

print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <link color="#036" href="/safari-pinned-tab.svg" rel="mask-icon"/>
  <meta content="ie=edge" http-equiv="x-ua-compatible"/>
  <meta content="Spectra Premium believes in a green and sustainable economy. That's why it uses its core competencies of metallurgical transformation, heat transfer and high quality assembly capacity, as well as its extensive expertise, to stand out in the booming vehicle electrification sector in Quebec." name="description"/>
  <link href="/favicon.ico" rel="icon" type="image/x-icon"/>
  <link href="/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
  <link href="/apple-touch-icon.png" rel="apple-touch-icon"/>
  <link href="/manifest.php?locale=en" rel="manifest"/>
  <link href="https://fonts.googleapis.com" rel="preconnect"/>
  <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
  <meta content="#036" name="msapplication-TileColor"/>
  <meta content="https://ecat.spectrapremium.com/logo-spectra--open-graph.jpg" property="og:image"/>
  <meta content="CRP18A" property="og:title"/>
  <meta content="website" property="og:type"/>
  <meta content="https://ecat.spectrapremium.com/en/parts/CRP18A" property="og:url"/>
  <meta content="#036" name="theme-color"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <style>
   :root { --view:'View'; --year:'Year'; --fuel:'Fuel'; --fueldel:'Fuel Del.'; --asp:'ASP.'; --engvin:'Eng. VIN'; --engdesg:'Eng. Desg.'; --cc:'CC'; --cid:'CID'; }
  </style>
  <link href="/css/pages/part.css?id=3557f03f6ffadace3fa5fe6aa806b9d2" rel="stylesheet"/>
  <title>
   CRP18A
  </title>
  <!-- Google Tag Manager (head du document) -->
  <script>
   (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MHFHCJL');
  </script>
  <!-- End Google Tag Manager -->
  <script async="async" defer="defer" src="https://www.google.com/recaptcha/api.js?hl=en">
  </script>
 </head>
 <body class="produits view part">
  <!-- Google Tag Manager (noscript) -->
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-MHFHCJL" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->
  <header class="header">
   <nav class="header__nav">
    <a href="/en">
     <picture>
      <source media="(max-width: 767px)" srcset="/img/logo-spectra--small.svg">
       <source media="(min-width: 768px)" srcset="/img/logo-spectra--medium.svg">
        <img alt="Spectra Premium" class="header__logo" height="42" src="/img/logo-spectra--medium.svg" width="161"/>
       </source>
      </source>
     </picture>
    </a>
    <div class="header__colonne-droite">
     <button class="btn btn--login" id="login-btn">
      Login
     </button>
     <form accept-charset="utf-8" action="/en/users/login" class="form header__login-form" id="login-form" method="post">
      <div style="display:none;">
       <input autocomplete="off" class="input input--hidden" name="_csrfToken" type="hidden" value="y0RTJKBOQRCbWFkocfSgvjCNFz2f7SEhcUvnqp4m0Z3i1w6uu7NxdnruCP2T1dUbajVMUo9hk0VqcGiiRNHiRUJfa8JgLH9dCb8kDK3dRRkVc4Sd/RHoqIHiPp6C0URFTdtryKrn5S8MUCplu1Klcw=="/>
      </div>
      <aside class="header__login-form__info">
       <span class="material-icons header__login-form__info-icon">
        info
       </span>
       <div class="header__login-form__info-container">
        <p class="header__login-form__paragraph">
         Enter your personal login and password.
        </p>
        <p class="header__login-form__paragraph">
         Caution: Sharing the same username among colleagues or opening the session on different computers may create order conflicts and disrupt the email confirmation of the receipts.
        </p>
        <p class="header__login-form__paragraph">
         Your administrator may create your own account. If you have any questions, email us at
         <a class="link" href="mailto:internaldataservice@spectrapremium.com">
          internaldataservice@spectrapremium.com
         </a>
         .
        </p>
       </div>
      </aside>
      <div class="header__login-form__title">
       Login
      </div>
      <div class="input-container input-container--text">
       <input aria-label="Username" class="input input--text" id="username-login-form" name="username" placeholder="Username" type="text"/>
      </div>
      <div class="input-container input-container--password">
       <input aria-label="Password" autocomplete="current-password" class="input input--password" id="password-login-form" name="password" placeholder="Password" type="password"/>
      </div>
      <div class="input-container input-container--checkbox">
       <input class="input input--hidden" name="remember_me" type="hidden" value="0"/>
       <label for="remember-me">
        Remember Me
        <input class="checkbox" id="remember-me" name="remember_me" type="checkbox" value="1"/>
       </label>
      </div>
      <button class="btn" type="submit">
       Login
      </button>
      <a class="link" href="/en/pages/embedded-forms?name=open-a-commercial-account">
       Open a commercial account
      </a>
      <span class="link" id="forgot-password-span">
       Forgot your password?
      </span>
      <p class="header__login-form__paragraph">
       For any problem or inquiry please consult our
       <a class="link" href="https://ecat.spectrapremium.com/documents/guides/ecommerce_user_guide.pdf">
        user guide
       </a>
       or email us at
       <a class="link" href="mailto:techinfo@spectrapremium.com">
        techinfo@spectrapremium.com
       </a>
       .
      </p>
      <div style="display:none;">
       <input autocomplete="off" class="input input--hidden" name="_Token[fields]" type="hidden" value="8dc234b94feb0d78e1d2e29af393df2cd3ab302c%3A"/>
       <input autocomplete="off" class="input input--hidden" name="_Token[unlocked]" type="hidden" value=""/>
      </div>
     </form>
     <form accept-charset="utf-8" action="/en/users/forgot-password" class="form header__forgot-password-form" id="forgot-password-form" method="post">
      <div style="display:none;">
       <input autocomplete="off" class="input input--hidden" name="_csrfToken" type="hidden" value="y0RTJKBOQRCbWFkocfSgvjCNFz2f7SEhcUvnqp4m0Z3i1w6uu7NxdnruCP2T1dUbajVMUo9hk0VqcGiiRNHiRUJfa8JgLH9dCb8kDK3dRRkVc4Sd/RHoqIHiPp6C0URFTdtryKrn5S8MUCplu1Klcw=="/>
      </div>
      <div class="header__forgot-password-form__title">
       Forgot your password?
      </div>
      <p class="header__forgot-password-form__paragraph header__forgot-password-form__paragraph--brand-color">
       Please enter your username. We will send you an email explaining how to reset your password (it may be in your spam folder).
      </p>
      <div class="input-container input-container--text">
       <input aria-label="Username" class="input input--text" id="username-forgot-password-form" name="username" placeholder="Username" type="text"/>
      </div>
      <button class="btn" type="submit">
       Submit
      </button>
      <p class="header__login-form__paragraph">
       If you don’t remember your username, contact your company account administrator. For any other problem or inquiry, email us at
       <a class="link" href="mailto:internaldataservice@spectrapremium.com">
        internaldataservice@spectrapremium.com
       </a>
       .
      </p>
      <div style="display:none;">
       <input autocomplete="off" class="input input--hidden" name="_Token[fields]" type="hidden" value="63b7f519931f73231a0198f1daf6509db080888e%3A"/>
       <input autocomplete="off" class="input input--hidden" name="_Token[unlocked]" type="hidden" value=""/>
      </div>
     </form>
     <button class="material-icons md-48 header__btn-menu" id="menu-btn">
      menu
     </button>
     <ul class="header__menu" id="menu-list">
      <li class="header__menu__item">
       <a class="link header__menu__link" href="https://ecat.spectrapremium.com/es/parts/CRP18A">
        Español
       </a>
      </li>
      <li class="header__menu__item">
       <a class="link header__menu__link" href="https://ecat.spectrapremium.com/fr/parts/CRP18A">
        Français
       </a>
      </li>
      <li class="header__menu__item">
       <hr/>
      </li>
      <li class="header__menu__item">
       <a class="link header__menu__link" href="/en/find-a-store">
        Find a store
       </a>
      </li>
      <li class="header__menu__item">
       <a class="link header__menu__link" href="https://www.spectrapremium.com/en/contact" target="_blank">
        Contact us
       </a>
      </li>
     </ul>
    </div>
   </nav>
  </header>
  <main class="main">
   <div class="main__container">
    <div class="search-container">
     <div class="search">
      <div class="search__icon-searches">
       <span class="material-icons md-48">
        search
       </span>
       <ul class="search__searches">
        <li class="search__search">
         <button class="btn btn--search" data-search="vehicleSearch" id="btn-vehicle-search">
          Vehicle | VIN
         </button>
        </li>
        <li class="search__search">
         <button class="btn btn--search" data-search="partNumberSearchForm" id="btn-part-number-search">
          Part | Interchange #
         </button>
        </li>
        <li class="search__search">
         <button class="btn btn--search" data-search="advancedSearchForm" id="btn-advanced-search">
          Advanced Search
         </button>
        </li>
       </ul>
      </div>
      <div class="search__vehicle-search" id="vehicle-search">
       <form accept-charset="utf-8" action="/en/parts/CRP18A" class="form search__vehicle-search-form" data-error-message="Please fill out this field." id="vehicle-search-form" method="get">
        <div class="input-container input-container--select required">
         <select class="select" id="vehicle-search-year" name="year" required="required">
          <option value="">
           Year
          </option>
          <option value="2024">
           2024
          </option>
          <option value="2023">
           2023
          </option>
          <option value="2022">
           2022
          </option>
          <option value="2021">
           2021
          </option>
          <option value="2020">
           2020
          </option>
          <option value="2019">
           2019
          </option>
          <option value="2018">
           2018
          </option>
          <option value="2017">
           2017
          </option>
          <option value="2016">
           2016
          </option>
          <option value="2015">
           2015
          </option>
          <option value="2014">
           2014
          </option>
          <option value="2013">
           2013
          </option>
          <option value="2012">
           2012
          </option>
          <option value="2011">
           2011
          </option>
          <option value="2010">
           2010
          </option>
          <option value="2009">
           2009
          </option>
          <option value="2008">
           2008
          </option>
          <option value="2007">
           2007
          </option>
          <option value="2006">
           2006
          </option>
          <option value="2005">
           2005
          </option>
          <option value="2004">
           2004
          </option>
          <option value="2003">
           2003
          </option>
          <option value="2002">
           2002
          </option>
          <option value="2001">
           2001
          </option>
          <option value="2000">
           2000
          </option>
          <option value="1999">
           1999
          </option>
          <option value="1998">
           1998
          </option>
          <option value="1997">
           1997
          </option>
          <option value="1996">
           1996
          </option>
          <option value="1995">
           1995
          </option>
          <option value="1994">
           1994
          </option>
          <option value="1993">
           1993
          </option>
          <option value="1992">
           1992
          </option>
          <option value="1991">
           1991
          </option>
          <option value="1990">
           1990
          </option>
          <option value="1989">
           1989
          </option>
          <option value="1988">
           1988
          </option>
          <option value="1987">
           1987
          </option>
          <option value="1986">
           1986
          </option>
          <option value="1985">
           1985
          </option>
          <option value="1984">
           1984
          </option>
          <option value="1983">
           1983
          </option>
          <option value="1982">
           1982
          </option>
          <option value="1981">
           1981
          </option>
          <option value="1980">
           1980
          </option>
          <option value="1979">
           1979
          </option>
          <option value="1978">
           1978
          </option>
          <option value="1977">
           1977
          </option>
          <option value="1976">
           1976
          </option>
          <option value="1975">
           1975
          </option>
          <option value="1974">
           1974
          </option>
          <option value="1973">
           1973
          </option>
          <option value="1972">
           1972
          </option>
          <option value="1971">
           1971
          </option>
          <option value="1970">
           1970
          </option>
          <option value="1969">
           1969
          </option>
          <option value="1968">
           1968
          </option>
          <option value="1967">
           1967
          </option>
          <option value="1966">
           1966
          </option>
          <option value="1965">
           1965
          </option>
          <option value="1964">
           1964
          </option>
          <option value="1963">
           1963
          </option>
          <option value="1962">
           1962
          </option>
          <option value="1961">
           1961
          </option>
          <option value="1960">
           1960
          </option>
          <option value="1959">
           1959
          </option>
          <option value="1958">
           1958
          </option>
          <option value="1957">
           1957
          </option>
          <option value="1956">
           1956
          </option>
          <option value="1955">
           1955
          </option>
          <option value="1954">
           1954
          </option>
          <option value="1953">
           1953
          </option>
          <option value="1952">
           1952
          </option>
          <option value="1951">
           1951
          </option>
          <option value="1950">
           1950
          </option>
          <option value="1949">
           1949
          </option>
          <option value="1948">
           1948
          </option>
          <option value="1947">
           1947
          </option>
          <option value="1946">
           1946
          </option>
          <option value="1945">
           1945
          </option>
          <option value="1944">
           1944
          </option>
          <option value="1943">
           1943
          </option>
          <option value="1942">
           1942
          </option>
          <option value="1938">
           1938
          </option>
          <option value="1937">
           1937
          </option>
         </select>
        </div>
        <div class="input-container input-container--select required">
         <select class="select" id="vehicle-search-make" name="make" required="required">
          <option value="">
           Make
          </option>
         </select>
        </div>
        <div class="input-container input-container--select required">
         <select class="select" id="vehicle-search-model" name="model" required="required">
          <option value="">
           Model
          </option>
         </select>
        </div>
        <div class="input-container input-container--select required">
         <select class="select" id="vehicle-search-submodel" name="vehiculeIds" required="required">
          <option value="">
           Submodel
          </option>
         </select>
        </div>
        <div class="input-container input-container--select search__vehicle-search-form__motorization">
         <select class="select" id="vehicle-search-motorization" name="vehicule_id">
          <option value="">
           Motorization
          </option>
         </select>
        </div>
       </form>
       <div class="search__vin-btn">
        <span class="search__vin-btn__or">
         or
        </span>
        <form accept-charset="utf-8" action="/en/vehicules/get-vehicle" class="form search__vin-search-form" id="vin-search-form" method="get">
         <div class="g-recaptcha" data-callback="googleRecaptchaOnSubmit" data-sitekey="6Ldad98ZAAAAAF8FuwzhSxxLDDjevI_pY2VMXt9A" data-size="invisible">
         </div>
         <div class="input-container input-container--text required">
          <input aria-label="VIN" aria-required="true" class="input input--text" id="vin-search-vin" name="vin" pattern="((?![IOQ])[a-zA-Z0-9]){17}" placeholder="VIN" required="required" title="A VIN is made of alphanumeric characters. A VIN must have 17 characters. 1981 vehicles through present. 17 characters which do not include the letters I (i), O (o), or Q (q) (to avoid confusion with numerals 1 and 0)." type="text"/>
         </div>
        </form>
        <button class="btn btn--search-search" id="vehicle-search-search-btn" type="submit">
         Search
        </button>
        <button class="btn btn--search-back" id="vehicle-search-back-btn" type="reset">
         Back
        </button>
       </div>
      </div>
      <form accept-charset="utf-8" action="/en/produits/get-product" class="form search__part-number-search-form" id="part-number-search-form" method="get">
       <div class="input-container input-container--text required">
        <input aria-label="Part #" aria-required="true" class="input input--text" id="part-number-search-part-number" maxlength="20" name="part-number" placeholder="Part #" required="required" type="text"/>
       </div>
       <div class="search__part-number-search-form__buttons">
        <button class="add-spinner btn btn--search-search" id="part-number-search-search-btn" type="submit">
         Search
        </button>
        <button class="btn btn--search-back" id="part-number-search-back-btn" type="reset">
         Back
        </button>
       </div>
      </form>
      <form accept-charset="utf-8" action="/en/parts" class="form search__advanced-search-form" id="advanced-search-form" method="get">
       <div class="input-container input-container--select required">
        <select class="select" id="advanced-search-line" name="line" required="required">
         <optgroup label="Heating &amp; Cooling">
          <option value="ags">
           Active Grille Shutter
          </option>
          <option value="radiators">
           Automotive Radiator
          </option>
          <option value="charge_air_coolers">
           Charge Air Cooler
          </option>
          <option value="coolant_test_strips">
           Coolant Test Strip
          </option>

In [5]:
from lxml import etree
html = etree.HTML(str(soup))

src = 'https://ecat.spectrapremium.com' + html.xpath('//div[@class="part__zoom-gallery"]/descendant::img/@src')[0]

src

'https://ecat.spectrapremium.com/img/produits/imagettes/CRP18A-01-01_220.jpg'

In [6]:
df_temp = pd.DataFrame([{'Url': list_url[i],
                         'Src': src,
                         'status': 'ok'}])

df_temp

,Url,Src,status
0,https://ecat.spectrapremium.com/en/parts/CRP18A,https://ecat.spectrapremium.com/img/produits/i...,ok

In [7]:
list_name = [name.text for name in html.xpath('//div[@class="part__nom-spec-valeur-spec"]/descendant::dt[@class="part__nom-spec"]')]
list_value = [value.text for value in html.xpath('//div[@class="part__nom-spec-valeur-spec"]/descendant::dd[@class="part__valeur-spec"]')]

for name, value in zip(list_name, list_value):
    df_temp[name.lower()] = value
    
df = pd.concat([df, df_temp], ignore_index=True).fillna('')

df

,Url,Src,status,description,material,height,drain plug thread,pop. code
0,https://ecat.spectrapremium.com/en/parts/CRP18A,https://ecat.spectrapremium.com/img/produits/i...,ok,Automotive Engine Oil Pan,Cold Rolled Steel (EDDQ),9 In.,M14 X 1.5,D