In [1]:
import pandas as pd

In [2]:
source = r'C:\Users\YangTeng\Desktop\工作\品牌号整合\Joanne【模板】.xlsx'# 输入带查重文件路径

out = r'C:\Users\YangTeng\Desktop\工作\品牌号整合\belt_tensioner_NOW().xlsx' # 输入输出文件路径

In [3]:
brand_first_data = pd.read_excel(source,sheet_name='品牌1',dtype=str).fillna('')
brand_first_data

       品牌1                                                 OE
0    38106                                           10069954
1    38103  10239670;12456152;12561094;12580296;31025168;8...
2    38104                12563083;24503851;24507667;24507684
3    38105  10044970;10078911;10114908;10166387;14091898;1...
4    38102  F37Z6B209A;F3TZ6B209C;F47E6B209AA;F4TE6B209AA;...
..     ...                                                ...
443  39428                                         68201164AA
444  39516                                           12647765
445  39467  2147525;CR3E6B209AB;JR2E6B209AA;JR3E6B209AA;JR...
446  39518                                         1662024020
447  39560                                         JX6Z6A228B

[448 rows x 2 columns]

In [4]:
clean_brand_first_data = brand_first_data[brand_first_data['OE']!='']

clean_brand_first_data

       品牌1                                                 OE
0    38106                                           10069954
1    38103  10239670;12456152;12561094;12580296;31025168;8...
2    38104                12563083;24503851;24507667;24507684
3    38105  10044970;10078911;10114908;10166387;14091898;1...
4    38102  F37Z6B209A;F3TZ6B209C;F47E6B209AA;F4TE6B209AA;...
..     ...                                                ...
443  39428                                         68201164AA
444  39516                                           12647765
445  39467  2147525;CR3E6B209AB;JR2E6B209AA;JR3E6B209AA;JR...
446  39518                                         1662024020
447  39560                                         JX6Z6A228B

[444 rows x 2 columns]

In [5]:
new_brand_first_data = clean_brand_first_data[['品牌1','OE']].copy()
new_brand_first_data['OE'] = new_brand_first_data['OE'].str.split(';')
new_brand_first_data = new_brand_first_data.explode('OE')

new_brand_first_data

       品牌1           OE
0    38106     10069954
1    38103     10239670
1    38103     12456152
1    38103     12561094
1    38103     12580296
..     ...          ...
445  39467  JR2E6B209AA
445  39467  JR3E6B209AA
445  39467   JR3Z6B209A
446  39518   1662024020
447  39560   JX6Z6A228B

[1494 rows x 2 columns]

#### ----------------------------------------------------------------
读取品牌2

In [6]:
brand_second_data = pd.read_excel(source,sheet_name='品牌2',dtype=str).fillna('')
brand_second_data

        品牌2                                                 OE
0    419000  0166200H020;166200H021;166200H030;1662028040;1...
1    419001  3C2E6B209AB;3C2E6B209AC;3C2E6B209DA;3C2Z6B209A...
2    419002                                         7C3Z6B209E
3    419003                                        F7TZ6B209AA
4    419004                                         252813C100
..      ...                                                ...
104  419400                                  12554701;12580828
105  419403
106  419404  5175588AA;6422000070;6422000870;6422001370;680...
107  419422                                  25191534;55563512
108  419504                                         BB3Z6A228A

[109 rows x 2 columns]

In [7]:
clean_brand_second_data = brand_second_data[brand_second_data['OE']!='']

clean_brand_second_data

        品牌2                                                 OE
0    419000  0166200H020;166200H021;166200H030;1662028040;1...
1    419001  3C2E6B209AB;3C2E6B209AC;3C2E6B209DA;3C2Z6B209A...
2    419002                                         7C3Z6B209E
3    419003                                        F7TZ6B209AA
4    419004                                         252813C100
..      ...                                                ...
103  419396                               5080243AA;68001798AB
104  419400                                  12554701;12580828
106  419404  5175588AA;6422000070;6422000870;6422001370;680...
107  419422                                  25191534;55563512
108  419504                                         BB3Z6A228A

[108 rows x 2 columns]

In [8]:
new_brand_second_data = clean_brand_second_data[['品牌2','OE']].copy()
new_brand_second_data['OE'] = new_brand_second_data['OE'].str.split(';')
new_brand_second_data = new_brand_second_data.explode('OE')

new_brand_second_data

        品牌2           OE
0    419000  0166200H020
0    419000   166200H021
0    419000   166200H030
0    419000   1662028040
0    419000   1662028041
..      ...          ...
106  419404   6422001370
106  419404   68040206AA
107  419422     25191534
107  419422     55563512
108  419504   BB3Z6A228A

[196 rows x 2 columns]

#### 通过OE连接品牌1与品牌2

In [9]:
merge_data_12 = pd.merge(new_brand_first_data,new_brand_second_data,on='OE',how='left').fillna('')

merge_data_12

        品牌1           OE 品牌2
0     38106     10069954
1     38103     10239670
2     38103     12456152
3     38103     12561094
4     38103     12580296
...     ...          ...  ..
1489  39467  JR2E6B209AA
1490  39467  JR3E6B209AA
1491  39467   JR3Z6B209A
1492  39518   1662024020
1493  39560   JX6Z6A228B

[1494 rows x 3 columns]

In [10]:
repeat_data_12 = merge_data_12[merge_data_12['品牌2']!='']

repeat_data_12

        品牌1           OE     品牌2
7     38103     89017309  419100
8     38104     12563083  419104
25    38102  F77Z6B209AA  419200
26    38102    ZZM515980  419200
27    38102    ZZM815980  419200
...     ...          ...     ...
1304  39120   53030958AG  419010
1374  39282    5184617AC  419040
1375  39282    5184617AD  419040
1455  39431     12580162  419112
1456  39431     12609719  419112

[172 rows x 3 columns]

In [11]:
OE_repeat_data_12 = repeat_data_12.groupby(['品牌1'],as_index=False,sort=False).agg({'OE':';'.join,'品牌2':';'.join})

OE_repeat_data_12

,品牌1,OE,品牌2
0,38103,89017309,419100
1,38104,12563083,419104
2,38102,F77Z6B209AA;ZZM515980;ZZM815980,419200;419200;419200
3,38108,10229114,419102
4,38107,10069964;10187662,419113;419113
...,...,...,...
100,39185,166200S011;166200S012,419318;419318
101,39242,98094201,419358
102,39120,53030958AC;53030958AD;53030958AE;53030958AG,419008;419010;419010;419010
103,39282,5184617AC;5184617AD,419040;419040
104,39431,12580162;12609719,419112;419112

In [12]:
OE_repeat_data_12['OE'] = OE_repeat_data_12['OE'].str.split(';').apply(lambda x: sorted(list(set(x)), key=x.index))
OE_repeat_data_12['品牌2'] = OE_repeat_data_12['品牌2'].str.split(';').apply(lambda x: sorted(list((set(x))), key=x.index))

In [13]:
OE_repeat_data_12

       品牌1                                                OE               品牌2
0    38103                                        [89017309]          [419100]
1    38104                                        [12563083]          [419104]
2    38102               [F77Z6B209AA, ZZM515980, ZZM815980]          [419200]
3    38108                                        [10229114]          [419102]
4    38107                              [10069964, 10187662]          [419113]
..     ...                                               ...               ...
100  39185                          [166200S011, 166200S012]          [419318]
101  39242                                        [98094201]          [419358]
102  39120  [53030958AC, 53030958AD, 53030958AE, 53030958AG]  [419008, 419010]
103  39282                            [5184617AC, 5184617AD]          [419040]
104  39431                              [12580162, 12609719]          [419112]

[105 rows x 3 columns]

In [14]:
OE_repeat_data_12.rename(columns={'OE':'品牌2重复OE','品牌2':'品牌2'},inplace=True)

OE_repeat_data_12

       品牌1                                           品牌2重复OE               品牌2
0    38103                                        [89017309]          [419100]
1    38104                                        [12563083]          [419104]
2    38102               [F77Z6B209AA, ZZM515980, ZZM815980]          [419200]
3    38108                                        [10229114]          [419102]
4    38107                              [10069964, 10187662]          [419113]
..     ...                                               ...               ...
100  39185                          [166200S011, 166200S012]          [419318]
101  39242                                        [98094201]          [419358]
102  39120  [53030958AC, 53030958AD, 53030958AE, 53030958AG]  [419008, 419010]
103  39282                            [5184617AC, 5184617AD]          [419040]
104  39431                              [12580162, 12609719]          [419112]

[105 rows x 3 columns]

In [15]:
brand_first_data

       品牌1                                                 OE
0    38106                                           10069954
1    38103  10239670;12456152;12561094;12580296;31025168;8...
2    38104                12563083;24503851;24507667;24507684
3    38105  10044970;10078911;10114908;10166387;14091898;1...
4    38102  F37Z6B209A;F3TZ6B209C;F47E6B209AA;F4TE6B209AA;...
..     ...                                                ...
443  39428                                         68201164AA
444  39516                                           12647765
445  39467  2147525;CR3E6B209AB;JR2E6B209AA;JR3E6B209AA;JR...
446  39518                                         1662024020
447  39560                                         JX6Z6A228B

[448 rows x 2 columns]

In [16]:
OE_repeat_data_12['品牌2重复OE'] = OE_repeat_data_12['品牌2重复OE'].apply(lambda x: ';'.join(x))
OE_repeat_data_12['品牌2'] = OE_repeat_data_12['品牌2'].apply(lambda x: ';'.join(x))

In [17]:
OE_repeat_data_12

       品牌1                                      品牌2重复OE            品牌2
0    38103                                     89017309         419100
1    38104                                     12563083         419104
2    38102              F77Z6B209AA;ZZM515980;ZZM815980         419200
3    38108                                     10229114         419102
4    38107                            10069964;10187662         419113
..     ...                                          ...            ...
100  39185                        166200S011;166200S012         419318
101  39242                                     98094201         419358
102  39120  53030958AC;53030958AD;53030958AE;53030958AG  419008;419010
103  39282                          5184617AC;5184617AD         419040
104  39431                            12580162;12609719         419112

[105 rows x 3 columns]

In [18]:
result_12 = pd.merge(brand_first_data,OE_repeat_data_12,on='品牌1',how='left').fillna('')

result_12

,品牌1,OE,品牌2重复OE,品牌2
0,38106,10069954,,
1,38103,10239670;12456152;12561094;12580296;31025168;8...,89017309,419100
2,38104,12563083;24503851;24507667;24507684,12563083,419104
3,38105,10044970;10078911;10114908;10166387;14091898;1...,,
4,38102,F37Z6B209A;F3TZ6B209C;F47E6B209AA;F4TE6B209AA;...,F77Z6B209AA;ZZM515980;ZZM815980,419200
...,...,...,...,...
443,39428,68201164AA,,
444,39516,12647765,,
445,39467,2147525;CR3E6B209AB;JR2E6B209AA;JR3E6B209AA;JR...,,
446,39518,1662024020,,
447,39560,JX6Z6A228B,,

### -----------------------------------------------------------

In [19]:
import datetime

In [20]:
result_12.to_excel(out.replace('NOW()', datetime.datetime.now().strftime("%Y%m%d_%H%M%S")), index=False)

### -------------------------------------------------------------
与品牌3连接

In [21]:
brand_third_data = pd.read_excel(source,sheet_name='品牌3',dtype=str).fillna('')
brand_third_data

        品牌3                                                 OE
0     89206  E7SE6B209AA;E7SE6B209AB;E7SE6B209DB;E7SZ6B209B...
1     89208  E93E6B209AA;E93Z6B209A;F13E6B209AA;F13Z6B209A;...
2     89211                                14102645;8141026450
3     89202       10129518;10129559;10187663;12552358;14103115
4     89218  F06Z6B209A;F2LE6B209BC;F2LE6B209BD;F2LE6B209BE...
..      ...                                                ...
300   89621                                         166200W035
301   89690
302  305207
303   89707
304   89739

[305 rows x 2 columns]

In [22]:
clean_brand_third_data = brand_third_data[brand_third_data['OE']!='']

clean_brand_third_data

       品牌3                                                 OE
0    89206  E7SE6B209AA;E7SE6B209AB;E7SE6B209DB;E7SZ6B209B...
1    89208  E93E6B209AA;E93Z6B209A;F13E6B209AA;F13Z6B209A;...
2    89211                                14102645;8141026450
3    89202       10129518;10129559;10187663;12552358;14103115
4    89218  F06Z6B209A;F2LE6B209BC;F2LE6B209BD;F2LE6B209BE...
..     ...                                                ...
258  89664                             F4TA6B209DB;F4TZ6B209A
260  89663                                           12581203
263  89667                                   89667FN;MD367192
268  89665                                         AL3Z6B209A
300  89621                                         166200W035

[254 rows x 2 columns]

In [23]:
new_brand_third_data = clean_brand_third_data[['品牌3','OE']].copy()
new_brand_third_data['OE'] = new_brand_third_data['OE'].str.split(';')
new_brand_third_data = new_brand_third_data.explode('OE')

new_brand_third_data

       品牌3           OE
0    89206  E7SE6B209AA
0    89206  E7SE6B209AB
0    89206  E7SE6B209DB
0    89206   E7SZ6B209B
0    89206  F1ZE6B209CA
..     ...          ...
260  89663     12581203
263  89667      89667FN
263  89667     MD367192
268  89665   AL3Z6B209A
300  89621   166200W035

[1135 rows x 2 columns]

In [24]:
merge_data_13 = pd.merge(new_brand_first_data,new_brand_third_data,on='OE',how='left').fillna('')

merge_data_13

        品牌1           OE    品牌3
0     38106     10069954  89227
1     38103     10239670  89231
2     38103     12456152  89231
3     38103     12561094  89231
4     38103     12580296  89231
...     ...          ...    ...
1490  39467  JR2E6B209AA
1491  39467  JR3E6B209AA
1492  39467   JR3Z6B209A
1493  39518   1662024020
1494  39560   JX6Z6A228B

[1495 rows x 3 columns]

In [25]:
repeat_data_13 = merge_data_13[merge_data_13['品牌3']!='']

repeat_data_13

        品牌1           OE    品牌3
0     38106     10069954  89227
1     38103     10239670  89231
2     38103     12456152  89231
3     38103     12561094  89231
4     38103     12580296  89231
...     ...          ...    ...
1422  39404  11287505566  89641
1423  39404  11287549589  89641
1455  39431     12554027  89253
1456  39431     12580162  89253
1457  39431     12609719  89397

[649 rows x 3 columns]

In [26]:
OE_repeat_data_13 = repeat_data_13.groupby(['品牌1'],as_index=False,sort=False).agg({'OE':';'.join,'品牌3':';'.join})

OE_repeat_data_13

,品牌1,OE,品牌3
0,38106,10069954,89227
1,38103,10239670;12456152;12561094;12580296;89017309,89231;89231;89231;89231;89231
2,38104,12563083;24503851;24507667;24507684,89241;89241;89241;89241
3,38105,10044970;10078911;10114908;10166387;14091898;1...,89203;89203;89203;89203;89203;89203;89203;89203
4,38102,F37Z6B209A;F3TZ6B209C;F47E6B209AA;F4TE6B209AA;...,89230;89230;89230;89393;89230;89230;89230;89230
...,...,...,...
229,39337,68021256AA,89463
230,39282,5184617AC;5184617AD,89632;89632
231,39385,31170R0A005;31170R0A015,89600;89600
232,39404,11287505566;11287549589,89641;89641
233,39431,12554027;12580162;12609719,89253;89253;89397

In [27]:
OE_repeat_data_13['OE'] = OE_repeat_data_13['OE'].str.split(';').apply(lambda x: sorted(list(set(x)), key=x.index))
OE_repeat_data_13['品牌3'] = OE_repeat_data_13['品牌3'].str.split(';').apply(lambda x: sorted(list((set(x))), key=x.index))
OE_repeat_data_13

       品牌1                                                 OE             品牌3
0    38106                                         [10069954]         [89227]
1    38103  [10239670, 12456152, 12561094, 12580296, 89017...         [89231]
2    38104           [12563083, 24503851, 24507667, 24507684]         [89241]
3    38105  [10044970, 10078911, 10114908, 10166387, 14091...         [89203]
4    38102  [F37Z6B209A, F3TZ6B209C, F47E6B209AA, F4TE6B20...  [89230, 89393]
..     ...                                                ...             ...
229  39337                                       [68021256AA]         [89463]
230  39282                             [5184617AC, 5184617AD]         [89632]
231  39385                         [31170R0A005, 31170R0A015]         [89600]
232  39404                         [11287505566, 11287549589]         [89641]
233  39431                     [12554027, 12580162, 12609719]  [89253, 89397]

[234 rows x 3 columns]

In [29]:
OE_repeat_data_13.rename(columns={'OE':'品牌3重复OE','品牌3':'品牌3'},inplace=True)

OE_repeat_data_13

       品牌1                                            品牌3重复OE             品牌3
0    38106                                         [10069954]         [89227]
1    38103  [10239670, 12456152, 12561094, 12580296, 89017...         [89231]
2    38104           [12563083, 24503851, 24507667, 24507684]         [89241]
3    38105  [10044970, 10078911, 10114908, 10166387, 14091...         [89203]
4    38102  [F37Z6B209A, F3TZ6B209C, F47E6B209AA, F4TE6B20...  [89230, 89393]
..     ...                                                ...             ...
229  39337                                       [68021256AA]         [89463]
230  39282                             [5184617AC, 5184617AD]         [89632]
231  39385                         [31170R0A005, 31170R0A015]         [89600]
232  39404                         [11287505566, 11287549589]         [89641]
233  39431                     [12554027, 12580162, 12609719]  [89253, 89397]

[234 rows x 3 columns]

In [30]:
OE_repeat_data_13['品牌3重复OE'] = OE_repeat_data_13['品牌3重复OE'].apply(lambda x: ';'.join(x))
OE_repeat_data_13['品牌3'] = OE_repeat_data_13['品牌3'].apply(lambda x: ';'.join(x))
OE_repeat_data_13

       品牌1                                            品牌3重复OE          品牌3
0    38106                                           10069954        89227
1    38103       10239670;12456152;12561094;12580296;89017309        89231
2    38104                12563083;24503851;24507667;24507684        89241
3    38105  10044970;10078911;10114908;10166387;14091898;1...        89203
4    38102  F37Z6B209A;F3TZ6B209C;F47E6B209AA;F4TE6B209AA;...  89230;89393
..     ...                                                ...          ...
229  39337                                         68021256AA        89463
230  39282                                5184617AC;5184617AD        89632
231  39385                            31170R0A005;31170R0A015        89600
232  39404                            11287505566;11287549589        89641
233  39431                         12554027;12580162;12609719  89253;89397

[234 rows x 3 columns]

In [40]:
result_13 = pd.merge(brand_first_data,OE_repeat_data_13,on='品牌1',how='left').fillna('')

result_13

,品牌1,OE,品牌3重复OE,品牌3
0,38106,10069954,10069954,89227
1,38103,10239670;12456152;12561094;12580296;31025168;8...,10239670;12456152;12561094;12580296;89017309,89231
2,38104,12563083;24503851;24507667;24507684,12563083;24503851;24507667;24507684,89241
3,38105,10044970;10078911;10114908;10166387;14091898;1...,10044970;10078911;10114908;10166387;14091898;1...,89203
4,38102,F37Z6B209A;F3TZ6B209C;F47E6B209AA;F4TE6B209AA;...,F37Z6B209A;F3TZ6B209C;F47E6B209AA;F4TE6B209AA;...,89230;89393
...,...,...,...,...
443,39428,68201164AA,,
444,39516,12647765,,
445,39467,2147525;CR3E6B209AB;JR2E6B209AA;JR3E6B209AA;JR...,,
446,39518,1662024020,,
447,39560,JX6Z6A228B,,

In [37]:
def Separate_oe(brand_date):
    
    clean_oe_data = brand_date[brand_date['OE']!='']

    new_brand_oe_data = clean_oe_data[['品牌3','OE']].copy()
    new_brand_oe_data['OE'] = new_brand_oe_data['OE'].str.split(';')
    new_brand_oe_data = new_brand_oe_data.explode('OE')
    
    return new_brand_oe_data

In [38]:
new_brand_third_data = Separate_oe(brand_third_data)
new_brand_third_data