In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('C:/Users/YangTeng/Desktop/Mevotech号码补充车型-20231026.xlsx',
                   header=0,
                   dtype=str).fillna('')

list_part_number = df['Part_Number'].tolist()

print('总数量：' + str(len(list_part_number)))
list_part_number

总数量：1158

['CMS251049',
 'CMS861292',
 'CMS861293',
 'CMS70116',
 'CMS70116',
 'CMS801135',
 'CMS251040',
 'CMS251039',
 'CMK80721',
 'CMK80720',
 'CMS761168',
 'CMS761169',
 'CMS701131',
 'CMS101226',
 'CMS101227',
 'CMS861114',
 'CMK80400',
 'CMK80399',
 'CMS30145',
 'CMS30146',
 'CMS861082',
 'CMS861083',
 'CMS70160',
 'CMS70161',
 'CMS101282',
 'CMS101283',
 'CMS101008',
 'CMS101347',
 'CMS101004',
 'CMS101005',
 'CMS501266',
 'CMS501267',
 'CMS501245',
 'CMS501244',
 'CMS501163',
 'CMS501181',
 'CMS401114',
 'CMS401115',
 'MK9623',
 'MK8471',
 'MK9025',
 'MK9083',
 'MK9081',
 'MK6696',
 'MS10558',
 'MS70506',
 'MK9922',
 'MK6175T',
 'MK6511',
 'MK9044',
 'MK9916',
 'MS25509',
 'MS40522',
 'MS40517',
 'MS25518',
 'MK80635',
 'MK9669',
 'MK80612',
 'MS40507',
 'MS10503',
 'MS80503',
 'MS90513',
 'MS90616',
 'MS10532',
 'MS60512',
 'MS25519',
 'MS10533',
 'MK90493',
 'MS50527',
 'MK7455',
 'MS40506',
 'MK9513',
 'MK8435',
 'MK8432T',
 'MS50529',
 'MS50514',
 'MS40529',
 'MS86523',
 'MS25532',
 'MS60511',
 'MS25551',
 'MS30524',
 'MS60503',
 'MK500114',
 'MS40521',
 'MS10487',
 'MS10577',
 'MS10564',
 'MS10525',
 'MS10536',
 'MS10535',
 'MS10524',
 'CMS40181',
 'CMS101420',
 'CMS101421',
 'CMS401220',
 'CMS401221',
 'CMS101281',
 'CMS101280',
 'CMS101088',
 'CMS101089',
 'CMS101182',
 'CMK90497',
 'CMS10168',
 'CMS1016',
 'CMS10160',
 'CMS10161',
 'CMS101093',
 'CMS101181',
 'CMS301006',
 'CMS301007',
 'CMS101431',
 'CMS101432',
 'CMS101352',
 'CMS101353',
 'CMS101230',
 'CMS101231',
 'CMS101400',
 'CMS101399',
 'CMS101278',
 'CMS101279',
 'CMS101091',
 'CMS101092',
 'CMS101287',
 'CMS101368',
 'CMS101286',
 'CMS101369',
 'CMS101180',
 'CMS101337',
 'CMS101338',
 'CMS101217',
 'CMS101503',
 'CMS101504',
 'CMS101441',
 'CMS101442',
 'CMS101179',
 'CMS101300',
 'CMS101301',
 'CMS101299',
 'CMS70164',
 'CMS70165',
 'CMS50192',
 'CMS50193',
 'CMS101298',
 'MS25710',
 'MS25611',
 'CMK6402',
 'MDS1011',
 'MDS918',
 'MDS80444',
 'MS40739',
 'MES3686',
 'MK9348',
 'MK9349',
 'MK9045',
 'MK9525',
 'MK9523',
 'MK9342',
 'MK9047',
 'MK9153',
 'MK9073',
 'MK8478',
 'MK9913',
 'MK9914',
 'MS50506',
 'MK9351',
 'MK9350',
 'MK90692',
 'MK9547',
 'MK9551',
 'MK9387',
 'MK9533',
 'MK9853',
 'MK90362',
 'MK9099',
 'MK9049',
 'MK9453',
 'MK9635',
 'MK9452',
 'MK9079',
 'MK9911',
 'MK9912',
 'MK6035',
 'MK9918',
 'MK9601',
 'MK9739',
 'MS80502',
 'MK9852',
 'MS50505',
 'MK9352',
 'MK90504',
 'MK90505',
 'MK90262',
 'MK90263',
 'MK9024',
 'MK9344',
 'MK9460',
 'MK9026',
 'MS25527',
 'MS50507',
 'MK7450',
 'MS10594',
 'MK90355',
 'MK90357',
 'MK9479',
 'MS50563',
 'MK80992',
 'MK9389',
 'MK9910',
 'MK9657',
 'MK9655',
 'MK90364',
 'MK9663',
 'MK80522',
 'MK80521',
 'MS50510',
 'MK90503',
 'MK80385',
 'MK80384',
 'MS80505',
 'MS86539',
 'MS86549',
 'MS86543',
 'MS86550',
 'MK500143',
 'MK6124',
 'MS86529',
 'MS10545',
 'MS60507',
 'MS10509',
 'MK9923',
 'MK9521',
 'MS90507',
 'MS90508',
 'MS25517',
 'MS50519',
 'MS90530',
 'MS90524',
 'MS90525',
 'MS60525',
 'MS70526',
 'MS70527',
 'MK9296',
 'MS90516',
 'MS90529',
 'MS86516',
 'MS86517',
 'MS60517',
 'MS90527',
 'MS90526',
 'MS90522',
 'MS10563',
 'MS10526',
 'MS10527',
 'MS10547',
 'MS10552',
 'MS70528',
 'MS70525',
 'MS106198',
 'MS106199',
 'MS106221',
 'MS106230',
 'MS106210',
 'MS106211',
 'MS80701',
 'MS80711',
 'MS25714',
 'MS10724',
 'MS86724',
 'MEV431',
 'MS80727',
 'MEV428',
 'MS86705',
 'MS50717',
 'MS90713',
 'MS80723',
 'MEV472',
 'MS76700',
 'MS76722',
 'MS76704',
 'MS30700',
 'MS30710',
 'MEV456',
 'MEV349',
 'MS60715',
 'MS60723',
 'MS86729',
 'MS80712',
 'MS40716',
 'MS80713',
 'MS50723',
 'MS60718',
 'MS30749',
 'MS80708',
 'MS90727',
 'MS50731',
 'MS25716',
 'MS60731',
 'MEV175',
 'MEV129',
 'MS50707',
 'MEV800044',
 'MS25718',
 'MS40719',
 'MS80703',
 'MS25722',
 'MS40701',
 'MS25717',
 'MS76710',
 'MS76711',
 'MS50725',
 'MS40706',
 'MS40727',
 'MS60726',
 'MS86719',
 'MS76708',
 'MS50777',
 'MS90728',
 'MS70614',
 'MS50716',
 'MS50703',
 'MS30747',
 'MS90709',
 'MS86711',
 'MEV80809',
 'MS80721',
 'MS30712',
 'MS30724',
 'MS90715',
 'MS40762',
 'MS50714',
 'MS25612',
 'MS25702',
 'MS10700',
 'MS86715',
 'MS60735',
 'MS60709',
 'MS50710',
 'MS90726',
 'MS90719',
 'MS86740',
 'MS86751',
 'MS30736',
 'MS90720',
 'MS90721',
 'MS50750',
 'MS90710',
 'MS10749',
 'MS10723',
 'MS30705',
 'MS60702',
 'MS90729',
 'MS90703',
 'MS50730',
 'MS86709',
 'MS10707',
 'CMS40745',
 'MS70701',
 'MS60701',
 'MS80739',
 'MS60712',
 'MS50789',
 'MS50776',
 'MS60737',
 'MS76725',
 'MS90746',
 'MS90739',
 'MS86748',
 'MS60739',
 'MS90756',
 'MS80730',
 'MS90706',
 'MS90716',
 'MS76717',
 'MS60719',
 'MS50732',
 'MS80719',
 'MS50747',
 'MS60727',
 'MS50749',
 'MS60734',
 'MS90730',
 'MS90740',
 'MS76720',
 'MS30739',
 'MS10709',
 'MS10717',
 'MS107113',
 'MS10768',
 'MS10779',
 'MS10763',
 'MS10776',
 'MS10797',
 'MS10786',
 'MS10785',
 'MS10790',
 'MS107108',
 'MS10764',
 'MS70717',
 'MS70716',
 'MS30741',
 'MS30711',
 'MS30703',
 'MS30745',
 'MS10789',
 'MS10775',
 'MS10701',
 'MS10787',
 'MS10737',
 'MS10762',
 'MS107100',
 'MS107101',
 'MS107115',
 'MS107107',
 'MS107114',
 'MS40760',
 'MS107102',
 'MS70719',
 'MS10721',
 'MS107110',
 'MS10777',
 'MS10798',
 'MS10758',
 'MS10759',
 'MS107109',
 'MS10714',
 'MS10755',
 'MS10754',
 'MS60710',
 'MS60730',
 'MS60728',
 'MS60729',
 'MS60738',
 'MS30742',
 'MS107122',
 'MS90830',
 'MS76870',
 'MK90369',
 'MK90370',
 'MK80374',
 'MS80847',
 'MK90515',
 'MK9825',
 'MS10824',
 'MK9826',
 'MS30800',
 'MS80818',
 'MS508179',
 'MK8631',
 'MS408119',
 'MK9471',
 'MK8662',
 'MK8625',
 'MK9226',
 'MK8633',
 'MK8635',
 'MS76838',
 'MS76839',
 'MS50816',
 'MK90345',
 'MS508154',
 'MK90356',
 'MS80820',
 'MS80819',
 'MS86809',
 'MK80601',
 'MS30844',
 'MS30899',
 'MK7371',
 'MK80575',
 'MS40815',
 'MK80858',
 'MK80859',
 'MK90684',
 'MS70811',
 'MK80459',
 'MK7433',
 'MS60844',
 'MK90718',
 'MK80565',
 'MK90619',
 'MS86846',
 'MS868113',
 'MS40854',
 'MK90456',
 'MK90457',
 'MS60843',
 'MS60842',
 'MK90667',
 'MS80837',
 'MK80300',
 'MS80845',
 'MS80846',
 'MK80769',
 'MK80768',
 'MK80268',
 'MS40850',
 'MK80510',
 'MK80766',
 'MK80043',
 'MK80041',
 'MK8805',
 'MS408100',
 'MS80841',
 'MS508220',
 'MS25850',
 'MK7430',
 'MK7431',
 'MS76846',
 'MK90129',
 'MS40837',
 'MS25890',
 'MS258127',
 'MS25853',
 'MS25887',
 'MK7470',
 'MK80101',
 'MS40861',
 'MS40862',
 'MS60847',
 'MS60846',
 'MS60894',
 'MS60893',
 'MS50839',
 'MS76862',
 'MS86829',
 'MS50884',
 'MS50885',
 'MS76827',
 'MS40827',
 'MS86818',
 'MK80042',
 'MS508184',
 'MS508185',
 'MS508182',
 'MS508183',
 'MK80084',
 'MS40816',
 'MS90826',
 'MS90825',
 'MS50834',
 'MS50835',
 'MK750067',
 'MK750068',
 'MS40804',
 'MS60898',
 'MS30861',
 'MS30860',
 'MS60868',
 'MS60869',
 'MS108143',
 'MS76871',
 'MS308124',
 'MS308125',
 'MS108150',
 'MS25833',
 'MS70854',
 'MS86886',
 'MS10825',
 'MS10830',
 'MS10826',
 'MS10829',
 'MS108156',
 'MK80058',
 'MS60810',
 'MS30885',
 'MS30886',
 'MS608102',
 'MS868123',
 'MS868122',
 'MS50896',
 'MS80853',
 'MS70843',
 'MS70816',
 'MS70828',
 'MS86876',
 'MS86877',
 'MS80869',
 'MS60831',
 'MS25886',
 'MS76851',
 'MS70821',
 'MS90844',
 'MS90843',
 'MS25854',
 'MS60834',
 'MS40864',
 'MS60837',
 'MS60836',
 'MS108177',
 'MS86896',
 'MK80044',
 'MK80083',
 'MS86893',
 'MS90875',
 'MS90876',
 'MS40858',
 'MS50810',
 'MK90121',
 'MK80972',
 'MK80973',
 'MS70807',
 'MS70808',
 'MK9584',
 'MK80299',
 'MK90102',
 'MS70829',
 'MK80952',
 'MS70830',
 'MK80847',
 'MK80557',
 'MK80260',
 'MK80259',
 'MK80860',
 'MK80865',
 'MK90097',
 'MK80516',
 'MK90127',
 'MK90709',
 'MK9832',
 'MK80500',
 'MK90363',
 'MK90710',
 'MK9225',
 'MK90098',
 'MS10897',
 'MK90249',
 'MK80694',
 'MS70822',
 'MK90248',
 'MK80862',
 'MK80863',
 'MK90110',
 'MK8806',
 'MK9827',
 'MK90118',
 'MK90113',
 'MK80499',
 'MK90385',
 'MK80269',
 'MS40830',
 'MK80849',
 'MS40869',
 'MS25829',
 'MS10833',
 'MK750076',
 'MS80850',
 'MK7370',
 'MS10853',
 'MK7304',
 'MS308118',
 'MS868111',
 'MS40852',
 'MS70823',
 'MS40826',
 'MS70868',
 'CMS30170',
 'MK9232',
 'MS868105',
 'MS258120',
 'MS508204',
 'MS608138',
 'MS76840',
 'MS258128',
 'MS76883',
 'MS76882',
 'MK80502',
 'MS908100',
 'MS258118',
 'MS258119',
 'MS258116',
 'MS258117',
 'MS258121',
 'MS258136',
 'MS258135',
 'MS868127',
 'MK80844',
 'MS70806',
 'MS70845',
 'MS90891',
 'MS90890',
 'MS908107',
 'MS908108',
 'MS90898',
 'MS90882',
 'MS90883',
 'MK3093',
 'MS608169',
 'MS608170',
 'CMS30151',
 'MS10845',
 'MS80863',
 'MS80886',
 'MS80885',
 'MS90869',
 'MS90872',
 'MS90861',
 'MS90862',
 'MS86803',
 'MS60892',
 'MK90365',
 'MK90366',
 'MS30854',
 'MS30855',
 'MK80506',
 'MK80507',
 'MS90823',
 'MS90824',
 'MS308116',
 'MS308138',
 'MS40884',
 'MS608104',
 'MS608105',
 'MS40870',
 'MS10862',
 'MS10863',
 'MS80861',
 'MS608146',
 'MS608147',
 'MS608137',
 'MS608136',
 'MS108220',
 'MS108221',
 'MS108178',
 'MS108214',
 'MS108161',
 'MS108162',
 'MS108232',
 'MS10898',
 'MS108209',
 'MS10899',
 'MS10816',
 'MS70874',
 'MS30845',
 'MS30804',
 'MS95810',
 'MS308137',
 'MS108213',
 'MS108212',
 'MS108218',
 'MS108217',
 'MK80267',
 'MS108258',
 'MS108259',
 'MS108248',
 'MS108249',
 'MS108245',
 'MS108246',
 'MS108226',
 'MS108227',
 'MS108228',
 'MS108229',
 'MK80870',
 'MK80871',
 'MS108115',
 'MS108116',
 'MS108127',
 'MS10852',
 'MS10855',
 'MS108202',
 'MS70877',
 'MS70878',
 'MS108203',
 'MS108121',
 'MS108290',
 'MS108111',
 'MS108112',
 'MS108216',
 'MS108219',
 'MS108179',
 'MS108171',
 'MS108215',
 'MS108262',
 'MS108222',
 'MS108223',
 'MK80252',
 'MS10870',
 'MS108299',
 'MS108300',
 'MK80497',
 'MS108297',
 'MS108243',
 'MS108244',
 'MS70882',
 'MS108234',
 'MS108235',
 'MS108233',
 'MS10812',
 'MS10813',
 'MS108236',
 'MS108237',
 'MS95806',
 'MS95805',
 'MS95803',
 'MS95804',
 'MS108155',
 'MS70820',
 'MS108238',
 'MS108239',
 'MS108274',
 'MS108273',
 'CMS101090',
 'MK80866',
 'MS70891',
 'MS608125',
 'MS608126',
 'MS60872',
 'MS608122',
 'MS608123',
 'MS608141',
 'MS608140',
 'MS608131',
 'MS608132',
 'MS608127',
 'MS608128',
 'MS108122',
 'MS108123',
 'CMS401126',
 'MK7270',
 'MK7350',
 'MK7268',
 'MS504227',
 'MK7266',
 'MK8645',
 'MK90318',
 'MK90254',
 'MK7352',
 'MK6399',
 'MK8690',
 'MK7358',
 'MK5248',
 'MK6455',
 'MK8654',
 'MK9247',
 'MK9258',
 'MK6649',
 'MK7361',
 'MK7466',
 'MK6650',
 'MK80023',
 'MK7360',
 'MK6648',
 'MK5332',
 'MK6641',
 'MK5326',
 'MK6647',
 'MK9375',
 'MS504229',
 'MS308127',
 'MS308131',
 'MS258106',
 'MS258107',
 'MS308130',
 'MS308126',
 'MS30889',
 'MK9986',
 'MS25871',
 'MS508151',
 'MS508141',
 'MK80772',
 'MS508146',
 'MS508142',
 'MS508143',
 'MS50868',
 'MS508147',
 'MS508139',
 'MS50869',
 'MK80774',
 'MK80364',
 'MK80365',
 'MS25304',
 'MS50400',
 'MS25864',
 'MS508174',
 'MS504228',
 'MS508145',
 'MS508144',
 'MK90559',
 'MS258104',
 'MS258105',
 'MS258160',
 'MS404191',
 'MS908113',
 'MS70837',
 'MS76878',
 'MS608171',
 'MS868160',
 'MK90572',
 'MS25862',
 'MK90024',
 'MS25842',
 'MS25843',
 'MS50401',
 'MS30419',
 'MS30428',
 'MK80362',
 'MS80874',
 'MS90868',
 'MS40875',
 'MK90537',
 'MS80412',
 'MS80854',
 'MS108192',
 'MS25302',
 'MS50301',
 'MS108182',
 'MS30422',
 'MS60419',
 'MS108133',
 'MS80872',
 'MS10438',
 'MS80404',
 'MS10439',
 'MS60878',
 'MS30427',
 'MS108194',
 'MS10872',
 'MS80877',
 'MS868100',
 'MS30411',
 'MS30420',
 'MS25896',
 'MK5329',
 'MS308135',
 'MS80456',
 'MES3430',
 'MS50631',
 'MS50612',
 'MES2132RL',
 'MES409LT',
 'MS90611',
 'MES3306',
 'MS30615',
 'MES3602',
 'MES2374',
 'MES2281R',
 'MS25603',
 'MS10662',
 'MS10663',
 'MES3076RL',
 'MS50684',
 'MS50683',
 'MES2322L',
 'MS50602',
 'MS50603',
 'MES3301',
 'MES3300',
 'MES2194R',
 'MES3523',
 'MES3631',
 'MS40627',
 'MES2850RL',
 'MS80605',
 'MS60618',
 'MES2996RL',
 'MES3712',
 'MS30603',
 'MS10660',
 'MES3257',
 'MS60616',
 'MS50647',
 'MS90639',
 'MS90640',
 'MS60605',
 'MS86632',
 'MS80628',
 'MES3351',
 'MS25628',
 'MS50652',
 'MS70646',
 'MS50653',
 'MS70647',
 'MS25614',
 'MS86629',
 'MS86630',
 'MS86641',
 'MS86642',
 'MS76613',
 'MS86618',
 'MS86619',
 'MES800621',
 'MS86612',
 'MS40618',
 'MS50651',
 'MS40616',
 'MS10601',
 'MS10600',
 'MS50624',
 'MS90623',
 'MS90624',
 'MES2500RL',
 'MS10682',
 'MS10669',
 'MS60611',
 'MS86637',
 'MS86638',
 'MS60625',
 'MS60626',
 'MS86616',
 'MS86617',
 ...]

In [3]:
df = pd.DataFrame()

df

Empty DataFrame
Columns: []
Index: []

In [4]:
import requests

In [5]:
i = 0

part_number = list_part_number[i]

resp = requests.get('https://www.mevotech.com/part/' + part_number).text

resp

'\n<!DOCTYPE html>\n<html lang="en-US">\n\t<head>\n        <meta charset="UTF-8">\n        <meta http-equiv="X-UA-Compatible" content="IE=edge">\n        <meta name="viewport" content="width=device-width, initial-scale=1.0">\n        <meta name="format-detection" content="telephone=no">\n        \n        <meta name=\'robots\' content=\'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1\' />\n<link rel="alternate" href="https://www.mevotech.com/part/" hreflang="en" />\n<link rel="alternate" href="https://www.mevotech.com/fr/partie/" hreflang="fr" />\n<link rel="alternate" href="https://www.mevotech.com/es/parte/" hreflang="es" />\n\n\t<!-- This site is optimized with the Yoast SEO plugin v20.5 - https://yoast.com/wordpress/plugins/seo/ -->\n\t<title>CMS251049 - Lateral Link - Mevotech</title>\n\t<link rel="canonical" href="https://www.mevotech.com/part/" />\n\t<meta property="og:locale" content="en_US" />\n\t<meta property="og:locale:alternate" content="fr_CA" />\n\t<meta property="og:locale:alternate" content="es_ES" />\n\t<meta property="og:type" content="article" />\n\t<meta property="og:title" content="Part - Mevotech" />\n\t<meta property="og:description" content="This is the page content" />\n\t<meta property="og:url" content="https://www.mevotech.com/part/" />\n\t<meta property="og:site_name" content="Mevotech" />\n\t<meta property="article:modified_time" content="2021-11-03T14:55:42+00:00" />\n\t<meta name="twitter:card" content="summary_large_image" />\n\t<script type="application/ld+json" class="yoast-schema-graph">{"@context":"https://schema.org","@graph":[{"@type":"WebPage","@id":"https://www.mevotech.com/part/","url":"https://www.mevotech.com/part/","name":"Part - Mevotech","isPartOf":{"@id":"https://www.mevotech.com/#website"},"datePublished":"2020-05-25T20:26:12+00:00","dateModified":"2021-11-03T14:55:42+00:00","breadcrumb":{"@id":"https://www.mevotech.com/part/#breadcrumb"},"inLanguage":"en-US","potentialAction":[{"@type":"ReadAction","target":["https://www.mevotech.com/part/"]}]},{"@type":"BreadcrumbList","@id":"https://www.mevotech.com/part/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://www.mevotech.com/"},{"@type":"ListItem","position":2,"name":"Part"}]},{"@type":"WebSite","@id":"https://www.mevotech.com/#website","url":"https://www.mevotech.com/","name":"Mevotech","description":"Engineered in the lab, built for the road.","publisher":{"@id":"https://www.mevotech.com/#organization"},"potentialAction":[{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https://www.mevotech.com/?s={search_term_string}"},"query-input":"required name=search_term_string"}],"inLanguage":"en-US"},{"@type":"Organization","@id":"https://www.mevotech.com/#organization","name":"Mevotech","url":"https://www.mevotech.com/","logo":{"@type":"ImageObject","inLanguage":"en-US","@id":"https://www.mevotech.com/#/schema/logo/image/","url":"https://www.mevotech.com/wp-content/uploads/2021/10/Logo.svg","contentUrl":"https://www.mevotech.com/wp-content/uploads/2021/10/Logo.svg","caption":"Mevotech"},"image":{"@id":"https://www.mevotech.com/#/schema/logo/image/"}}]}</script>\n\t<!-- / Yoast SEO plugin. -->\n\n\n<link rel=\'dns-prefetch\' href=\'//www.googletagmanager.com\' />\n<link rel=\'dns-prefetch\' href=\'//fonts.googleapis.com\' />\n<style type="text/css">\nimg.wp-smiley,\nimg.emoji {\n\tdisplay: inline !important;\n\tborder: none !important;\n\tbox-shadow: none !important;\n\theight: 1em !important;\n\twidth: 1em !important;\n\tmargin: 0 0.07em !important;\n\tvertical-align: -0.1em !important;\n\tbackground: none !important;\n\tpadding: 0 !important;\n}\n</style>\n\t<link rel=\'stylesheet\' id=\'vc_extensions_admin_individual_hotspot-css\'  href=\'https://www.mevotech.com/wp-content/plugins/vc-extensions-hotspot/css/admin_icon.css?ver=6.0.6\' type=\'text/css\' media=\'all\' />\n<link rel=\'stylesheet\' id=\'wp-block-library-css\'  href=\'https://www.mevotech.com/wp-includes/css/dist/block-library/style.min.css?ver=6.0.6\' type=\'text/css\' media=\'all\' />\n<style id=\'global-styles-inline-css\' type=\'text/css\'>\nbody{--wp--preset--color--black: #000000;--wp--preset--color--cyan-bluish-gray: #abb8c3;--wp--preset--color--white: #ffffff;--wp--preset--color--pale-pink: #f78da7;--wp--preset--color--vivid-red: #cf2e2e;--wp--preset--color--luminous-vivid-orange: #ff6900;--wp--preset--color--luminous-vivid-amber: #fcb900;--wp--preset--color--light-green-cyan: #7bdcb5;--wp--preset--color--vivid-green-cyan: #00d084;--wp--preset--color--pale-cyan-blue: #8ed1fc;--wp--preset--color--vivid-cyan-blue: #0693e3;--wp--preset--color--vivid-purple: #9b51e0;--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple: linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%);--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan: linear-gradient(135deg,rgb(122,220,180) 0%,rgb(0,208,130) 100%);--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange: linear-gradient(135deg,rgba(252,185,0,1) 0%,rgba(255,105,0,1) 100%);--wp--preset--gradient--luminous-vivid-orange-to-vivid-red: linear-gradient(135deg,rgba(255,105,0,1) 0%,rgb(207,46,46) 100%);--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray: linear-gradient(135deg,rgb(238,238,238) 0%,rgb(169,184,195) 100%);--wp--preset--gradient--cool-to-warm-spectrum: linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%);--wp--preset--gradient--blush-light-purple: linear-gradient(135deg,rgb(255,206,236) 0%,rgb(152,150,240) 100%);--wp--preset--gradient--blush-bordeaux: linear-gradient(135deg,rgb(254,205,165) 0%,rgb(254,45,45) 50%,rgb(107,0,62) 100%);--wp--preset--gradient--luminous-dusk: linear-gradient(135deg,rgb(255,203,112) 0%,rgb(199,81,192) 50%,rgb(65,88,208) 100%);--wp--preset--gradient--pale-ocean: linear-gradient(135deg,rgb(255,245,203) 0%,rgb(182,227,212) 50%,rgb(51,167,181) 100%);--wp--preset--gradient--electric-grass: linear-gradient(135deg,rgb(202,248,128) 0%,rgb(113,206,126) 100%);--wp--preset--gradient--midnight: linear-gradient(135deg,rgb(2,3,129) 0%,rgb(40,116,252) 100%);--wp--preset--duotone--dark-grayscale: url(\'#wp-duotone-dark-grayscale\');--wp--preset--duotone--grayscale: url(\'#wp-duotone-grayscale\');--wp--preset--duotone--purple-yellow: url(\'#wp-duotone-purple-yellow\');--wp--preset--duotone--blue-red: url(\'#wp-duotone-blue-red\');--wp--preset--duotone--midnight: url(\'#wp-duotone-midnight\');--wp--preset--duotone--magenta-yellow: url(\'#wp-duotone-magenta-yellow\');--wp--preset--duotone--purple-green: url(\'#wp-duotone-purple-green\');--wp--preset--duotone--blue-orange: url(\'#wp-duotone-blue-orange\');--wp--preset--font-size--small: 13px;--wp--preset--font-size--medium: 20px;--wp--preset--font-size--large: 36px;--wp--preset--font-size--x-large: 42px;}.has-black-color{color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-color{color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-color{color: var(--wp--preset--color--white) !important;}.has-pale-pink-color{color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-color{color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-color{color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-color{color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-color{color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-color{color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-color{color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-color{color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-color{color: var(--wp--preset--color--vivid-purple) !important;}.has-black-background-color{background-color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-background-color{background-color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-background-color{background-color: var(--wp--preset--color--white) !important;}.has-pale-pink-background-color{background-color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-background-color{background-color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-background-color{background-color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-background-color{background-color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-background-color{background-color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-background-color{background-color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-background-color{background-color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-background-color{background-color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-background-color{background-color: var(--wp--preset--color--vivid-purple) !important;}.has-black-border-color{border-color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-border-color{border-color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-border-color{border-color: var(--wp--preset--color--white) !important;}.has-pale-pink-border-color{border-color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-border-color{border-color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-border-color{border-color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-border-color{border-color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-border-color{border-color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-border-color{border-color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-border-color{border-color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-border-color{border-color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-border-color{border-color: var(--wp--preset--color--vivid-purple) !important;}.has-vivid-cyan-blue-to-vivid-purple-gradient-background{background: var(--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple) !important;}.has-light-green-cyan-to-vivid-green-cyan-gradient-background{background: var(--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan) !important;}.has-luminous-vivid-amber-to-luminous-vivid-orange-gradient-background{background: var(--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange) !important;}.has-luminous-vivid-orange-to-vivid-red-gradient-background{background: var(--wp--preset--gradient--luminous-vivid-orange-to-vivid-red) !important;}.has-very-light-gray-to-cyan-bluish-gray-gradient-background{background: var(--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray) !important;}.has-cool-to-warm-spectrum-gradient-background{background: var(--wp--preset--gradient--cool-to-warm-spectrum) !important;}.has-blush-light-purple-gradient-background{background: var(--wp--preset--gradient--blush-light-purple) !important;}.has-blush-bordeaux-gradient-background{background: var(--wp--preset--gradient--blush-bordeaux) !important;}.has-luminous-dusk-gradient-background{background: var(--wp--preset--gradient--luminous-dusk) !important;}.has-pale-ocean-gradient-background{background: var(--wp--preset--gradient--pale-ocean) !important;}.has-electric-grass-gradient-background{background: var(--wp--preset--gradient--electric-grass) !important;}.has-midnight-gradient-background{background: var(--wp--preset--gradient--midnight) !important;}.has-small-font-size{font-size: var(--wp--preset--font-size--small) !important;}.has-medium-font-size{font-size: var(--wp--preset--font-size--medium) !important;}.has-large-font-size{font-size: var(--wp--preset--font-size--large) !important;}.has-x-large-font-size{font-size: var(--wp--preset--font-size--x-large) !important;}\n</style>\n<link rel=\'stylesheet\' id=\'atwm-open-sans-css\'  href=\'https://fonts.googleapis.com/css2?family=Roboto%3Aital%2Cwght%400%2C400%3B0%2C700%3B0%2C900%3B1%2C400%3B1%2C700%3B1%2C900&#038;display=swap&#038;ver=1.0.61\' type=\'text/css\' media=\'all\' />\n<link rel=\'stylesheet\' id=\'atwm-bootstrap-css-css\'  href=\'https://www.mevotech.com/wp-content/themes/mevotech/css/bootstrap5/bootstrap.min.css?ver=1.0.61\' type=\'text/css\' media=\'all\' />\n<link rel=\'stylesheet\' id=\'atwm-swiper-css-css\'  href=\'https://www.mevotech.com/wp-content/themes/mevotech/css/swiper/swiper.css?ver=1.0.61\' type=\'text/css\' media=\'all\' />\n<link rel=\'stylesheet\' id=\'atwm-theme-style-css\'  href=\'https://www.mevotech.com/wp-content/themes/mevotech/style.css?ver=1.0.61\' type=\'text/css\' media=\'all\' />\n<link rel=\'stylesheet\' id=\'atwm-theme-style-header-css\'  href=\'https://www.mevotech.com/wp-content/themes/mevotech/css/header.css?ver=1.0.61\' type=\'text/css\' media=\'all\' />\n<link rel=\'stylesheet\' id=\'atwm-theme-style-main-css\'  href=\'https://www.mevotech.com/wp-content/themes/mevotech/css/main.css?ver=1.0.61\' type=\'text/css\' media=\'all\' />\n<link rel=\'stylesheet\' id=\'atwm-theme-style-footer-css\'  href=\'https://www.mevotech.com/wp-content/themes/mevotech/css/footer.css?ver=1.0.61\' type=\'text/css\' media=\'all\' />\n<link rel=\'stylesheet\' id=\'atwm-theme-style-media-css\'  href=\'https://www.mevotech.com/wp-content/themes/mevotech/css/media.css?ver=1.0.61\' type=\'text/css\' media=\'all\' />\n<link rel=\'stylesheet\' id=\'js_composer_custom_css-css\'  href=\'//www.mevotech.com/wp-content/uploads/js_composer/custom.css?ver=6.7.0\' type=\'text/css\' media=\'all\' />\n<link rel=\'stylesheet\' id=\'bsf-Defaults-css\'  href=\'https://www.mevotech.com/wp-content/uploads/smile_fonts/Defaults/Defaults.css?ver=3.19.10\' type=\'text/css\' media=\'all\' />\n<!--n2css--><script type=\'text/javascript\' src=\'https://www.mevotech.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0\' id=\'jquery-core-js\'></script>\n<script type=\'text/javascript\' src=\'https://www.mevotech.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=3.3.2\' id=\'jquery-migrate-js\'></script>\n\n<!-- Google Analytics snippet added by Site Kit -->\n<script type=\'text/javascript\' src=\'https://www.googletagmanager.com/gtag/js?id=G-HFRQXE4S60\' id=\'google_gtagjs-js\' async></script>\n<script type=\'text/javascript\' id=\'google_gtagjs-js-after\'>\nwindow.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}\ngtag(\'set\', \'linker\', {"domains":["www.mevotech.com"]} );\ngtag("js", new Date());\ngtag("set", "developer_id.dZTNiMT", true);\ngtag("config", "G-HFRQXE4S60");\n</script>\n\n<!-- End Google Analytics snippet added by Site Kit -->\n<link rel="https://api.w.org/" href="https://www.mevotech.com/wp-json/" /><link rel="alternate" type="application/json" href="https://www.mevotech.com/wp-json/wp/v2/pages/452" /><link rel="EditURI" type="application/rsd+xml" title="RSD" href="https://www.mevotech.com/xmlrpc.php?rsd" />\n<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="https://www.mevotech.com/wp-includes/wlwmanifest.xml" /> \n<meta name="generator" content="WordPress 6.0.6" />\n<link rel=\'shortlink\' href=\'https://www.mevotech.com/?p=452\' />\n<link rel="alternate" type="application/json+oembed" href="https://www.mevotech.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.mevotech.com%2Fpart%2F" />\n<link rel="alternate" type="text/xml+oembed" href="https://www.mevotech.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.mevotech.com%2Fpart%2F&#038;format=xml" />\n<meta name="generator" content="Site Kit by Google 1.115.0" /><meta name="google" content="aHR0cHM6Ly93d3cubWV2b3RlY2guY29tL3dwLWxvZ2luLnBocA=="  /><!-- Global site tag (gtag.js) - Google Analytics -->\n<script async src="https://www.googletagmanager.com/gtag/js?id=UA-159120141-1"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag(\'js\', new Date());\n\n  gtag(\'config\', \'UA-159120141-1\');\n</script>\n\n<!-- Google Tag Manager -->\n<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':\nnew Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],\nj=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\n\'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);\n})(window,document,\'script\',\'dataLayer\',\'GTM-5KRVX32\');</script>\n<!-- End Google Tag Manager -->\n\n<!-- Google tag (gtag.js) -->\n<script async src="https://www.googletagmanager.com/gtag/js?id=AW-10990581449"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag(\'js\', new Date());\n\n  gtag(\'config\', \'AW-10990581449\');\n</script>\n\n<!-- Start of HubSpot Embed Code -->\n<script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/7086927.js"></script>\n<!-- End of HubSpot Embed Code --><meta name="generator" content="Powered by WPBakery Page Builder - drag and drop page builder for WordPress."/>\n\n<!-- Google Tag Manager snippet added by Site Kit -->\n<script type="text/javascript">\n\t\t\t( function( w, d, s, l, i ) {\n\t\t\t\tw[l] = w[l] || [];\n\t\t\t\tw[l].push( {\'gtm.start\': new Date().getTime(), event: \'gtm.js\'} );\n\t\t\t\tvar f = d.getElementsByTagName( s )[0],\n\t\t\t\t\tj = d.createElement( s ), dl = l != \'dataLayer\' ? \'&l=\' + l : \'\';\n\t\t\t\tj.async = true;\n\t\t\t\tj.src = \'https://www.googletagmanager.com/gtm.js?id=\' + i + dl;\n\t\t\t\tf.parentNode.insertBefore( j, f );\n\t\t\t} )( window, document, \'script\', \'dataLayer\', \'GTM-5KRVX32\' );\n\t\t\t\n</script>\n\n<!-- End Google Tag Manager snippet added by Site Kit -->\n<link rel="icon" href="https://www.mevotech.com/wp-content/uploads/2020/04/cropped-favicon-32x32.png" sizes="32x32" />\n<link rel="icon" href="https://www.mevotech.com/wp-content/uploads/2020/04/cropped-favicon-192x192.png" sizes="192x192" />\n<link rel="apple-touch-icon" href="https://www.mevotech.com/wp-content/uploads/2020/04/cropped-favicon-180x180.png" />\n<meta name="msapplication-TileImage" content="https://www.mevotech.com/wp-content/uploads/2020/04/cropped-favicon-270x270.png" />\n\t\t<style type="text/css" id="wp-custom-css">\n\t\t\t.atwater-home-page-slider div.wpb_column:first-child > .vc_column-inner > .wpb_wrapper {\n\tpadding: 3rem;\n\tpadding-left: 5 rem;\n}\n.atwater-home-page-slider .vc_col-sm-6:nth-child(2) .vc_column-inner {\n\tpadding-right: 0;\n\tpadding-left: 0;\n}\n.atwater-home-page-slider .vc_col-sm-6:nth-child(2) > .vc_column-inner > .wpb_wrapper {\n\theight: 100%;\n}\n.atwater-home-page-slider .vc_col-sm-6:nth-child(2) .wpb_single_image,\n.atwater-home-page-slider .vc_col-sm-6:nth-child(2) .vc_figure {\n\theight: 100%;\n}\n.atwt-text-blue {\n\tcolor: #2573be;\n}\n.atwater-to-image-slider::before {\n\t  content: "";\n    display: block !important;\n    width: 300px;\n    height: 300px;\n    background-image: url(https://www.mevotech.com/wp-content/themes/mevotech/images/logo-icon.svg);\n    background-repeat: no-repeat;\n    background-size: 100% 100%;\n    background-position: center;\n    position: absolute;\n    left: -50px;\n    top: -55px;\n    z-index: -1;\n}\n\n.atwater-home-page-slider {\n\tbox-shadow: -5px 0px 15px rgb(0 0 0 / 15%);\n\tborder-top-left-radius: 80px;\n\tborder-bottom-right-radius: 80px;\n\tbackground-color: #fff;\n\tmargin: 25px;\n}\n.slick-initialized .slick-slide.atwater-home-page-slider  {\n\tdisplay: flex;\n}\n.atwater-home-page-slider .atwm-video {\n\tmargin-bottom: 0;\n\t\n}\n.atwater-home-page-slider .vc_single_imag

In [6]:
from bs4 import BeautifulSoup

In [7]:
soup = BeautifulSoup(resp, 'lxml')

with open('./vehicle.html', 'w', encoding='UTF-8') as file:
    file.write(str(soup))

print(soup.prettify())

<!DOCTYPE html>
<html lang="en-US">
 <head>
  <meta charset="utf-8"/>
  <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <meta content="telephone=no" name="format-detection"/>
  <meta content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" name="robots"/>
  <link href="https://www.mevotech.com/part/" hreflang="en" rel="alternate"/>
  <link href="https://www.mevotech.com/fr/partie/" hreflang="fr" rel="alternate"/>
  <link href="https://www.mevotech.com/es/parte/" hreflang="es" rel="alternate"/>
  <!-- This site is optimized with the Yoast SEO plugin v20.5 - https://yoast.com/wordpress/plugins/seo/ -->
  <title>
   CMS251049 - Lateral Link - Mevotech
  </title>
  <link href="https://www.mevotech.com/part/" rel="canonical"/>
  <meta content="en_US" property="og:locale"/>
  <meta content="fr_CA" property="og:locale:alternate"/>
  <meta content="es_ES" property="og:locale:alternate"/>
  <meta content="article" property="og:type"/>
  <meta content="Part - Mevotech" property="og:title"/>
  <meta content="This is the page content" property="og:description"/>
  <meta content="https://www.mevotech.com/part/" property="og:url"/>
  <meta content="Mevotech" property="og:site_name"/>
  <meta content="2021-11-03T14:55:42+00:00" property="article:modified_time"/>
  <meta content="summary_large_image" name="twitter:card"/>
  <script class="yoast-schema-graph" type="application/ld+json">
   {"@context":"https://schema.org","@graph":[{"@type":"WebPage","@id":"https://www.mevotech.com/part/","url":"https://www.mevotech.com/part/","name":"Part - Mevotech","isPartOf":{"@id":"https://www.mevotech.com/#website"},"datePublished":"2020-05-25T20:26:12+00:00","dateModified":"2021-11-03T14:55:42+00:00","breadcrumb":{"@id":"https://www.mevotech.com/part/#breadcrumb"},"inLanguage":"en-US","potentialAction":[{"@type":"ReadAction","target":["https://www.mevotech.com/part/"]}]},{"@type":"BreadcrumbList","@id":"https://www.mevotech.com/part/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://www.mevotech.com/"},{"@type":"ListItem","position":2,"name":"Part"}]},{"@type":"WebSite","@id":"https://www.mevotech.com/#website","url":"https://www.mevotech.com/","name":"Mevotech","description":"Engineered in the lab, built for the road.","publisher":{"@id":"https://www.mevotech.com/#organization"},"potentialAction":[{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https://www.mevotech.com/?s={search_term_string}"},"query-input":"required name=search_term_string"}],"inLanguage":"en-US"},{"@type":"Organization","@id":"https://www.mevotech.com/#organization","name":"Mevotech","url":"https://www.mevotech.com/","logo":{"@type":"ImageObject","inLanguage":"en-US","@id":"https://www.mevotech.com/#/schema/logo/image/","url":"https://www.mevotech.com/wp-content/uploads/2021/10/Logo.svg","contentUrl":"https://www.mevotech.com/wp-content/uploads/2021/10/Logo.svg","caption":"Mevotech"},"image":{"@id":"https://www.mevotech.com/#/schema/logo/image/"}}]}
  </script>
  <!-- / Yoast SEO plugin. -->
  <link href="//www.googletagmanager.com" rel="dns-prefetch"/>
  <link href="//fonts.googleapis.com" rel="dns-prefetch"/>
  <style type="text/css">
   img.wp-smiley,
img.emoji {
	display: inline !important;
	border: none !important;
	box-shadow: none !important;
	height: 1em !important;
	width: 1em !important;
	margin: 0 0.07em !important;
	vertical-align: -0.1em !important;
	background: none !important;
	padding: 0 !important;
}
  </style>
  <link href="https://www.mevotech.com/wp-content/plugins/vc-extensions-hotspot/css/admin_icon.css?ver=6.0.6" id="vc_extensions_admin_individual_hotspot-css" media="all" rel="stylesheet" type="text/css"/>
  <link href="https://www.mevotech.com/wp-includes/css/dist/block-library/style.min.css?ver=6.0.6" id="wp-block-library-css" media="all" rel="stylesheet" type="text/css"/>
  <style id="global-styles-inline-css" type="text/css">
   body{--wp--preset--color--black: #000000;--wp--preset--color--cyan-bluish-gray: #abb8c3;--wp--preset--color--white: #ffffff;--wp--preset--color--pale-pink: #f78da7;--wp--preset--color--vivid-red: #cf2e2e;--wp--preset--color--luminous-vivid-orange: #ff6900;--wp--preset--color--luminous-vivid-amber: #fcb900;--wp--preset--color--light-green-cyan: #7bdcb5;--wp--preset--color--vivid-green-cyan: #00d084;--wp--preset--color--pale-cyan-blue: #8ed1fc;--wp--preset--color--vivid-cyan-blue: #0693e3;--wp--preset--color--vivid-purple: #9b51e0;--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple: linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%);--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan: linear-gradient(135deg,rgb(122,220,180) 0%,rgb(0,208,130) 100%);--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange: linear-gradient(135deg,rgba(252,185,0,1) 0%,rgba(255,105,0,1) 100%);--wp--preset--gradient--luminous-vivid-orange-to-vivid-red: linear-gradient(135deg,rgba(255,105,0,1) 0%,rgb(207,46,46) 100%);--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray: linear-gradient(135deg,rgb(238,238,238) 0%,rgb(169,184,195) 100%);--wp--preset--gradient--cool-to-warm-spectrum: linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%);--wp--preset--gradient--blush-light-purple: linear-gradient(135deg,rgb(255,206,236) 0%,rgb(152,150,240) 100%);--wp--preset--gradient--blush-bordeaux: linear-gradient(135deg,rgb(254,205,165) 0%,rgb(254,45,45) 50%,rgb(107,0,62) 100%);--wp--preset--gradient--luminous-dusk: linear-gradient(135deg,rgb(255,203,112) 0%,rgb(199,81,192) 50%,rgb(65,88,208) 100%);--wp--preset--gradient--pale-ocean: linear-gradient(135deg,rgb(255,245,203) 0%,rgb(182,227,212) 50%,rgb(51,167,181) 100%);--wp--preset--gradient--electric-grass: linear-gradient(135deg,rgb(202,248,128) 0%,rgb(113,206,126) 100%);--wp--preset--gradient--midnight: linear-gradient(135deg,rgb(2,3,129) 0%,rgb(40,116,252) 100%);--wp--preset--duotone--dark-grayscale: url('#wp-duotone-dark-grayscale');--wp--preset--duotone--grayscale: url('#wp-duotone-grayscale');--wp--preset--duotone--purple-yellow: url('#wp-duotone-purple-yellow');--wp--preset--duotone--blue-red: url('#wp-duotone-blue-red');--wp--preset--duotone--midnight: url('#wp-duotone-midnight');--wp--preset--duotone--magenta-yellow: url('#wp-duotone-magenta-yellow');--wp--preset--duotone--purple-green: url('#wp-duotone-purple-green');--wp--preset--duotone--blue-orange: url('#wp-duotone-blue-orange');--wp--preset--font-size--small: 13px;--wp--preset--font-size--medium: 20px;--wp--preset--font-size--large: 36px;--wp--preset--font-size--x-large: 42px;}.has-black-color{color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-color{color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-color{color: var(--wp--preset--color--white) !important;}.has-pale-pink-color{color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-color{color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-color{color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-color{color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-color{color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-color{color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-color{color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-color{color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-color{color: var(--wp--preset--color--vivid-purple) !important;}.has-black-background-color{background-color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-background-color{background-color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-background-color{background-color: var(--wp--preset--color--white) !important;}.has-pale-pink-background-color{background-color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-background-color{background-color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-background-color{background-color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-background-color{background-color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-background-color{background-color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-background-color{background-color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-background-color{background-color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-background-color{background-color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-background-color{background-color: var(--wp--preset--color--vivid-purple) !important;}.has-black-border-color{border-color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-border-color{border-color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-border-color{border-color: var(--wp--preset--color--white) !important;}.has-pale-pink-border-color{border-color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-border-color{border-color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-border-color{border-color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-border-color{border-color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-border-color{border-color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-border-color{border-color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-border-color{border-color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-border-color{border-color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-border-color{border-color: var(--wp--preset--color--vivid-purple) !important;}.has-vivid-cyan-blue-to-vivid-purple-gradient-background{background: var(--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple) !important;}.has-light-green-cyan-to-vivid-green-cyan-gradient-background{background: var(--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan) !important;}.has-luminous-vivid-amber-to-luminous-vivid-orange-gradient-background{background: var(--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange) !important;}.has-luminous-vivid-orange-to-vivid-red-gradient-background{background: var(--wp--preset--gradient--luminous-vivid-orange-to-vivid-red) !important;}.has-very-light-gray-to-cyan-bluish-gray-gradient-background{background: var(--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray) !important;}.has-cool-to-warm-spectrum-gradient-background{background: var(--wp--preset--gradient--cool-to-warm-spectrum) !important;}.has-blush-light-purple-gradient-background{background: var(--wp--preset--gradient--blush-light-purple) !important;}.has-blush-bordeaux-gradient-background{background: var(--wp--preset--gradient--blush-bordeaux) !important;}.has-luminous-dusk-gradient-background{background: var(--wp--preset--gradient--luminous-dusk) !important;}.has-pale-ocean-gradient-background{background: var(--wp--preset--gradient--pale-ocean) !important;}.has-electric-grass-gradient-background{background: var(--wp--preset--gradient--electric-grass) !important;}.has-midnight-gradient-background{background: var(--wp--preset--gradient--midnight) !important;}.has-small-font-size{font-size: var(--wp--preset--font-size--small) !important;}.has-medium-font-size{font-size: var(--wp--preset--font-size--medium) !important;}.has-large-font-size{font-size: var(--wp--preset--font-size--large) !important;}.has-x-large-font-size{font-size: var(--wp--preset--font-size--x-large) !important;}
  </style>
  <link href="https://fonts.googleapis.com/css2?family=Roboto%3Aital%2Cwght%400%2C400%3B0%2C700%3B0%2C900%3B1%2C400%3B1%2C700%3B1%2C900&amp;display=swap&amp;ver=1.0.61" id="atwm-open-sans-css" media="all" rel="stylesheet" type="text/css"/>
  <link href="https://www.mevotech.com/wp-content/themes/mevotech/css/bootstrap5/bootstrap.min.css?ver=1.0.61" id="atwm-bootstrap-css-css" media="all" rel="stylesheet" type="text/css"/>
  <link href="https://www.mevotech.com/wp-content/themes/mevotech/css/swiper/swiper.css?ver=1.0.61" id="atwm-swiper-css-css" media="all" rel="stylesheet" type="text/css"/>
  <link href="https://www.mevotech.com/wp-content/themes/mevotech/style.css?ver=1.0.61" id="atwm-theme-style-css" media="all" rel="stylesheet" type="text/css"/>
  <link href="https://www.mevotech.com/wp-content/themes/mevotech/css/header.css?ver=1.0.61" id="atwm-theme-style-header-css" media="all" rel="stylesheet" type="text/css"/>
  <link href="https://www.mevotech.com/wp-content/themes/mevotech/css/main.css?ver=1.0.61" id="atwm-theme-style-main-css" media="all" rel="stylesheet" type="text/css"/>
  <link href="https://www.mevotech.com/wp-content/themes/mevotech/css/footer.css?ver=1.0.61" id="atwm-theme-style-footer-css" media="all" rel="stylesheet" type="text/css"/>
  <link href="https://www.mevotech.com/wp-content/themes/mevotech/css/media.css?ver=1.0.61" id="atwm-theme-style-media-css" media="all" rel="stylesheet" type="text/css"/>
  <link href="//www.mevotech.com/wp-content/uploads/js_composer/custom.css?ver=6.7.0" id="js_composer_custom_css-css" media="all" rel="stylesheet" type="text/css"/>
  <link href="https://www.mevotech.com/wp-content/uploads/smile_fonts/Defaults/Defaults.css?ver=3.19.10" id="bsf-Defaults-css" media="all" rel="stylesheet" type="text/css"/>
  <!--n2css-->
  <script id="jquery-core-js" src="https://www.mevotech.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0" type="text/javascript">
  </script>
  <script id="jquery-migrate-js" src="https://www.mevotech.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=3.3.2" type="text/javascript">
  </script>
  <!-- Google Analytics snippet added by Site Kit -->
  <script async="" id="google_gtagjs-js" src="https://www.googletagmanager.com/gtag/js?id=G-HFRQXE4S60" type="text/javascript">
  </script>
  <script id="google_gtagjs-js-after" type="text/javascript">
   window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}
gtag('set', 'linker', {"domains":["www.mevotech.com"]} );
gtag("js", new Date());
gtag("set", "developer_id.dZTNiMT", true);
gtag("config", "G-HFRQXE4S60");
  </script>
  <!-- End Google Analytics snippet added by Site Kit -->
  <link href="https://www.mevotech.com/wp-json/" rel="https://api.w.org/"/>
  <link href="https://www.mevotech.com/wp-json/wp/v2/pages/452" rel="alternate" type="application/json"/>
  <link href="https://www.mevotech.com/xmlrpc.php?rsd" rel="EditURI" title="RSD" type="application/rsd+xml"/>
  <link href="https://www.mevotech.com/wp-includes/wlwmanifest.xml" rel="wlwmanifest" type="application/wlwmanifest+xml"/>
  <meta content="WordPress 6.0.6" name="generator"/>
  <link href="https://www.mevotech.com/?p=452" rel="shortlink"/>
  <link href="https://www.mevotech.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.mevotech.com%2Fpart%2F" rel="alternate" type="application/json+oembed"/>
  <link href="https://www.mevotech.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.mevotech.com%2Fpart%2F&amp;format=xml" rel="alternate" type="text/xml+oembed"/>
  <meta content="Site Kit by Google 1.115.0" name="generator"/>
  <meta content="aHR0cHM6Ly93d3cubWV2b3RlY2guY29tL3dwLWxvZ2luLnBocA==" name="google"/>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-159120141-1">
  </script>
  <script>
   window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-159120141-1');
  </script>
  <!-- Google Tag Manager -->
  <script>
   (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5KRVX32');
  </script>
  <!-- End Google Tag Manager -->
  <!-- Google tag (gtag.js) -->
  <script async="" src="https://www.googletagmanager.com/gtag/js?id=AW-10990581449">
  </script>
  <script>
   window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'AW-10990581449');
  </script>
  <!-- Start of HubSpot Embed Code -->
  <script async="" defer="" id="hs-script-loader" src="//js.hs-scripts.com/7086927.js" type="text/javascript">
  </script>
  <!-- End of HubSpot Embed Code -->
  <meta content="Powered by WPBakery Page Builder - drag and drop page builder for WordPress." name="generator"/>
  <!-- Google Tag Manager snippet added by Site Kit -->
  <script type="text/javascript">
   ( function( w, d, s, l, i ) {
				w[l] = w[l] || [];
				w[l].push( {'gtm.start': new Date().getTime(), event: 'gtm.js'} );
				var f = d.getElementsByTagName( s )[0],
					j = d.createElement( s ), dl = l != 'dataLayer' ? '&l=' + l : '';
				j.async = true;
				j.src = 'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
				f.parentNode.insertBefore( j, f );
			} )( window, document, 'script', 'dataLayer', 'GTM-5KRVX32' );
  </script>
  <!-- End Google Tag Manager snippet added by Site Kit -->
  <link href="https://www.mevotech.com/wp-content/uploads/2020/04/cropped-favicon-32x32.png" rel="icon" sizes="32x32"/>
  <link href="https://www.mevotech.com/wp-content/uploads/2020/04/cropped-favicon-192x192.png" rel="icon" sizes="192x192"/>
  <link href="https://www.mevotech.com/wp-content/uploads/2020/04/cropped-favicon-180x180.png" rel="apple-touch-icon"/>
  <meta content="https://www.mevotech.com/wp-content/uploads/2020/04/cropped-favicon-270x270.png" name="msapplication-TileImage"/>
  <style id="wp-custom-css" type="text/css">
   .atwater-home-page-slider div.wpb_column:first-child > .vc_column-inner > .wpb_wrapper {
	padding: 3rem;
	padding-left: 5 rem;
}
.atwater-home-page-slider .vc_col-sm-6:nth-child(2) .vc_column-inner {
	padding-right: 0;
	padding-left: 0;
}
.atwater-home-page-slider .vc_col-sm-6:nth-child(2) > .vc_column-inner > .wpb_wrapper {
	height: 100%;
}
.atwater-home-page-slider .vc_col-sm-6:nth-child(2) .wpb_single_image,
.atwater-home-page-slider .vc_col-sm-6:nth-child(2) .vc_figure {
	height: 100%;
}
.atwt-text-blue {
	color: #2573be;
}
.atwater-to-image-slider::before {
	  content: "";
    display: block !important;
    width: 300px;
    height: 300px;
    background-image: url(https://www.mevotech.com/wp-content/themes/mevotech/images/logo-icon.svg);
    background-repeat: no-repeat;
    background-size: 100% 100%;
    background-position: center;
    position: absolute;
    left: -50px;
    top: -55px;
    z-index: -1;
}

.atwater-home-page-slider {
	box-shadow: -5px 0px 15px rgb(0 0 0 / 15%);
	border-top-left-radius: 80px;
	border-bottom-right-radius: 80px;
	background-color: #fff;
	margin: 25px;
}
.slick-initialized .slick-slide.atwater-home-page-slider  {
	display: flex;
}
.atwater-home-page-slider .atwm-video {
	margin-bottom: 0;

}
.atwater-home-page-slider .vc_single_image-wrapper {
	position: relative;
	height: 100%;
	width: 100%;
	overflow: hidden;
	border-bottom-right-radius: 80px;
}
.atwater-home-page-slider .vc_single_image-wrapper img {
	min-height: 100%;
	min-width: 100%;
	object-fit: cover;
}

.atwater-home-page-slider .atwm-video .vc_single_image-wrapper:before {
	content: "";
	display: block;
	position: absolute;
	top: 0;
	left: 0;
	right: 0;

In [8]:
from lxml import etree

In [9]:
html = etree.HTML(str(soup))

list_vehicle = []
list_tr = html.xpath('//div[@class="atwm-table-continer"]/table/tbody/tr')
for tr in list_tr:
    vehicle_temp = tr.xpath('./td/text()')[0].strip() + ' '
    vehicle_temp += tr.xpath('./td/text()')[1].strip() + ' '
    if '-' in tr.xpath('./td/text()')[2]:
        vehicle_temp += tr.xpath('./td/text()')[2].split('-')[1].strip() + '-' + tr.xpath('./td/text()')[2].split('-')[0].strip() + ' '
    else:
        vehicle_temp += tr.xpath('./td/text()')[2].strip() + ' '
    vehicle_temp += tr.xpath('./td/text()')[3].strip()
    list_vehicle.append(vehicle_temp)
    
vehicle = '\n'.join(list_vehicle)

print(vehicle)

Chrysler Neon 2000-2002 Rear Left Rearward
Dodge Neon 2000-2005 Rear Left Rearward
Plymouth Neon 2000-2001 Rear Left Rearward

In [10]:
df_temp = pd.DataFrame([{'status': 'ok',
                         'Part_Number': part_number,
                         'Vehicle': vehicle}])

df = pd.concat([df, df_temp], ignore_index=True).fillna('')

df

  status Part_Number                                            Vehicle
0     ok   CMS251049  Chrysler Neon 2000-2002 Rear Left Rearward\nDo...