In [1]:
import pandas as pd
df_menu = pd.read_excel(r'C:\Users\YangTeng\Desktop\数据来源\05、STANDARD\STANDARD_menu.xlsx', header=0)
list_part_number = df_menu['Part_Number'].to_list()

print('总数量：' + str(len(list_part_number)))
list_part_number

总数量：768

['ALS295',
 'ALS296',
 'ALS297',
 'ALS298',
 'ALS299',
 'ALS300',
 'ALS302',
 'ALS303',
 'ALS305',
 'ALS306',
 'ALS307',
 'ALS308',
 'ALS309',
 'ALS310',
 'ALS312',
 'ALS314',
 'ALS316',
 'ALS321',
 'ALS325',
 'ALS327',
 'ALS328',
 'ALS329',
 'ALS330',
 'ALS331',
 'ALS333',
 'ALS335',
 'ALS339',
 'ALS341',
 'ALS342',
 'ALS343',
 'ALS344',
 'ALS345',
 'ALS346',
 'ALS347',
 'ALS348',
 'ALS349',
 'ALS350',
 'ALS351',
 'ALS355',
 'ALS358',
 'ALS359',
 'ALS360',
 'ALS363',
 'ALS364',
 'ALS365',
 'ALS366',
 'ALS367',
 'ALS368',
 'ALS369',
 'ALS370',
 'ALS371',
 'ALS372',
 'ALS373',
 'ALS374',
 'ALS375',
 'ALS376',
 'ALS377',
 'ALS378',
 'ALS379',
 'ALS380',
 'ALS381',
 'ALS382',
 'ALS383',
 'ALS384',
 'ALS385',
 'ALS386',
 'ALS387',
 'ALS388',
 'ALS389',
 'ALS390',
 'ALS391',
 'ALS392',
 'ALS393',
 'ALS394',
 'ALS395',
 'ALS396',
 'ALS397',
 'ALS398',
 'ALS399',
 'ALS400',
 'ALS401',
 'ALS402',
 'ALS403',
 'ALS404',
 'ALS405',
 'ALS406',
 'ALS407',
 'ALS408',
 'ALS410',
 'ALS411',
 'ALS412',
 'ALS413',
 'ALS414',
 'ALS415',
 'ALS416',
 'ALS417',
 'ALS418',
 'ALS419',
 'ALS420',
 'ALS421',
 'ALS423',
 'ALS424',
 'ALS425',
 'ALS426',
 'ALS427',
 'ALS428',
 'ALS429',
 'ALS430',
 'ALS430T',
 'ALS431',
 'ALS432',
 'ALS433',
 'ALS434',
 'ALS435',
 'ALS436',
 'ALS437',
 'ALS438',
 'ALS439',
 'ALS440',
 'ALS441',
 'ALS442',
 'ALS443',
 'ALS444',
 'ALS445',
 'ALS446',
 'ALS447',
 'ALS448',
 'ALS449',
 'ALS450',
 'ALS451',
 'ALS452',
 'ALS453',
 'ALS454',
 'ALS455',
 'ALS457',
 'ALS458',
 'ALS459',
 'ALS461',
 'ALS462',
 'ALS463',
 'ALS464',
 'ALS465',
 'ALS466',
 'ALS467',
 'ALS467T',
 'ALS468',
 'ALS468T',
 'ALS469',
 'ALS469T',
 'ALS470',
 'ALS471',
 'ALS472',
 'ALS473',
 'ALS474',
 'ALS475',
 'ALS476',
 'ALS477',
 'ALS478',
 'ALS479',
 'ALS480',
 'ALS481',
 'ALS482',
 'ALS482T',
 'ALS483',
 'ALS483T',
 'ALS484',
 'ALS485',
 'ALS486',
 'ALS487',
 'ALS488',
 'ALS489',
 'ALS491',
 'ALS494',
 'ALS495',
 'ALS496',
 'ALS497',
 'ALS498',
 'ALS499',
 'ALS501',
 'ALS503',
 'ALS504',
 'ALS505',
 'ALS505T',
 'ALS506',
 'ALS508',
 'ALS509',
 'ALS510',
 'ALS511',
 'ALS512',
 'ALS513',
 'ALS514',
 'ALS515',
 'ALS516',
 'ALS517',
 'ALS518',
 'ALS520',
 'ALS521',
 'ALS522',
 'ALS523',
 'ALS524',
 'ALS525',
 'ALS526',
 'ALS527',
 'ALS528',
 'ALS529',
 'ALS530',
 'ALS532',
 'ALS533',
 'ALS535',
 'ALS537',
 'ALS538',
 'ALS539',
 'ALS540',
 'ALS541',
 'ALS542',
 'ALS543',
 'ALS544',
 'ALS545',
 'ALS546',
 'ALS547',
 'ALS548',
 'ALS549',
 'ALS550',
 'ALS551',
 'ALS552',
 'ALS553',
 'ALS554',
 'ALS555',
 'ALS559',
 'ALS560',
 'ALS561',
 'ALS562',
 'ALS563',
 'ALS564',
 'ALS565',
 'ALS566',
 'ALS567',
 'ALS568',
 'ALS569',
 'ALS570',
 'ALS571',
 'ALS572',
 'ALS573',
 'ALS574',
 'ALS575',
 'ALS576',
 'ALS578',
 'ALS579',
 'ALS580',
 'ALS581',
 'ALS582',
 'ALS583',
 'ALS584',
 'ALS585',
 'ALS586',
 'ALS587',
 'ALS588',
 'ALS589',
 'ALS590',
 'ALS591',
 'ALS592',
 'ALS593',
 'ALS594',
 'ALS595',
 'ALS596',
 'ALS597',
 'ALS598',
 'ALS599',
 'ALS600',
 'ALS601',
 'ALS602',
 'ALS603',
 'ALS605',
 'ALS606',
 'ALS607',
 'ALS608',
 'ALS609',
 'ALS610',
 'ALS611',
 'ALS612',
 'ALS613',
 'ALS614',
 'ALS615',
 'ALS616',
 'ALS617',
 'ALS618',
 'ALS619',
 'ALS620',
 'ALS621',
 'ALS622',
 'ALS623',
 'ALS624',
 'ALS625',
 'ALS626',
 'ALS627',
 'ALS628',
 'ALS629',
 'ALS630',
 'ALS631',
 'ALS633',
 'ALS634',
 'ALS635',
 'ALS636',
 'ALS637',
 'ALS638',
 'ALS639',
 'ALS640',
 'ALS641',
 'ALS642',
 'ALS643',
 'ALS644',
 'ALS645',
 'ALS646',
 'ALS647',
 'ALS648',
 'ALS649',
 'ALS650',
 'ALS651',
 'ALS652',
 'ALS653',
 'ALS654',
 'ALS655',
 'ALS656',
 'ALS657',
 'ALS658',
 'ALS659',
 'ALS660',
 'ALS661',
 'ALS662',
 'ALS663',
 'ALS664',
 'ALS665',
 'ALS666',
 'ALS667',
 'ALS670',
 'ALS671',
 'ALS672',
 'ALS673',
 'ALS674',
 'ALS675',
 'ALS679',
 'ALS680',
 'ALS681',
 'ALS683',
 'ALS684',
 'ALS685',
 'ALS686',
 'ALS687',
 'ALS688',
 'ALS690',
 'ALS691',
 'ALS692',
 'ALS693',
 'ALS694',
 'ALS695',
 'ALS696',
 'ALS697',
 'ALS698',
 'ALS699',
 'ALS701',
 'ALS702',
 'ALS703',
 'ALS704',
 'ALS705',
 'ALS707',
 'ALS708',
 'ALS709',
 'ALS710',
 'ALS713',
 'ALS714',
 'ALS715',
 'ALS716',
 'ALS717',
 'ALS718',
 'ALS719',
 'ALS720',
 'ALS721',
 'ALS723',
 'ALS724',
 'ALS725',
 'ALS726',
 'ALS729',
 'ALS731',
 'ALS732',
 'ALS733',
 'ALS734',
 'ALS735',
 'ALS736',
 'ALS737',
 'ALS738',
 'ALS739',
 'ALS740',
 'ALS741',
 'ALS742',
 'ALS745',
 'ALS746',
 'ALS747',
 'ALS748',
 'ALS749',
 'ALS750',
 'ALS751',
 'ALS752',
 'ALS753',
 'ALS754',
 'ALS755',
 'ALS756',
 'ALS757',
 'ALS758',
 'ALS759',
 'ALS763',
 'ALS764',
 'ALS765',
 'ALS766',
 'ALS768',
 'ALS769',
 'ALS770',
 'ALS772',
 'ALS773',
 'ALS774',
 'ALS776',
 'ALS777',
 'ALS778',
 'ALS782',
 'ALS783',
 'ALS784',
 'ALS786',
 'ALS787',
 'ALS788',
 'ALS789',
 'ALS790',
 'ALS791',
 'ALS792',
 'ALS793',
 'ALS794',
 'ALS796',
 'ALS797',
 'ALS799',
 'ALS800',
 'ALS801',
 'ALS802',
 'ALS803',
 'ALS804',
 'ALS805',
 'ALS806',
 'ALS811',
 'ALS812',
 'ALS813',
 'ALS814',
 'ALS815',
 'ALS816',
 'ALS817',
 'ALS818',
 'ALS819',
 'ALS820',
 'ALS821',
 'ALS822',
 'ALS823',
 'ALS824',
 'ALS825',
 'ALS827',
 'ALS828',
 'ALS829',
 'ALS830',
 'ALS831',
 'ALS832',
 'ALS834',
 'ALS835',
 'ALS836',
 'ALS837',
 'ALS838',
 'ALS839',
 'ALS841',
 'ALS842',
 'ALS843',
 'ALS844',
 'ALS845',
 'ALS846',
 'ALS847',
 'ALS848',
 'ALS849',
 'ALS850',
 'ALS851',
 'ALS852',
 'ALS853',
 'ALS854',
 'ALS855',
 'ALS856',
 'ALS857',
 'ALS858',
 'ALS859',
 'ALS860',
 'ALS862',
 'ALS865',
 'ALS867',
 'ALS868',
 'ALS869',
 'ALS870',
 'ALS871',
 'ALS872',
 'ALS873',
 'ALS874',
 'ALS875',
 'ALS876',
 'ALS877',
 'ALS878',
 'ALS879',
 'ALS880',
 'ALS881',
 'ALS882',
 'ALS883',
 'ALS884',
 'ALS886',
 'ALS888',
 'ALS889',
 'ALS891',
 'ALS892',
 'ALS893',
 'ALS894',
 'ALS895',
 'ALS896',
 'ALS897',
 'ALS898',
 'ALS899',
 'ALS902',
 'ALS903',
 'ALS904',
 'ALS905',
 'ALS906',
 'ALS907',
 'ALS908',
 'ALS909',
 'ALS910',
 'ALS911',
 'ALS912',
 'ALS913',
 'ALS914',
 'ALS915',
 'ALS916',
 'ALS917',
 'ALS917T',
 'ALS919',
 'ALS920',
 'ALS923',
 'ALS924',
 'ALS925',
 'ALS926',
 'ALS927',
 'ALS928',
 'ALS929',
 'ALS931',
 'ALS933',
 'ALS940',
 'ALS947',
 'ALS948',
 'ALS949',
 'ALS950',
 'ALS951',
 'ALS953',
 'ALS954',
 'ALS956',
 'ALS958',
 'ALS961',
 'ALS962',
 'ALS963',
 'ALS964',
 'ALS965',
 'ALS967',
 'ALS969',
 'ALS970',
 'ALS971',
 'ALS972',
 'ALS973',
 'ALS974',
 'ALS975',
 'ALS976',
 'ALS977',
 'ALS170',
 'ALS171',
 'ALS172',
 'ALS173',
 'ALS174',
 'ALS175',
 'ALS176',
 'ALS177',
 'ALS179',
 'ALS180',
 'ALS181',
 'ALS181T',
 'ALS182',
 'ALS183',
 'ALS184',
 'ALS185',
 'ALS186',
 'ALS188',
 'ALS190',
 'ALS191',
 'ALS192',
 'ALS193',
 'ALS195',
 'ALS196',
 'ALS197',
 'ALS197T',
 'ALS198',
 'ALS199',
 'ALS200',
 'ALS201',
 'ALS202',
 'ALS203',
 'ALS204',
 'ALS205',
 'ALS207',
 'ALS209',
 'ALS210',
 'ALS211',
 'ALS219',
 'ALS220',
 'ALS224',
 'ALS225',
 'ALS226',
 'ALS228',
 'ALS229',
 'ALS230',
 'ALS231',
 'ALS233',
 'ALS234',
 'ALS235',
 'ALS237',
 'ALS238',
 'ALS240',
 'ALS243',
 'ALS245',
 'ALS246',
 'ALS247',
 'ALS248',
 'ALS249',
 'ALS250',
 'ALS252',
 'ALS253',
 'ALS254',
 'ALS255',
 'ALS257',
 'ALS258',
 'ALS258T',
 'ALS259',
 'ALS263',
 'ALS265',
 'ALS266',
 'ALS267',
 'ALS268',
 'ALS270',
 'ALS271',
 'ALS274',
 'ALS275',
 'ALS276',
 'ALS277',
 'ALS278',
 'ALS279',
 'ALS280',
 'ALS281',
 'ALS282',
 'ALS283',
 'ALS284',
 'ALS285',
 'ALS286',
 'ALS287',
 'ALS288',
 'ALS289',
 'ALS290',
 'ALS291',
 'ALS292',
 'ALS293',
 'ALS294',
 'ALH22',
 'ALH81',
 'ALH134',
 'ALH173',
 'ALH379',
 'ALH380',
 'ALS2',
 'ALS3',
 'ALS7',
 'ALS8',
 'ALS9',
 'ALS10',
 'ALS11',
 'ALS17',
 'ALS33',
 'ALS35',
 'ALS40',
 'ALS41',
 'ALS42',
 'ALS43',
 'ALS45',
 'ALS47',
 'ALS48',
 'ALS49',
 'ALS50',
 'ALS52',
 'ALS53',
 'ALS54',
 'ALS55',
 'ALS57',
 'ALS58',
 'ALS59',
 'ALS60',
 'ALS61',
 'ALS62',
 'ALS63',
 'ALS64',
 'ALS65',
 'ALS66',
 'ALS67',
 'ALS70',
 'ALS71',
 'ALS72',
 'ALS74',
 'ALS76',
 'ALS77',
 'ALS78',
 'ALS80',
 'ALS82',
 'ALS84',
 'ALS85',
 'ALS87',
 'ALS88',
 'ALS89',
 'ALS90',
 'ALS92',
 'ALS93',
 'ALS100',
 'ALS102',
 'ALS103',
 'ALS104',
 'ALS105',
 'ALS107',
 'ALS108',
 'ALS110',
 'ALS111',
 'ALS112',
 'ALS113',
 'ALS115',
 'ALS116',
 'ALS117',
 'ALS120',
 'ALS121',
 'ALS127',
 'ALS129',
 'ALS131',
 'ALS137',
 'ALS139',
 'ALS141',
 'ALS142',
 'ALS148',
 'ALS151',
 'ALS154',
 'ALS155',
 'ALS156',
 'ALS157',
 'ALS159',
 'ALS160',
 'ALS161',
 'ALS162',
 'ALS163',
 'ALS164',
 'ALS165',
 'ALS166',
 'ALS167',
 'ALS169']

In [47]:
df = pd.DataFrame(columns=['Part_Number',
                           'Part_Type',
                           'POP',
                           'Per_Car',
                           'Vehicle',
                           'Src',
                           'status'])

df

Empty DataFrame
Columns: [Part_Number, Part_Type, POP, Per_Car, Vehicle, Src, status]
Index: []

In [48]:
import requests
import json
from bs4 import BeautifulSoup
from lxml import etree

In [49]:
i = 0

resp = requests.get('https://ecatalog.smpcorp.com/V2/STD/api/part/partselect?part=' + list_part_number[i] + '&func=PART').text
resp

'{"pd":{"rowId":1,"site":"STD","webBase":"ALS295","brand":"STI","basePart":"ALS295","partDesc_en":"ABS Sensor","partLongDesc_en":"ABS Speed Sensor","pop":"F","partComment":null,"qtyEach":1,"webColumn_Id":null,"categoryName_en":null,"vehicleId":null,"mfg":null,"mfG_Part":null,"maxRows":1,"brandLink":null,"imageUrl":null},"pp":{"buyersGuides":[{"basePart":"ALS295","buyersGuideId":27388,"buyersGuideDesc":"Infiniti I30 (01-00)"},{"basePart":"ALS295","buyersGuideId":36268,"buyersGuideDesc":"Nissan Maxima (01-00)"}],"partSpecs":[{"attributeCode":"110","attributeValue":1905,"attributeSort":0,"attributeName_en":"Warranty","siteValue_en":"3 years/36,000 mile"},{"attributeCode":"388","attributeValue":1843,"attributeSort":0,"attributeName_en":"Number of Bolt Holes","siteValue_en":"3"},{"attributeCode":"9","attributeValue":5959,"attributeSort":10310,"attributeName_en":"Connector Gender","siteValue_en":"Male (1)"},{"attributeCode":"160","attributeValue":249,"attributeSort":10340,"attributeName_en":"Connector Quantity","siteValue_en":"1"},{"attributeCode":"171","attributeValue":6776,"attributeSort":10350,"attributeName_en":"Connector Shape","siteValue_en":"Rectangular"},{"attributeCode":"37","attributeValue":2167,"attributeSort":10850,"attributeName_en":"Harness Length - Inches","siteValue_en":"34"},{"attributeCode":"38","attributeValue":8181,"attributeSort":10860,"attributeName_en":"Harness Length - mm","siteValue_en":"867 mm"},{"attributeCode":"54","attributeValue":7842,"attributeSort":11370,"attributeName_en":"Mounting Location","siteValue_en":"Wheel"},{"attributeCode":"56","attributeValue":4879,"attributeSort":11400,"attributeName_en":"Mounting Type","siteValue_en":"Flange"},{"attributeCode":"104","attributeValue":4753,"attributeSort":12380,"attributeName_en":"Terminal Gender","siteValue_en":"Female (1)"},{"attributeCode":"164","attributeValue":1320,"attributeSort":12390,"attributeName_en":"Terminal Quantity","siteValue_en":"2"},{"attributeCode":"105","attributeValue":3983,"attributeSort":12400,"attributeName_en":"Terminal Type","siteValue_en":"Blade"}],"imageUrls":[],"relatedParts":[{"webBase":"S2943","brand":"STI","basePart":"S2943","partDesc_en":"Electrical Connector","partLongDesc_en":"ABS Speed Sensor Connector","rowId":1}],"relatedCategories":null,"fandB":[{"basePart":"ALS295","fbId":"301746","fbDesc":"For over 100 years, professional technicians have trusted Standard® to replace the failed OE part. Standard® manufacturers the highest-quality, best-performing parts for all import and domestic vehicles; gas, diesel, electric and hybrid. Precision manufacturing, multiple layers of testing, and a detailed validation process ensures Standard® parts don’t just fit, they perform and they last.","taB_Type":"F&B Heading","assetSort":1,"digiSort":100},{"basePart":"ALS295","fbId":"53","fbDesc":"As a global manufacturer, we have complete control of the manufacturing process from componentry to finished product","taB_Type":"F&B Details","assetSort":8,"digiSort":200},{"basePart":"ALS295","fbId":"167","fbDesc":"Our ABS sensor line has complete coverage for domestic and import applications","taB_Type":"F&B Details","assetSort":8,"digiSort":210},{"basePart":"ALS295","fbId":"223","fbDesc":"Over 1500 ABS numbers cataloged – and growing","taB_Type":"F&B Details","assetSort":8,"digiSort":220},{"basePart":"ALS295","fbId":"168","fbDesc":"Our ABS sensors are engineered for precision performance, durability and a long service life","taB_Type":"F&B Details","assetSort":8,"digiSort":230},{"basePart":"ALS295","fbId":"107","fbDesc":"Featuring the broadest sensor coverage in the market, we meet the service professionals needs with the highest quality product every time he opens the box","taB_Type":"F&B Details","assetSort":8,"digiSort":240},{"basePart":"ALS295","fbId":"51","fbDesc":"As a global manufacturer of emission components, complete quality control is maintained through the manufacturing process from componentry to finished product","taB_Type":"F&B Details","assetSort":8,"digiSort":250}],"digiAssests":[{"asset_ID":3,"assetName":"Bulletins","basePart":"ALS295","fileName":"ST10235ALS-FEB14_JTF_ABS.pdf","fileURL":"http://eaccess.smpcorp.com/eCatalogs/Downloads/EMD/ST10235ALS-FEB14_JTF_ABS.pdf","comment_ID":"212312","comment":"Just The Facts: Anti-Lock Brake (ABS) Sensors","assetSort":3,"digiSort":0,"videoImage":null},{"asset_ID":3,"assetName":"Bulletins","basePart":"ALS295","fileName":"IM14137-IntermotorBro.pdf","fileURL":"http://eaccess.smpcorp.com/eCatalogs/Downloads/EMD/IM14137-IntermotorBro.pdf","comment_ID":"260618","comment":"Intermotor Brochure","assetSort":3,"digiSort":0,"videoImage":null},{"asset_ID":3,"assetName":"Bulletins","basePart":"ALS295","fileName":"ST10235ABT-FEB14_JTF_ABS-Test.pdf","fileURL":"http://eaccess.smpcorp.com/eCatalogs/Downloads/EMD/ST10235ABT-FEB14_JTF_ABS-Test.pdf","comment_ID":"260623","comment":"Just the Facts: Anti-lock Brake (ABS) Sensors Testing","assetSort":3,"digiSort":0,"videoImage":null},{"asset_ID":3,"assetName":"Bulletins","basePart":"ALS295","fileName":"ST10235VWL-MAR13_JTF_veh_warn_light.pdf","fileURL":"http://eaccess.smpcorp.com/eCatalogs/Downloads/EMD/ST10235VWL-MAR13_JTF_veh_warn_light.pdf","comment_ID":"260657","comment":"Just the Facts: Vehicle Warning Lights","assetSort":3,"digiSort":0,"videoImage":null},{"asset_ID":3,"assetName":"Bulletins","basePart":"ALS295","fileName":"ST11237-Standard_Interactive_Buyers_Guide-WEB.pdf","fileURL":"http://eaccess.smpcorp.com/eCatalogs/Downloads/EMD/ST11237-Standard_Interactive_Buyers_Guide-WEB.pdf","comment_ID":"260664","comment":"Standard Interactive Buyer\'s Guide","assetSort":3,"digiSort":0,"videoImage":null},{"asset_ID":7,"assetName":"Videos","basePart":"ALS295","fileName":"ABS Speed Sensor Replacement - Typical","fileURL":"https://youtube.com/embed/NGQK384mmTg","comment_ID":"212334","comment":"ABS Speed Sensor Replacement - Typical","assetSort":7,"digiSort":10330,"videoImage":null},{"asset_ID":7,"assetName":"Videos","basePart":"ALS295","fileName":"SMP Engineering Spotlight: Long Island City","fileURL":"https://youtube.com/embed/vac2vas7vJY","comment_ID":"220958","comment":"SMP Engineering Spotlight: Long Island City","assetSort":7,"digiSort":80000,"videoImage":null},{"asset_ID":7,"assetName":"Videos","basePart":"ALS295","fileName":"WIYB: Engineering Spotlight: Long Island City","fileURL":"https://youtube.com/embed/I-kWdiTPe08","comment_ID":"291618","comment":"WIYB: Engineering Spotlight: Long Island City","assetSort":7,"digiSort":80003,"videoImage":null},{"asset_ID":7,"assetName":"Videos","basePart":"ALS295","fileName":"SMP Engineering - Long Island City Facility Tour","fileURL":"https://youtube.com/embed/ut5LYbUFCKo","comment_ID":"271219","comment":"SMP Engineering - Long Island City Facility Tour","assetSort":7,"digiSort":80350,"videoImage":null},{"asset_ID":7,"assetName":"Videos","basePart":"ALS295","fileName":"Standard Interactive Buyers Guide","fileURL":"https://youtube.com/embed/mRzK11T9pxg","comment_ID":"251346","comment":"Standard Interactive Buyers Guide","assetSort":7,"digiSort":90030,"videoImage":null},{"asset_ID":7,"assetName":"Videos","basePart":"ALS295","fileName":"SMP Parts App Update (3.0.9)","fileURL":"https://youtube.com/embed/KpEXmjcKbMc","comment_ID":"270593","comment":"SMP Parts App Update (3.0.9)","assetSort":7,"digiSort":90090,"videoImage":null}],"categories":[{"basePart":"ALS295","webLayout_ID":250,"categoryName_en":"Sensor - ABS Speed","prodCategory_ASort":24710}],"crossRef":null,"completeRepair":{"serviceParts":[{"webBase":"S2943","brand":"STI","basePart":"S2943","partDesc_en":"Electrical Connector","partLongDesc_en":"ABS Speed Sensor Connector","rowId":1}],"serviceSpec":[{"serviceName":"Fuel Filter Flush (Required)"},{"serviceName":"Oil Change (Required)"}]}}}'

In [50]:
info = json.loads(resp)

info

{'pd': {'rowId': 1,
  'site': 'STD',
  'webBase': 'ALS295',
  'brand': 'STI',
  'basePart': 'ALS295',
  'partDesc_en': 'ABS Sensor',
  'partLongDesc_en': 'ABS Speed Sensor',
  'pop': 'F',
  'partComment': None,
  'qtyEach': 1,
  'webColumn_Id': None,
  'categoryName_en': None,
  'vehicleId': None,
  'mfg': None,
  'mfG_Part': None,
  'maxRows': 1,
  'brandLink': None,
  'imageUrl': None},
 'pp': {'buyersGuides': [{'basePart': 'ALS295',
    'buyersGuideId': 27388,
    'buyersGuideDesc': 'Infiniti I30 (01-00)'},
   {'basePart': 'ALS295',
    'buyersGuideId': 36268,
    'buyersGuideDesc': 'Nissan Maxima (01-00)'}],
  'partSpecs': [{'attributeCode': '110',
    'attributeValue': 1905,
    'attributeSort': 0,
    'attributeName_en': 'Warranty',
    'siteValue_en': '3 years/36,000 mile'},
   {'attributeCode': '388',
    'attributeValue': 1843,
    'attributeSort': 0,
    'attributeName_en': 'Number of Bolt Holes',
    'siteValue_en': '3'},
   {'attributeCode': '9',
    'attributeValue': 5959,
    'attributeSort': 10310,
    'attributeName_en': 'Connector Gender',
    'siteValue_en': 'Male (1)'},
   {'attributeCode': '160',
    'attributeValue': 249,
    'attributeSort': 10340,
    'attributeName_en': 'Connector Quantity',
    'siteValue_en': '1'},
   {'attributeCode': '171',
    'attributeValue': 6776,
    'attributeSort': 10350,
    'attributeName_en': 'Connector Shape',
    'siteValue_en': 'Rectangular'},
   {'attributeCode': '37',
    'attributeValue': 2167,
    'attributeSort': 10850,
    'attributeName_en': 'Harness Length - Inches',
    'siteValue_en': '34'},
   {'attributeCode': '38',
    'attributeValue': 8181,
    'attributeSort': 10860,
    'attributeName_en': 'Harness Length - mm',
    'siteValue_en': '867 mm'},
   {'attributeCode': '54',
    'attributeValue': 7842,
    'attributeSort': 11370,
    'attributeName_en': 'Mounting Location',
    'siteValue_en': 'Wheel'},
   {'attributeCode': '56',
    'attributeValue': 4879,
    'attributeSort': 11400,
    'attributeName_en': 'Mounting Type',
    'siteValue_en': 'Flange'},
   {'attributeCode': '104',
    'attributeValue': 4753,
    'attributeSort': 12380,
    'attributeName_en': 'Terminal Gender',
    'siteValue_en': 'Female (1)'},
   {'attributeCode': '164',
    'attributeValue': 1320,
    'attributeSort': 12390,
    'attributeName_en': 'Terminal Quantity',
    'siteValue_en': '2'},
   {'attributeCode': '105',
    'attributeValue': 3983,
    'attributeSort': 12400,
    'attributeName_en': 'Terminal Type',
    'siteValue_en': 'Blade'}],
  'imageUrls': [],
  'relatedParts': [{'webBase': 'S2943',
    'brand': 'STI',
    'basePart': 'S2943',
    'partDesc_en': 'Electrical Connector',
    'partLongDesc_en': 'ABS Speed Sensor Connector',
    'rowId': 1}],
  'relatedCategories': None,
  'fandB': [{'basePart': 'ALS295',
    'fbId': '301746',
    'fbDesc': 'For over 100 years, professional technicians have trusted Standard® to replace the failed OE part. Standard® manufacturers the highest-quality, best-performing parts for all import and domestic vehicles; gas, diesel, electric and hybrid. Precision manufacturing, multiple layers of testing, and a detailed validation process ensures Standard® parts don’t just fit, they perform and they last.',
    'taB_Type': 'F&B Heading',
    'assetSort': 1,
    'digiSort': 100},
   {'basePart': 'ALS295',
    'fbId': '53',
    'fbDesc': 'As a global manufacturer, we have complete control of the manufacturing process from componentry to finished product',
    'taB_Type': 'F&B Details',
    'assetSort': 8,
    'digiSort': 200},
   {'basePart': 'ALS295',
    'fbId': '167',
    'fbDesc': 'Our ABS sensor line has complete coverage for domestic and import applications',
    'taB_Type': 'F&B Details',
    'assetSort': 8,
    'digiSort': 210},
   {'basePart': 'ALS295',
    'fbId': '223',
    'fbDesc': 'Over 1500 ABS numbers cataloged – and growing',
    'taB_Type': 'F&B Details',
    'assetSort': 8,
    'digiSort': 220},
   {'basePart': 'ALS295',
    'fbId': '168',
    'fbDesc': 'Our ABS sensors are engineered for precision performance, durability and a long service life',
    'taB_Type': 'F&B Details',
    'assetSort': 8,
    'digiSort': 230},
   {'basePart': 'ALS295',
    'fbId': '107',
    'fbDesc': 'Featuring the broadest sensor coverage in the market, we meet the service professionals needs with the highest quality product every time he opens the box',
    'taB_Type': 'F&B Details',
    'assetSort': 8,
    'digiSort': 240},
   {'basePart': 'ALS295',
    'fbId': '51',
    'fbDesc': 'As a global manufacturer of emission components, complete quality control is maintained through the manufacturing process from componentry to finished product',
    'taB_Type': 'F&B Details',
    'assetSort': 8,
    'digiSort': 250}],
  'digiAssests': [{'asset_ID': 3,
    'assetName': 'Bulletins',
    'basePart': 'ALS295',
    'fileName': 'ST10235ALS-FEB14_JTF_ABS.pdf',
    'fileURL': 'http://eaccess.smpcorp.com/eCatalogs/Downloads/EMD/ST10235ALS-FEB14_JTF_ABS.pdf',
    'comment_ID': '212312',
    'comment': 'Just The Facts: Anti-Lock Brake (ABS) Sensors',
    'assetSort': 3,
    'digiSort': 0,
    'videoImage': None},
   {'asset_ID': 3,
    'assetName': 'Bulletins',
    'basePart': 'ALS295',
    'fileName': 'IM14137-IntermotorBro.pdf',
    'fileURL': 'http://eaccess.smpcorp.com/eCatalogs/Downloads/EMD/IM14137-IntermotorBro.pdf',
    'comment_ID': '260618',
    'comment': 'Intermotor Brochure',
    'assetSort': 3,
    'digiSort': 0,
    'videoImage': None},
   {'asset_ID': 3,
    'assetName': 'Bulletins',
    'basePart': 'ALS295',
    'fileName': 'ST10235ABT-FEB14_JTF_ABS-Test.pdf',
    'fileURL': 'http://eaccess.smpcorp.com/eCatalogs/Downloads/EMD/ST10235ABT-FEB14_JTF_ABS-Test.pdf',
    'comment_ID': '260623',
    'comment': 'Just the Facts: Anti-lock Brake (ABS) Sensors Testing',
    'assetSort': 3,
    'digiSort': 0,
    'videoImage': None},
   {'asset_ID': 3,
    'assetName': 'Bulletins',
    'basePart': 'ALS295',
    'fileName': 'ST10235VWL-MAR13_JTF_veh_warn_light.pdf',
    'fileURL': 'http://eaccess.smpcorp.com/eCatalogs/Downloads/EMD/ST10235VWL-MAR13_JTF_veh_warn_light.pdf',
    'comment_ID': '260657',
    'comment': 'Just the Facts: Vehicle Warning Lights',
    'assetSort': 3,
    'digiSort': 0,
    'videoImage': None},
   {'asset_ID': 3,
    'assetName': 'Bulletins',
    'basePart': 'ALS295',
    'fileName': 'ST11237-Standard_Interactive_Buyers_Guide-WEB.pdf',
    'fileURL': 'http://eaccess.smpcorp.com/eCatalogs/Downloads/EMD/ST11237-Standard_Interactive_Buyers_Guide-WEB.pdf',
    'comment_ID': '260664',
    'comment': "Standard Interactive Buyer's Guide",
    'assetSort': 3,
    'digiSort': 0,
    'videoImage': None},
   {'asset_ID': 7,
    'assetName': 'Videos',
    'basePart': 'ALS295',
    'fileName': 'ABS Speed Sensor Replacement - Typical',
    'fileURL': 'https://youtube.com/embed/NGQK384mmTg',
    'comment_ID': '212334',
    'comment': 'ABS Speed Sensor Replacement - Typical',
    'assetSort': 7,
    'digiSort': 10330,
    'videoImage': None},
   {'asset_ID': 7,
    'assetName': 'Videos',
    'basePart': 'ALS295',
    'fileName': 'SMP Engineering Spotlight: Long Island City',
    'fileURL': 'https://youtube.com/embed/vac2vas7vJY',
    'comment_ID': '220958',
    'comment': 'SMP Engineering Spotlight: Long Island City',
    'assetSort': 7,
    'digiSort': 80000,
    'videoImage': None},
   {'asset_ID': 7,
    'assetName': 'Videos',
    'basePart': 'ALS295',
    'fileName': 'WIYB: Engineering Spotlight: Long Island City',
    'fileURL': 'https://youtube.com/embed/I-kWdiTPe08',
    'comment_ID': '291618',
    'comment': 'WIYB: Engineering Spotlight: Long Island City',
    'assetSort': 7,
    'digiSort': 80003,
    'videoImage': None},
   {'asset_ID': 7,
    'assetName': 'Videos',
    'basePart': 'ALS295',
    'fileName': 'SMP Engineering - Long Island City Facility Tour',
    'fileURL': 'https://youtube.com/embed/ut5LYbUFCKo',
    'comment_ID': '271219',
    'comment': 'SMP Engineering - Long Island City Facility Tour',
    'assetSort': 7,
    'digiSort': 80350,
    'videoImage': None},
   {'asset_ID': 7,
    'assetName': 'Videos',
    'basePart': 'ALS295',
    'fileName': 'Standard Interactive Buyers Guide',
    'fileURL': 'https://youtube.com/embed/mRzK11T9pxg',
    'comment_ID': '251346',
    'comment': 'Standard Interactive Buyers Guide',
    'assetSort': 7,
    'digiSort': 90030,
    'videoImage': None},
   {'asset_ID': 7,
    'assetName': 'Videos',
    'basePart': 'ALS295',
    'fileName': 'SMP Parts App Update (3.0.9)',
    'fileURL': 'https://youtube.com/embed/KpEXmjcKbMc',
    'comment_ID': '270593',
    'comment': 'SMP Parts App Update (3.0.9)',
    'assetSort': 7,
    'digiSort': 90090,
    'videoImage': None}],
  'categories': [{'basePart': 'ALS295',
    'webLayout_ID': 250,
    'categoryName_en': 'Sensor - ABS Speed',
    'prodCategory_ASort': 24710}],
  'crossRef': None,
  'completeRepair': {'serviceParts': [{'webBase': 'S2943',
     'brand': 'STI',
     'basePart': 'S2943',
     'partDesc_en': 'Electrical Connector',
     'partLongDesc_en': 'ABS Speed Sensor Connector',
     'rowId': 1}],
   'serviceSpec': [{'serviceName': 'Fuel Filter Flush (Required)'},
    {'serviceName': 'Oil Change (Required)'}]}}}

In [51]:
part_type = info['pp']['categories'][0]['categoryName_en']

part_type

'Sensor - ABS Speed'

In [52]:
pop = info['pd']['pop']

pop

'F'

In [53]:
pop = info['pd']['pop']

pop

'F'

In [54]:
per_car = info['pd']['qtyEach']

per_car

1

In [55]:
list_vehicle = [vehicle['buyersGuideDesc'] for vehicle in info['pp']['buyersGuides']]
vehicle = '\n'.join(list_vehicle)

vehicle

'Infiniti I30 (01-00)\nNissan Maxima (01-00)'

In [56]:
details = info['pp']['partSpecs']

details

[{'attributeCode': '110',
  'attributeValue': 1905,
  'attributeSort': 0,
  'attributeName_en': 'Warranty',
  'siteValue_en': '3 years/36,000 mile'},
 {'attributeCode': '388',
  'attributeValue': 1843,
  'attributeSort': 0,
  'attributeName_en': 'Number of Bolt Holes',
  'siteValue_en': '3'},
 {'attributeCode': '9',
  'attributeValue': 5959,
  'attributeSort': 10310,
  'attributeName_en': 'Connector Gender',
  'siteValue_en': 'Male (1)'},
 {'attributeCode': '160',
  'attributeValue': 249,
  'attributeSort': 10340,
  'attributeName_en': 'Connector Quantity',
  'siteValue_en': '1'},
 {'attributeCode': '171',
  'attributeValue': 6776,
  'attributeSort': 10350,
  'attributeName_en': 'Connector Shape',
  'siteValue_en': 'Rectangular'},
 {'attributeCode': '37',
  'attributeValue': 2167,
  'attributeSort': 10850,
  'attributeName_en': 'Harness Length - Inches',
  'siteValue_en': '34'},
 {'attributeCode': '38',
  'attributeValue': 8181,
  'attributeSort': 10860,
  'attributeName_en': 'Harness Length - mm',
  'siteValue_en': '867 mm'},
 {'attributeCode': '54',
  'attributeValue': 7842,
  'attributeSort': 11370,
  'attributeName_en': 'Mounting Location',
  'siteValue_en': 'Wheel'},
 {'attributeCode': '56',
  'attributeValue': 4879,
  'attributeSort': 11400,
  'attributeName_en': 'Mounting Type',
  'siteValue_en': 'Flange'},
 {'attributeCode': '104',
  'attributeValue': 4753,
  'attributeSort': 12380,
  'attributeName_en': 'Terminal Gender',
  'siteValue_en': 'Female (1)'},
 {'attributeCode': '164',
  'attributeValue': 1320,
  'attributeSort': 12390,
  'attributeName_en': 'Terminal Quantity',
  'siteValue_en': '2'},
 {'attributeCode': '105',
  'attributeValue': 3983,
  'attributeSort': 12400,
  'attributeName_en': 'Terminal Type',
  'siteValue_en': 'Blade'}]

In [57]:
brand = info['pd']['brand']

brand

'STI'

In [58]:
resp = requests.get('https://ecatalog.smpcorp.com/V2/STD/api/image/getallimages?partNum=' + list_part_number[i] + '&brand=' + brand + '&zoomFactor_sm=75&zoomFactor_md=360&zoomFactor_bg=960').text
info = json.loads(resp)

info

[{'image_Name': 'DQw6Cl7kkREdTfsVJnjD%2Fg%3D%3D',
  'image_SM_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=+POEp/4gcJ+la+G8t3vSaPOA3FM8wSUCfEFLjhl+yY51Wji2BTIoaGvC9jZhQ8JlNuh91g7gmM/55URlMOW+XVqOzvag35n6IYODDVJXQ/5aAUVD7HPvINfMHmFkfTlA8D+msAMmvX2CZuqvooaa7DCB6ftZHycUS1qHVwGWXkIr+m7fx4OW9NZDtUzqjDntuQM5+ganXCoaNE3YLkDIPexDDtSObvr3',
  'image_MD_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=+POEp/4gcJ+la+G8t3vSaPOA3FM8wSUCqYrcgaXQHScWSaSu79Q7PQd0sqFgnuyfYvfY+sUXOOXlUiMf62iPubgwXLHE9txgJv0YyvK/rWecX6DmzjK5LAPGgnfAzoJeeiNuk1H1nIsgiEVPfC+WFBiIabLNN0Hoqeu5hZlCRfM7DcAIwETg010LvBQdcLIGIuVjQ+jvHmZkmGleZsu4Wg==',
  'image_BG_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=+POEp/4gcJ+la+G8t3vSaPOA3FM8wSUCTuE74rL23eQ1LdhgJc0sRtra6bfLxRybnRaSzC3dZmboEyZGCTZQXGS/yUkBUvThK0HZgA1C4AGxzJCtT0EC3h5PFeAkVcMYsJ9MXbl4u4qQsP+xaLsnCfi8uaNCstSIH/vcGamvfKp6nFOvXH2vSS5cUvcicyc/5V1o6fLSErOYkCUjotx4/w=='},
 {'image_Name': 'DQw6Cl7kkRF6NLJMaokDKA%3D%3D',
  'image_SM_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=+POEp/4gcJ+la+G8t3vSaPOA3FM8wSUCfEFLjhl+yY51Wji2BTIoaGvC9jZhQ8JlsxchFsjiz+L55URlMOW+XVqOzvag35n6IYODDVJXQ/5aAUVD7HPvINfMHmFkfTlA8D+msAMmvX2CZuqvooaa7DCB6ftZHycUS1qHVwGWXkIr+m7fx4OW9NZDtUzqjDntuQM5+ganXCoaNE3YLkDIPexDDtSObvr3',
  'image_MD_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=+POEp/4gcJ+la+G8t3vSaPOA3FM8wSUCqYrcgaXQHScWSaSu79Q7PQd0sqFgnuyfjsQEhs3D4i/lUiMf62iPubgwXLHE9txgJv0YyvK/rWecX6DmzjK5LAPGgnfAzoJeeiNuk1H1nIsgiEVPfC+WFBiIabLNN0Hoqeu5hZlCRfM7DcAIwETg010LvBQdcLIGIuVjQ+jvHmZkmGleZsu4Wg==',
  'image_BG_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=+POEp/4gcJ+la+G8t3vSaPOA3FM8wSUCTuE74rL23eQ1LdhgJc0sRv37J/hN+8R9nRaSzC3dZmboEyZGCTZQXGS/yUkBUvThK0HZgA1C4AGxzJCtT0EC3h5PFeAkVcMYsJ9MXbl4u4qQsP+xaLsnCfi8uaNCstSIH/vcGamvfKp6nFOvXH2vSS5cUvcicyc/5V1o6fLSErOYkCUjotx4/w=='},
 {'image_Name': 'DQw6Cl7kkRFl6etEOLj07w%3D%3D',
  'image_SM_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=+POEp/4gcJ+la+G8t3vSaPOA3FM8wSUCfEFLjhl+yY51Wji2BTIoaGvC9jZhQ8JlCMz0nsr3iej55URlMOW+XVqOzvag35n6IYODDVJXQ/5aAUVD7HPvINfMHmFkfTlA8D+msAMmvX2CZuqvooaa7DCB6ftZHycUS1qHVwGWXkIr+m7fx4OW9NZDtUzqjDntuQM5+ganXCoaNE3YLkDIPexDDtSObvr3',
  'image_MD_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=+POEp/4gcJ+la+G8t3vSaPOA3FM8wSUCqYrcgaXQHScWSaSu79Q7PQd0sqFgnuyffkYFZhxtARnlUiMf62iPubgwXLHE9txgJv0YyvK/rWecX6DmzjK5LAPGgnfAzoJeeiNuk1H1nIsgiEVPfC+WFBiIabLNN0Hoqeu5hZlCRfM7DcAIwETg010LvBQdcLIGIuVjQ+jvHmZkmGleZsu4Wg==',
  'image_BG_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=+POEp/4gcJ+la+G8t3vSaPOA3FM8wSUCTuE74rL23eQ1LdhgJc0sRs3skRQ/C9W5nRaSzC3dZmboEyZGCTZQXGS/yUkBUvThK0HZgA1C4AGxzJCtT0EC3h5PFeAkVcMYsJ9MXbl4u4qQsP+xaLsnCfi8uaNCstSIH/vcGamvfKp6nFOvXH2vSS5cUvcicyc/5V1o6fLSErOYkCUjotx4/w=='}]

In [59]:
if len(info) == 0:
    src = ''
else:
    src = info[0]['image_BG_Url']

src

'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=+POEp/4gcJ+la+G8t3vSaPOA3FM8wSUCTuE74rL23eQ1LdhgJc0sRtra6bfLxRybnRaSzC3dZmboEyZGCTZQXGS/yUkBUvThK0HZgA1C4AGxzJCtT0EC3h5PFeAkVcMYsJ9MXbl4u4qQsP+xaLsnCfi8uaNCstSIH/vcGamvfKp6nFOvXH2vSS5cUvcicyc/5V1o6fLSErOYkCUjotx4/w=='

In [60]:
df_temp = pd.DataFrame([{'Part_Number': list_part_number[i],
                         'Part_Type': part_type,
                         'POP': pop,
                         'Per_Car': per_car,
                         'Vehicle': vehicle,
                         'Src': src,
                         'status': 'ok'}])

df_temp

,Part_Number,Part_Type,POP,Per_Car,Vehicle,Src,status
0,ALS295,Sensor - ABS Speed,F,1,Infiniti I30 (01-00)\nNissan Maxima (01-00),https://extapi.smpcorp.com/ihgs/imagehandlergs...,ok

In [61]:

for name_value in details:
    df_temp[name_value['attributeName_en'].lower()] = name_value['siteValue_en']
    
df = pd.concat([df, df_temp], ignore_index=True).fillna('')

df

,Part_Number,Part_Type,POP,Per_Car,Vehicle,Src,status,warranty,number of bolt holes,connector gender,connector quantity,connector shape,harness length - inches,harness length - mm,mounting location,mounting type,terminal gender,terminal quantity,terminal type
0,ALS295,Sensor - ABS Speed,F,1,Infiniti I30 (01-00)\nNissan Maxima (01-00),https://extapi.smpcorp.com/ihgs/imagehandlergs...,ok,"3 years/36,000 mile",3,Male (1),1,Rectangular,34,867 mm,Wheel,Flange,Female (1),2,Blade