In [1]:
import pandas as pd
import random
from selenium.webdriver import ChromeOptions
import time
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver import Chrome
from selenium.webdriver.chrome.service import Service


list_user_agent = ['Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.90 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.16 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.5672.63 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.5672.24 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.5615.49 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.5615.28 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5563.64 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5563.41 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5563.19 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.5481.77 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.5481.30 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.74 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.25 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.71 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.22 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.5304.62 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.5304.18 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.5249.61 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.5249.21 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.5195.52 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.5195.19 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.79 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.29 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.20 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.24 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.27 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.15 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.20 Safari/537.36']

In [63]:
import pandas as pd
df_menu = pd.read_excel(r'C:\Users\YangTeng\Desktop\数据来源\05、STANDARD\STANDARD_menu.xlsx', header=0)
list_part_number = df_menu['Part_Number'].to_list()

print('总数量：' + str(len(list_part_number)))
list_part_number

list_url = []

for j in range(len(list_part_number)):
    url = 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/'+list_part_number[j]
    list_url.append(url)
print('总数量：' + str(len(list_url)))
list_url

总数量：768
总数量：768

['https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS295',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS296',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS297',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS298',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS299',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS300',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS302',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS303',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS305',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS306',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS307',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS308',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS309',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS310',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS312',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS314',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS316',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS321',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS325',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS327',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS328',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS329',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS330',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS331',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS333',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS335',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS339',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS341',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS342',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS343',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS344',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS345',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS346',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS347',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS348',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS349',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS350',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS351',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS355',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS358',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS359',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS360',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS363',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS364',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS365',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS366',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS367',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS368',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS369',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS370',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS371',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS372',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS373',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS374',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS375',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS376',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS377',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS378',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS379',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS380',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS381',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS382',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS383',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS384',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS385',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS386',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS387',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS388',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS389',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS390',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS391',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS392',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS393',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS394',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS395',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS396',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS397',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS398',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS399',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS400',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS401',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS402',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS403',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS404',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS405',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS406',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS407',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS408',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS410',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS411',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS412',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS413',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS414',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS415',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS416',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS417',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS418',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS419',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS420',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS421',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS423',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS424',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS425',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS426',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS427',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS428',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS429',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS430',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS430T',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS431',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS432',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS433',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS434',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS435',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS436',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS437',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS438',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS439',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS440',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS441',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS442',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS443',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS444',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS445',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS446',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS447',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS448',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS449',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS450',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS451',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS452',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS453',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS454',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS455',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS457',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS458',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS459',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS461',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS462',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS463',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS464',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS465',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS466',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS467',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS467T',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS468',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS468T',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS469',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS469T',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS470',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS471',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS472',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS473',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS474',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS475',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS476',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS477',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS478',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS479',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS480',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS481',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS482',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS482T',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS483',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS483T',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS484',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS485',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS486',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS487',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS488',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS489',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS491',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS494',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS495',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS496',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS497',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS498',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS499',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS501',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS503',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS504',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS505',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS505T',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS506',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS508',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS509',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS510',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS511',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS512',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS513',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS514',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS515',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS516',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS517',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS518',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS520',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS521',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS522',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS523',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS524',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS525',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS526',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS527',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS528',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS529',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS530',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS532',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS533',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS535',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS537',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS538',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS539',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS540',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS541',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS542',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS543',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS544',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS545',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS546',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS547',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS548',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS549',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS550',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS551',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS552',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS553',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS554',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS555',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS559',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS560',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS561',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS562',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS563',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS564',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS565',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS566',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS567',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS568',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS569',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS570',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS571',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS572',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS573',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS574',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS575',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS576',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS578',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS579',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS580',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS581',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS582',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS583',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS584',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS585',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS586',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS587',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS588',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS589',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS590',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS591',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS592',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS593',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS594',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS595',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS596',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS597',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS598',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS599',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS600',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS601',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS602',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS603',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS605',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS606',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS607',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS608',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS609',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS610',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS611',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS612',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS613',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS614',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS615',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS616',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS617',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS618',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS619',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS620',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS621',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS622',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS623',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS624',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS625',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS626',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS627',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS628',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS629',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS630',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS631',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS633',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS634',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS635',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS636',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS637',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS638',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS639',
 'https://ecatalog.smpcorp.com/V2/STD/#/partdetail/part/ALS640',

In [72]:
df = pd.DataFrame(columns=['Part_Number',
                           'Part_Type',
                           'Vehicle',
                           'status'])

df

Empty DataFrame
Columns: [Part_Number, Part_Type, Vehicle, status]
Index: []

In [73]:
option = ChromeOptions()
option.add_experimental_option('useAutomationExtension', False)
option.add_argument('blink-settings=imagesEnabled=false')
option.add_argument('--disable-blink-features=AutomationControlled')
option.add_argument('--disable-dev-shm-usage')
option.add_argument('--disable-gpu')
option.add_experimental_option('excludeSwitches', ['enable-automation'])
# option.add_argument('--headless')
option.add_argument('--no-sandbox')
option.add_argument('--proxy-server=http://u431.kdltps.com:15818')
option.add_argument('user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36')
option.page_load_strategy = 'eager'

browser = Chrome(service=Service(r'C:\Users\YangTeng\Desktop\venv\chromedriver'), options=option)

browser.maximize_window()

In [74]:
i=2


browser.get(list_url[i])

time.sleep(5)

wait = WebDriverWait(browser, 60)
wait.until(EC.presence_of_element_located((By.XPATH, '//div[@class="toggle_container_pt"]/ul/li')))

In [75]:
# df_temp = pd.DataFrame(columns=['Part_Number',
#                            'Part_Type',
#                            'Vehicle',
#                            'status'])

In [79]:
Part_Type = browser.find_element(by=By.XPATH, value='//div[@class="toggle_container_pt"]/ul/li').text
Part_Type

'Sensor - ABS Speed'

In [80]:
Vehicle = browser.find_element(by=By.XPATH, value='//div[@class="toggle_container_bg divBg"]/ul').text
Vehicle

'Infiniti I30 (99-97)\nNissan Maxima (99-97)'

In [81]:
df_temp = pd.DataFrame([{'Part_Number':list_part_number[i],
                           'Part_Type':Part_Type,
                           'Vehicle':Vehicle,
                           'status':'ok'}])
df_temp

,Part_Number,Part_Type,Vehicle,status
0,ALS297,Sensor - ABS Speed,Infiniti I30 (99-97)\nNissan Maxima (99-97),ok

In [69]:
index = browser.find_element(by=By.XPATH, value='//a[@title="Show All Part Specifications"]')

index.click()

list_name = [name.text for name in browser.find_elements(by=By.XPATH, value='//div[@class="spec-group"]/ul/li/span[1]')]

list_value = [value.text for value in browser.find_elements(by=By.XPATH, value='//div[@class="spec-group"]/ul/li/span[2]')]

for name, value in zip(list_name, list_value):
    df_temp[name.lower()] = value

In [70]:
df_temp

,Part_Number,Part_Type,Vehicle,status,warranty:,number of bolt holes:,connector gender:,connector quantity:,connector shape:,harness length - inches:,harness length - mm:,mounting location:,terminal gender:,terminal quantity:,terminal type:
0,ALS297,Sensor - ABS Speed,Infiniti I30 (99-97)\nNissan Maxima (99-97),ok,"3 years/36,000 mile",1,Female (1),1,Square,32,812.8 mm,Wheel,Male (1),2,Pin

In [71]:
df = pd.concat([df, df_temp], ignore_index=True).fillna('')

df

,Part_Number,Part_Type,Vehicle,status,warranty:,number of bolt holes:,connector gender:,connector quantity:,connector shape:,harness length - inches:,harness length - mm:,mounting location:,terminal gender:,terminal quantity:,terminal type:
0,ALS297,Sensor - ABS Speed,Infiniti I30 (99-97)\nNissan Maxima (99-97),ok,"3 years/36,000 mile",1,Female (1),1,Square,32,812.8 mm,Wheel,Male (1),2,Pin