In [1]:
referer = 'https://www.ebay.com/sch/i.html?_dkr=1&iconV2Request=true&_blrs=recall_filtering&_ssn=boostprojects&store_name=boostprojects&_oac=1&_nkw=intercooler&_sop=16'

list_user_agent = ['Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.90 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.16 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.5672.63 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.5672.24 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.5615.49 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.5615.28 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5563.64 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5563.41 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5563.19 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.5481.77 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.5481.30 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.74 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.25 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.71 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.22 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.5304.62 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.5304.18 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.5249.61 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.5249.21 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.5195.52 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.5195.19 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.79 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.29 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.20 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.24 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.27 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.15 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.20 Safari/537.36']
import pandas as pd
df_menu = pd.read_excel(r'C:/Users/YangTeng/Desktop/menu_J.xlsx', header=0)
list_url = df_menu['Url'].to_list()

print('总数量：' + str(len(list_url)))
list_url

总数量：5210

['https://www.ebay.com/itm/373651381733?epid=20018744991&hash=item56ff5b9de5%3Ag%3A%7EWgAAOSwLghksHjq&LH_BIN=1',
 'https://www.ebay.com/itm/372749825457?hash=item56c99ef5b1%3Ag%3AugQAAOSwF5VksbNW&LH_BIN=1',
 'https://www.ebay.com/itm/352852280880?epid=22021265030&hash=item5227a28630%3Ag%3AdfMAAOSwgDlkuamH&LH_BIN=1',
 'https://www.ebay.com/itm/371671143501?epid=28018749698&hash=item568953944d%3Ag%3AJFYAAOSwEsBkuKQn&LH_BIN=1',
 'https://www.ebay.com/itm/231811140279?hash=item35f9054ab7%3Ag%3A-icAAOSw81hkuGTK&LH_BIN=1',
 'https://www.ebay.com/itm/372607254605?hash=item56c11f804d%3Ag%3AiRAAAOSwefJkubuj&LH_BIN=1',
 'https://www.ebay.com/itm/354863824088?hash=item529f883cd8%3Ag%3Ae9UAAOSw6iJkubg5&LH_BIN=1',
 'https://www.ebay.com/itm/234724594860?epid=10021401012&hash=item36a6ad14ac%3Ag%3Azv4AAOSwWGlkuVbp&LH_BIN=1',
 'https://www.ebay.com/itm/373603471564?epid=21024326851&hash=item56fc8090cc%3Ag%3AbMoAAOSw7Dhkn9nL&LH_BIN=1',
 'https://www.ebay.com/itm/231999231771?hash=item36043b571b%3Ag%3ANA4AAOSwWHtkuSAp&LH_BIN=1',
 'https://www.ebay.com/itm/351591859793?hash=item51dc820651%3Ag%3AQBwAAOSwQapkuVxq&LH_BIN=1',
 'https://www.ebay.com/itm/373603456794?epid=17018746264&hash=item56fc80571a%3Ag%3AlDsAAOSwaHRkuLAK&LH_BIN=1',
 'https://www.ebay.com/itm/234524726177?hash=item369ac353a1%3Ag%3AtZMAAOSwm4xkr-Uf&LH_BIN=1',
 'https://www.ebay.com/itm/374040164887?hash=item571687fa17%3Ag%3AKcwAAOSwa8hksB79&LH_BIN=1',
 'https://www.ebay.com/itm/231998752345?hash=item3604340659%3Ag%3A2g8AAOSwvZ1knvrc&LH_BIN=1',
 'https://www.ebay.com/itm/232998814725?epid=12018737046&hash=item363fcfc405%3Ag%3AEd0AAOSwIIRknxP7&LH_BIN=1',
 'https://www.ebay.com/itm/353576959375?hash=item5252d43d8f%3Ag%3AtrwAAOSw5v5koAyo&LH_BIN=1',
 'https://www.ebay.com/itm/373651422336?hash=item56ff5c3c80%3Ag%3Asr0AAOSwhTVkuYe1&LH_BIN=1',
 'https://www.ebay.com/itm/373652586576?epid=24018737370&hash=item56ff6e0050%3Ag%3AeIYAAOSwrYpkuLRU&LH_BIN=1',
 'https://www.ebay.com/itm/235055845742?hash=item36ba6b916e%3Ag%3AGuQAAOSw-oNksElh&LH_BIN=1',
 'https://www.ebay.com/itm/374763041141?hash=item57419e3175%3Ag%3AVhMAAOSwKjtksH9A&LH_BIN=1',
 'https://www.ebay.com/itm/353244176405?epid=13044071621&hash=item523efe6015%3Ag%3Ai54AAOSwuOZkuWkK&LH_BIN=1',
 'https://www.ebay.com/itm/371713349375?hash=item568bd796ff%3Ag%3A88AAAOSwP19ksaqI&LH_BIN=1',
 'https://www.ebay.com/itm/373651450430?hash=item56ff5caa3e%3Ag%3Alc4AAOSwQ-NkucBb&LH_BIN=1',
 'https://www.ebay.com/itm/372563364968?epid=19018748837&hash=item56be81cc68%3Ag%3Aw7kAAOSwKV5kn3Dg&LH_BIN=1',
 'https://www.ebay.com/itm/354852956813?hash=item529ee26a8d%3Ag%3Am50AAOSwukhkubgB&LH_BIN=1',
 'https://www.ebay.com/itm/373652531695?epid=11018743723&hash=item56ff6d29ef%3Ag%3AZkYAAOSwWbtksByh&LH_BIN=1',
 'https://www.ebay.com/itm/373652531848?epid=21018749700&hash=item56ff6d2a88%3Ag%3AVUUAAOSwLnNksB2E&LH_BIN=1',
 'https://www.ebay.com/itm/231998639555?hash=item3604324dc3%3Ag%3Acz0AAOSwNQJkuGeR&LH_BIN=1',
 'https://www.ebay.com/itm/233360502330?hash=item36555eae3a%3Ag%3AWxMAAOSwPBRkuHRu&LH_BIN=1',
 'https://www.ebay.com/itm/353578674047?hash=item5252ee677f%3Ag%3AbfUAAOSwWkVksGEC&LH_BIN=1',
 'https://www.ebay.com/itm/233069634778?hash=item36440864da%3Ag%3A6p0AAOSwTFRkr9mA&LH_BIN=1',
 'https://www.ebay.com/itm/353522057824?epid=6016706203&hash=item524f8e8260%3Ag%3AIQAAAOSw0Ahkn7sj&LH_BIN=1',
 'https://www.ebay.com/itm/353578695397?epid=7016711075&hash=item5252eebae5%3Ag%3AlHMAAOSw0olkn8Rb&LH_BIN=1',
 'https://www.ebay.com/itm/234041063480?hash=item367def3838%3Ag%3A4yYAAOSwa8hkpjE1&LH_BIN=1',
 'https://www.ebay.com/itm/354774422203?hash=item529a3412bb%3Ag%3A6N8AAOSwXqxkubY1&LH_BIN=1',
 'https://www.ebay.com/itm/374759018638?hash=item574160d08e%3Ag%3AneMAAOSw3G5kucnD&LH_BIN=1',
 'https://www.ebay.com/itm/234039534691?epid=3018752306&hash=item367dd7e463%3Ag%3AhNQAAOSwc-Nknzad&LH_BIN=1',
 'https://www.ebay.com/itm/234041045078?epid=16018744352&hash=item367deef056%3Ag%3AOkUAAOSwkWpknz8u&LH_BIN=1',
 'https://www.ebay.com/itm/351814360939?epid=11018743120&hash=item51e9c51f6b%3Ag%3Ar%7EEAAOSwQz9kuV3D&LH_BIN=1',
 'https://www.ebay.com/itm/351814360979?hash=item51e9c51f93%3Ag%3A78EAAOSwJFBkuV2w&LH_BIN=1',
 'https://www.ebay.com/itm/351773312632?hash=item51e752c678%3Ag%3Azs8AAOSwIstkuV1J&LH_BIN=1',
 'https://www.ebay.com/itm/351773304629?hash=item51e752a735%3Ag%3AopMAAOSwKVpkuVwC&LH_BIN=1',
 'https://www.ebay.com/itm/372543984610?hash=item56bd5a13e2%3Ag%3AB1cAAOSwqD5ksa7o&LH_BIN=1',
 'https://www.ebay.com/itm/372560205984?epid=16018744362&hash=item56be5198a0%3Ag%3A7xsAAOSw9XRkn3Ap&LH_BIN=1',
 'https://www.ebay.com/itm/231997911534?hash=item36042731ee%3Ag%3ABcwAAOSwl79kuSJC&LH_BIN=1',
 'https://www.ebay.com/itm/373604507078?hash=item56fc905dc6%3Ag%3A%7EtoAAOSwjmZkub70&LH_BIN=1',
 'https://www.ebay.com/itm/373652593250?hash=item56ff6e1a62%3Ag%3AZAkAAOSwpnFkuYi3&LH_BIN=1',
 'https://www.ebay.com/itm/351772588338?hash=item51e747b932%3Ag%3AiFkAAOSwVB1kn1DU&LH_BIN=1',
 'https://www.ebay.com/itm/231998046113?epid=22018748883&hash=item3604293fa1%3Ag%3A1o8AAOSwymJknvbH&LH_BIN=1',
 'https://www.ebay.com/itm/234572133213?hash=item369d96b35d%3Ag%3AWHgAAOSwg8dkn5My&LH_BIN=1',
 'https://www.ebay.com/itm/353587242103?hash=item5253712477%3Ag%3AxnkAAOSwFFRkua6t&LH_BIN=1',
 'https://www.ebay.com/itm/352149179093?hash=item51fdba0ad5%3Ag%3A0OMAAOSw6upkoACp&LH_BIN=1',
 'https://www.ebay.com/itm/353578697934?hash=item5252eec4ce%3Ag%3AJj4AAOSwm9Nkpk31&LH_BIN=1',
 'https://www.ebay.com/itm/372544066078?hash=item56bd5b521e%3Ag%3An6MAAOSwS8dkpmcT&LH_BIN=1',
 'https://www.ebay.com/itm/372564353851?hash=item56be90e33b%3Ag%3AkRMAAOSwrZNkuX9d&LH_BIN=1',
 'https://www.ebay.com/itm/374702048862?hash=item573dfb865e%3Ag%3AdQAAAOSwGf5kuch6&LH_BIN=1',
 'https://www.ebay.com/itm/351003080788?hash=item51b969f854%3Ag%3AXeEAAOSwIQRkuVug&LH_BIN=1',
 'https://www.ebay.com/itm/351002654837?epid=1379691093&hash=item51b9637875%3Ag%3Ag9QAAOSwgmBkuVq4&LH_BIN=1',
 'https://www.ebay.com/itm/373603461426?hash=item56fc806932%3Ag%3A2qgAAOSw1C9kn9my&LH_BIN=1',
 'https://www.ebay.com/itm/353578635088?hash=item5252edcf50%3Ag%3AztcAAOSwNM9kn8Hg&LH_BIN=1',
 'https://www.ebay.com/itm/353522042566?hash=item524f8e46c6%3Ag%3AsiEAAOSwsY5kpklV&LH_BIN=1',
 'https://www.ebay.com/itm/353523587025?epid=3018752955&hash=item524fa5d7d1%3Ag%3AMPQAAOSw-iBkpkof&LH_BIN=1',
 'https://www.ebay.com/itm/352553591878?hash=item5215d4e446%3Ag%3AaGMAAOSwUB9kpkOh&LH_BIN=1',
 'https://www.ebay.com/itm/234999228024?hash=item36b70ba678%3Ag%3ArncAAOSwU3tkuaKQ&LH_BIN=1',
 'https://www.ebay.com/itm/351788128556?hash=item51e834d92c%3Ag%3AgDMAAOSwZgdkuV21&LH_BIN=1',
 'https://www.ebay.com/itm/354671007557?hash=item52940a1745%3Ag%3AiOMAAOSw8zhkplkg&LH_BIN=1',
 'https://www.ebay.com/itm/374582560351?hash=item5736dc465f%3Ag%3A2WYAAOSwwXdkpnPl&LH_BIN=1',
 'https://www.ebay.com/itm/371671049575?hash=item5689522567%3Ag%3A0WAAAOSw7DZkoBuv&LH_BIN=1',
 'https://www.ebay.com/itm/351772958804?hash=item51e74d6054%3Ag%3AdC8AAOSwB39kn1EG&LH_BIN=1',
 'https://www.ebay.com/itm/352511578687?hash=item521353d23f%3Ag%3AaE8AAOSwZNJksFA4&LH_BIN=1',
 'https://www.ebay.com/itm/373652558362?hash=item56ff6d921a%3Ag%3AK4wAAOSwqo5kn3pW&LH_BIN=1',
 'https://www.ebay.com/itm/353577031252?hash=item5252d55654%3Ag%3AvRgAAOSw1FpkuJmG&LH_BIN=1',
 'https://www.ebay.com/itm/231848264689?epid=9021252864&hash=item35fb3bc3f1%3Ag%3A%7EwUAAOSwPatkuGV7&LH_BIN=1',
 'https://www.ebay.com/itm/354858848456?hash=item529f3c50c8%3Ag%3AkTQAAOSwZNJksGdD&LH_BIN=1',
 'https://www.ebay.com/itm/374759013747?hash=item574160bd73%3Ag%3AxtQAAOSwdkdkuclJ&LH_BIN=1',
 'https://www.ebay.com/itm/372003028352?hash=item569d1bbd80%3Ag%3AFIsAAOSw7URkuXkE&LH_BIN=1',
 'https://www.ebay.com/itm/352592109154?hash=item5218209e62%3Ag%3Ai2kAAOSwuuZkpkYf&LH_BIN=1',
 'https://www.ebay.com/itm/234092963197?hash=item368107257d%3Ag%3AwUoAAOSwos5kpjNn&LH_BIN=1',
 'https://www.ebay.com/itm/234041076207?hash=item367def69ef%3Ag%3ArnAAAOSwM-Rkn41a&LH_BIN=1',
 'https://www.ebay.com/itm/373652579369?hash=item56ff6de429%3Ag%3ACjIAAOSwWepkn93t&LH_BIN=1',
 'https://www.ebay.com/itm/351002727662?hash=item51b96494ee%3Ag%3AVsYAAOSwTF1kuVqQ&LH_BIN=1',
 'https://www.ebay.com/itm/352363261141?hash=item520a7cacd5%3Ag%3AxdwAAOSwvMNkuV%7ER&LH_BIN=1',
 'https://www.ebay.com/itm/372544000601?epid=1879761910&hash=item56bd5a5259%3Ag%3AzFwAAOSwfUlkpmeP&LH_BIN=1',
 'https://www.ebay.com/itm/353594459413?hash=item5253df4515%3Ag%3AC4AAAOSwzKpkpk5W&LH_BIN=1',
 'https://www.ebay.com/itm/352493177761?hash=item52123b0ba1%3Ag%3AaToAAOSwsL5kpkMG&LH_BIN=1',
 'https://www.ebay.com/itm/373651381675?hash=item56ff5b9dab%3Ag%3AA6EAAOSwO3tkpm3R&LH_BIN=1',
 'https://www.ebay.com/itm/373651381780?hash=item56ff5b9e14%3Ag%3A-uYAAOSw5Utkpm3T&LH_BIN=1',
 'https://www.ebay.com/itm/354774422782?hash=item529a3414fe%3Ag%3A8bgAAOSwolJkubVt&LH_BIN=1',
 'https://www.ebay.com/itm/352742591848?hash=item522118cd68%3Ag%3A9-IAAOSw3yNkpkYM&LH_BIN=1',
 'https://www.ebay.com/itm/234093019539?hash=item3681080193%3Ag%3AzrEAAOSwhLVkpjSW&LH_BIN=1',
 'https://www.ebay.com/itm/235055863492?hash=item36ba6bd6c4%3Ag%3AEjUAAOSw%7E-VkuVmN&LH_BIN=1',
 'https://www.ebay.com/itm/371688379611?epid=1378412039&hash=item568a5a94db%3Ag%3A59kAAOSw1KJkpmLs&LH_BIN=1',
 'https://www.ebay.com/itm/352511582702?hash=item521353e1ee%3Ag%3Aoc4AAOSwVY9kpkM2&LH_BIN=1',
 'https://www.ebay.com/itm/233000180561?epid=27018742485&hash=item363fe49b51%3Ag%3A67UAAOSwHCBkpioD&LH_BIN=1',
 'https://www.ebay.com/itm/234483728299?hash=item369851bfab%3Ag%3AQ7MAAOSw5ORkpja1&LH_BIN=1',
 'https://www.ebay.com/itm/373994489163?hash=item5713cf054b%3Ag%3A5wMAAOSw6HlkpnDk&LH_BIN=1',
 'https://www.ebay.com/itm/235052255447?hash=item36ba34c8d7%3Ag%3A9C4AAOSwGTpkuaWC&LH_BIN=1',
 'https://www.ebay.com/itm/353522042616?hash=item524f8e46f8%3Am%3AmISpb_aadeX872j1mENaXRQ&LH_BIN=1',
 'https://www.ebay.com/itm/353523587032?hash=item524fa5d7d8%3Ag%3AZacAAOSwwXdkn72K&LH_BIN=1',
 'https://www.ebay.com/itm/372560182115?hash=item56be513b63%3Ag%3A2pkAAOSwuQNksHDP&LH_BIN=1',
 'https://www.ebay.com/itm/233315331737?hash=item3652ad6e99%3Ag%3A4-UAAOSwsVpksDrx&LH_BIN=1',
 'https://www.ebay.com/itm/231999627246?epid=13045141778&hash=item3604415fee%3Ag%3Aos8AAOSwAvhkn-bN&LH_BIN=1',
 'https://www.ebay.com/itm/235052248820?hash=item36ba34aef4%3Ag%3AdmcAAOSwD81kuaTn&LH_BIN=1',
 'https://www.ebay.com/itm/373604504369?hash=item56fc905331%3Ag%3AQk0AAOSwvjdkub5c&LH_BIN=1',
 'https://www.ebay.com/itm/352553563621?epid=7016334290&hash=item5215d475e5%3Ag%3AQZsAAOSwZfZkn7DK&LH_BIN=1',
 'https://www.ebay.com/itm/353578673828?epid=9018735497&hash=item5252ee66a4%3Ag%3Ae8AAAOSwYrpkn8PX&LH_BIN=1',
 'https://www.ebay.com/itm/374678447289?hash=item573c9364b9%3Ag%3AzSoAAOSwa8VkucfM&LH_BIN=1',
 'https://www.ebay.com/itm/374678448393?hash=item573c936909%3Ag%3AxPMAAOSwoJ5kuceF&LH_BIN=1',
 'https://www.ebay.com/itm/354774422787?hash=item529a341503%3Ag%3AquUAAOSwgglkubYO&LH_BIN=1',
 'https://www.ebay.com/itm/234478418069?hash=item369800b895%3Ag%3A3iYAAOSwqUZkpjco&LH_BIN=1',
 'https://www.ebay.com/itm/233330653024?epid=5018749215&hash=item3653973760%3Ag%3A2fIAAOSwg2Rkpi31&LH_BIN=1',
 'https://www.ebay.com/itm/354223415486?hash=item52795c60be%3Ag%3Ayb4AAOSwcYtkn8iF&LH_BIN=1',
 'https://www.ebay.com/itm/233104782606?hash=item364620b50e%3Ag%3ABPEAAOSwsgRkpizY&LH_BIN=1',
 'https://www.ebay.com/itm/351002212773?epid=1479708998&hash=item51b95cb9a5%3Ag%3AlosAAOSwsZ5kuVp5&LH_BIN=1',
 'https://www.ebay.com/itm/231999409345?hash=item36043e0cc1%3Ag%3AxKcAAOSwFDBkpifn&LH_BIN=1',
 'https://www.ebay.com/itm/354763669459?epid=17018746041&hash=item52998fffd3%3Ag%3ApxQAAOSwZRBkpltX&LH_BIN=1',
 'https://www.ebay.com/itm/374678460527?hash=item573c93986f%3Ag%3AEIMAAOSwEeJkpnSE&LH_BIN=1',
 'https://www.ebay.com/itm/233000176377?hash=item363fe48af9%3Ag%3ACiwAAOSwbs9kuG4i&LH_BIN=1',
 'https://www.ebay.com/itm/233047971767?hash=item3642bdd7b7%3Ag%3AsvAAAOSwxkdkpipd&LH_BIN=1',
 'https://www.ebay.com/itm/231848316272?hash=item35fb3c8d70%3Ag%3AjnoAAOSwrx1kuGWM&LH_BIN=1',
 'https://www.ebay.com/itm/354763668961?epid=0&hash=item52998ffde1%3Ag%3AZYYAAOSwKf1kubYB&LH_BIN=1',
 'https://www.ebay.com/itm/234999237400?hash=item36b70bcb18%3Ag%3ASu8AAOSwTvlkuaKF&LH_BIN=1',
 'https://www.ebay.com/itm/374113687250?hash=item571ae9d6d2%3Ag%3AVSMAAOSwih1kn-ED&LH_BIN=1',
 'https://www.ebay.com/itm/372497636707?hash=item56ba96dd63%3Ag%3APiMAAOSwQulkn9I2&LH_BIN=1',
 'https://www.ebay.com/itm/373603456631?epid=15018746827&hash=item56fc805677%3Ag%3AHt8AAOSwtthksBtD&LH_BIN=1',
 'https://www.ebay.com/itm/372562525840?hash=item56be74fe90%3Ag%3AzLsAAOSwkcZkn9O2&LH_BIN=1',
 'https://www.ebay.com/itm/372341744327?hash=item56b14c22c7%3Ag%3AlpIAAOSwaPBkuKo1&LH_BIN=1',
 'https://www.ebay.com/itm/233061497854?hash=item36438c3bfe%3Ag%3A7wMAAOSw2fdkuG2O&LH_BIN=1',
 'https://www.ebay.com/itm/234214694093?hash=item3688489ccd%3Ag%3AnuUAAOSwaHRkuVSr&LH_BIN=1',
 'https://www.ebay.com/itm/372742155661?hash=item56c929ed8d%3Ag%3A%7EVcAAOSwOopkuK6r&LH_BIN=1',
 'https://www.ebay.com/itm/353522032470?hash=item524f8e1f56%3Ag%3ArbIAAOSwGk1kr%7E2O&LH_BIN=1',
 'https://www.ebay.com/itm/233329634477?hash=item365387acad%3Ag%3A-fMAAOSwNyNkuUoJ&LH_BIN=1',
 'https://www.ebay.com/itm/374688163680?hash=item573d27a760%3Ag%3A984AAOSwhy5kucfl&LH_BIN=1',
 'https://www.ebay.com/itm/352555083338?hash=item5215eba64a%3Ag%3AHRcAAOSwsmZkn1a-&LH_BIN=1',
 'https://www.ebay.com/itm/352482087114?hash=item521191d0ca%3Ag%3AsBwAAOSwEatkpkJk&LH_BIN=1',
 'https://www.ebay.com/itm/373604487813?epid=9018735403&hash=item56fc901285%3Ag%3AazYAAOSwvZ1kpmyM&LH_BIN=1',
 'https://www.ebay.com/itm/373604487867?epid=17018746033&hash=item56fc9012bb%3Ag%3AUUIAAOSwjy5kpm0L&LH_BIN=1',
 'https://www.ebay.com/itm/352746449801?hash=item522153ab89%3Ag%3A-isAAOSwMtBkuQ3u&LH_BIN=1',
 'https://www.ebay.com/itm/372733005815?epid=1979763452&hash=item56c89e4ff7%3Ag%3ATqIAAOSw6N1kuRAw&LH_BIN=1',
 'https://www.ebay.com/itm/374138900770?hash=item571c6a9122%3Ag%3AXfQAAOSw35FirxbO&LH_BIN=1',
 'https://www.ebay.com/itm/233149646361?hash=item3648cd4619%3Ag%3AEacAAOSwMd9kuUmL&LH_BIN=1',
 'https://www.ebay.com/itm/234039559907?hash=item367dd846e3%3Ag%3A91kAAOSwgMpknzux&LH_BIN=1',
 'https://www.ebay.com/itm/233315329917?hash=item3652ad677d%3Ag%3AxZoAAOSwAOJknzNl&LH_BIN=1',
 'https://www.ebay.com/itm/351831910382?hash=item51ead0e7ee%3Ag%3ALkwAAOSwIGxkoADq&LH_BIN=1',
 'https://www.ebay.com/itm/234039561168?epid=3018752723&hash=item367dd84bd0%3Ag%3Azf4AAOSwN7dkuHVk&LH_BIN=1',
 'https://www.ebay.com/itm/371671194143?hash=item5689545a1f%3Ag%3AodgAAOSwJHNkuKSt&LH_BIN=1',
 'https://www.ebay.com/itm/233151996131?hash=item3648f120e3%3Ag%3AQcQAAOSwVblkuHMM&LH_BIN=1',
 'https://www.ebay.com/itm/231770787953?hash=item35f69d9071%3Ag%3AoVsAAOSwoThkpiLi&LH_BIN=1',
 'https://www.ebay.com/itm/234999229421?hash=item36b70babed%3Ag%3AHloAAOSw0hZkuaKX&LH_BIN=1',
 'https://www.ebay.com/itm/234658966858?hash=item36a2c3ad4a%3Ag%3AG-wAAOSwUQBkuVeE&LH_BIN=1',
 'https://www.ebay.com/itm/373635542702?hash=item56fe69eeae%3Ag%3AhBwAAOSwBitkub%7Eh&LH_BIN=1',
 'https://www.ebay.com/itm/232780212751?hash=item3632c82a0f%3Ag%3AOH4AAOSwhgNkr9Wx&LH_BIN=1',
 'https://www.ebay.com/itm/373627139547?hash=item56fde9b5db%3Ag%3AZsQAAOSwJHNkuYbq&LH_BIN=1',
 'https://www.ebay.com/itm/234999225098?hash=item36b70b9b0a%3Ag%3ApG8AAOSwzmJkuaIB&LH_BIN=1',
 'https://www.ebay.com/itm/234039569145?hash=item367dd86af9%3Ag%3Aai4AAOSwsx5kpjB1&LH_BIN=1',
 'https://www.ebay.com/itm/353536344281?hash=item52506880d9%3Ag%3Ae-AAAOSwXqhkpkqP&LH_BIN=1',
 'https://www.ebay.com/itm/353578695167?epid=8028120862&hash=item5252eeb9ff%3Ag%3AhlsAAOSwxhJkn8Sc&LH_BIN=1',
 'https://www.ebay.com/itm/354852919300?hash=item529ee1d804%3Ag%3AKy0AAOSw1G5kubec&LH_BIN=1',
 'https://www.ebay.com/itm/351773304593?epid=1472709415&hash=item51e752a711%3Ag%3Akd8AAOSwzbNksE05&LH_BIN=1',
 'https://www.ebay.com/itm/350846641046?hash=item51b016e396%3Ag%3AN8kAAOSw91tkn01r&LH_BIN=1',
 'https://www.ebay.com/itm/370809156559?hash=item5655f2b3cf%3Ag%3Auq4AAOSwQulkn2H3&LH_BIN=1',
 'https://www.ebay.com/itm/234091476834?hash=item3680f07762%3Ag%3AmsYAAOSwHyNkuVDl&LH_BIN=1',
 'https://www.ebay.com/itm/352271693773?hash=item52050777cd%3Ag%3As6EAAOSwaWlkuIg4&LH_BIN=1',
 'https://www.ebay.com/itm/373604504321?hash=item56fc905301%3Ag%3AdocAAOSwylJkub4U&LH_BIN=1',
 'https://www.ebay.com/itm/352521748645?epid=25018737734&hash=item5213ef00a5%3Ag%3AwIoAAOSwl-xkuIsX&LH_BIN=1',
 'https://www.ebay.com/itm/352550929813?hash=item5215ac4595%3Ag%3AX2MAAOSwo81kpkLl&LH_BIN=1',
 'https://www.ebay.com/itm/354634086703?hash=item5291d6b92f%3Ag%3AD1wAAOSwa-9kpldP&LH_BIN=1',
 'https://www.ebay.com/itm/374551514900?hash=item5735028f14%3Ag%3AvloAAOSwE9tkpnOp&LH_BIN=1',
 'https://www.ebay.com/itm/374678439818?hash=item573c93478a%3Ag%3AqCgAAOSwHdlkuRIU&LH_BIN=1',
 'https://www.ebay.com/itm/354763656022?hash=item52998fcb56%3Ag%3AHmcAAOSw0I1kuQ9N&LH_BIN=1',
 'https://www.ebay.com/itm/374678439752?hash=item573c934748%3Ag%3AnGgAAOSwVuFksdqx&LH_BIN=1',
 'https://www.ebay.com/itm/234999229656?hash=item36b70bacd8%3Ag%3AlK4AAOSwgMpkscgE&LH_BIN=1',
 'https://www.ebay.com/itm/373651443520?hash=item56ff5c8f40%3Ag%3AJRkAAOSwCzlksbgW&LH_BIN=1',
 'https://www.ebay.com/itm/374737456477?hash=item574017cd5d%3Ag%3AoPIAAOSw0edkfSl6&LH_BIN=1',
 'https://www.ebay.com/itm/373603454328?epid=1679597006&hash=item56fc804d78%3Ag%3ADWYAAOSwKztkuYVT&LH_BIN=1',
 'https://www.ebay.com/itm/354318381822?hash=item527f0572fe%3Ag%3AcdUAAOSwymdkubM6&LH_BIN=1',
 'https://www.ebay.com/itm/374678448455?hash=item573c936947%3Ag%3ATmAAAOSwIw9kuceC&LH_BIN=1',
 'https://www.ebay.com/itm/235005373025?hash=item36b7696a61%3Ag%3A1dwAAOSwyGRkuaPQ&LH_BIN=1',
 'https://www.ebay.com/itm/233230110898?hash=item364d9910b2%3Ag%3AjO0AAOSwLAVksYe5&LH_BIN=1',
 'https://www.ebay.com/itm/374767581647?hash=item5741e379cf%3Ag%3A-xIAAOSwuuFkucq7&LH_BIN=1',
 'https://www.ebay.com/itm/354763656084?hash=item52998fcb94%3Ag%3ALQcAAOSwbd5ksc%7Em&LH_BIN=1',
 'https://www.ebay.com/itm/372413811598?hash=item56b597cb8e%3Ag%3AYpgAAOSwwG1kubop&LH_BIN=1',
 'https://www.ebay.com/itm/374678461139?hash=item573c939ad3%3Ag%3ALZUAAOSwrYVksdua&LH_BIN=1',
 'https://www.ebay.com/itm/372320551881?hash=item56b008c3c9%3Ag%3AIrYAAOSwEDlksG4w&LH_BIN=1',
 'https://www.ebay.com/itm/233089678014?hash=item36453a3abe%3Ag%3Alf0AAOSwZhBksDjX&LH_BIN=1',
 'https://www.ebay.com/itm/234091515015?hash=item3680f10c87%3Ag%3ATxkAAOSwO0JkuVEY&LH_BIN=1',
 'https://www.ebay.com/itm/234999227220?hash=item36b70ba354%3Ag%3AC6cAAOSwrx1kscdz&LH_BIN=1',
 'https://www.ebay.com/itm/374759024915?hash=item574160e913%3Ag%3ApC8AAOSw-R5kuclM&LH_BIN=1',
 'https://www.ebay.com/itm/373603464756?hash=item56fc807634%3Ag%3AfmcAAOSw%7EmRkn9l2&LH_BIN=1',
 'https://www.ebay.com/itm/373652558136?hash=item56ff6d9138%3Ag%3AXxYAAOSw1ZZkn90L&LH_BIN=1',
 'https://www.ebay.com/itm/371053737477?epid=1677453149&hash=item566486b605%3Ag%3AIUYAAOSwU7tksGh1&LH_BIN=1',
 'https://www.ebay.com/itm/371671709554?hash=item56895c3772%3Ag%3APfMAAOSwyC9kn2eB&LH_BIN=1',
 'https://www.ebay.com/itm/235005370675?hash=item36b7696133%3Ag%3AdIQAAOSw81hkuaOs&LH_BIN=1',
 'https://www.ebay.com/itm/352392237092?hash=item520c36d024%3Ag%3Am5YAAOSw87tkpkJi&LH_BIN=1',
 'https://www.ebay.com/itm/352837810338?hash=item5226c5b8a2%3Ag%3AxnEAAOSwsiBkuao4&LH_BIN=1',
 'https://www.ebay.com/itm/373251652591?hash=item56e7883bef%3Ag%3AWikAAOSwbFVkuK%7EE&LH_BIN=1',
 'https://www.ebay.com/itm/233715189195?hash=item366a82c5cb%3Ag%3AnTQAAOSwyy5kuHUJ&LH_BIN=1',
 'https://www.ebay.com/itm/234091466123?hash=item3680f04d8b%3Ag%3AkJMAAOSwsudkn0hL&LH_BIN=1',
 'https://www.ebay.com/itm/234091466183?hash=item3680f04dc7%3Ag%3ANWIAAOSwzmJkuHed&LH_BIN=1',
 'https://www.ebay.com/itm/354852961018?hash=item529ee27afa%3Ag%3AXy0AAOSwZgdkubfw&LH_BIN=1',
 'https://www.ebay.com/itm/372493505105?hash=item56ba57d251%3Ag%3A5NQAAOSwgq5kubpr&LH_BIN=1',
 'https://www.ebay.com/itm/231312219407?epid=2308511253&hash=item35db485d0f%3Ag%3AaRQAAOSwYttkuR20&LH_BIN=1',
 'https://www.ebay.com/itm/374688162449?hash=item573d27a291%3Ag%3At54AAOSwI8Rkucdw&LH_BIN=1',

In [2]:
df = pd.DataFrame(columns=['Url',
                           'iframe',
                           'status'])

df

Empty DataFrame
Columns: [Url, iframe, status]
Index: []

In [3]:
import requests
import random

In [4]:
i = 1

headers = {'User-Agent': random.choice(list_user_agent),
           'Referer': referer}

if '?' in list_url[i]:
    resp = requests.get(list_url[i] + '&_ul=US', headers=headers).text
else:
    resp = requests.get(list_url[i] + '?_ul=US', headers=headers).text

resp

'<!DOCTYPE html>\n<html xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://opengraphprotocol.org/schema/" lang=en>\n<head>\n<link rel="dns-prefetch" href="//i.ebayimg.com">\n<link rel="dns-prefetch" href="//thumbs.ebaystatic.com">\n<link rel="dns-prefetch" href="//vi.vipr.ebaydesc.com">\n<link rel="dns-prefetch" href="//p.ebaystatic.com">\n<link rel="dns-prefetch" href="//q.ebaystatic.com">\n<link rel="dns-prefetch" href="//pics.ebaystatic.com">\n<link rel="dns-prefetch" href="//ir.ebaystatic.com">\n<link rel="dns-prefetch" href="//srx.main.ebayrtm.com">\n<link rel="dns-prefetch" href="//rover.ebay.com">\n<link rel="dns-prefetch" href="//reco.ebay.com">\n\n<link rel="dns-prefetch" href="//i.ebayimg.cn">\n<link rel="dns-prefetch" href="//ir.ebaystatic.cn">\n<link rel="preconnect" href="https://i.ebayimg.cn">\n<link rel="preconnect" href="https://ir.ebaystatic.cn">\n<!--  fix for IE freezing.  -->\n<style type="text/css">\nbody #Body .btn, body #Body c-std {\nfilter:none;\n-ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=\'#0079bc\',endColorstr=\'#00509d\')";\n}\n</style>\n\n\t<meta name="viewport"/>\n\t<meta name="layout" content="main" />\n\t<!-- Use ?ForceSiteSpeedGauge=true for forcing -->\n\t<link rel="dns-prefetch" href="//secureir.ebaystatic.com">\n\t<link rel="dns-prefetch" href="//i.ebayimg.com">\n\t<link rel="preconnect" href="https://ir.ebaystatic.com" /><meta name="twitter:site" content="@eBay" /><meta Property="og:description" Content="Find many great new &amp; used options and get the best deals for Headlight Set For 99-2000 GMC Yukon Denali Cadillac Escalade LH RH w/ bulb at the best online prices at eBay! Free shipping for many products!" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=CO" hreflang="es-co" /><meta Property="og:type" Content="ebay-objects:item" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=PY" hreflang="es-py" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=EC" hreflang="es-ec" /><meta name="google-site-verification" content="8kHr3jd3Z43q1ovwo0KVgo_NZKIEMjthBxti8m8fYTg" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=PA" hreflang="es-pa" /><meta http-equiv="content-language" content="en-US" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=GT" hreflang="es-gt" /><meta Property="og:site_name" Content="eBay" /><meta name="yandex-verification" content="6e11485a66d91eff" /><meta name="y_key" content="acf32e2a69cbc2b0" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=AR" hreflang="es-ar" /><link rel="alternate" href="android-app://com.ebay.mobile/ebay/link/?nav=item.view&amp;id=372749825457&amp;referrer=http%3A%2F%2Frover.ebay.com%2Froverns%2F1%2F711-13271-9788-0%3Fmpcl%3Dhttp%253A%252F%252Fwww.ebay.com%252Fitm%252F372749825457" /><link href="https://i.ebayimg.com" rel="preconnect" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=DO" hreflang="es-do" /><meta name="description" content="Find many great new &amp; used options and get the best deals for Headlight Set For 99-2000 GMC Yukon Denali Cadillac Escalade LH RH w/ bulb at the best online prices at eBay! Free shipping for many products!" /><meta Property="og:image" Content="https://i.ebayimg.com/images/g/ugQAAOSwF5VksbNW/s-l500.jpg" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=HN" hreflang="es-hn" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=RU" hreflang="ru-ru" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=PE" hreflang="es-pe" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=NI" hreflang="es-ni" /><meta Property="og:url" Content="https://www.ebay.com/itm/372749825457" /><meta name="twitter:title" content="Headlight Set For 99-2000 GMC Yukon Denali Cadillac Escalade LH RH w/ bulb" /><meta name="twitter:image" content="https://i.ebayimg.com/images/g/ugQAAOSwF5VksbNW/s-l500.jpg" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=PR" hreflang="es-pr" /><meta name="referrer" content="unsafe-url" /><meta Property="og:title" Content="Headlight Set For 99-2000 GMC Yukon Denali Cadillac Escalade LH RH w/ bulb  | eBay" /><meta name="msvalidate.01" content="34E98E6F27109BE1A9DCF19658EEEE33" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=CL" hreflang="es-cl" /><link rel="canonical" href="https://www.ebay.com/itm/372749825457" /><meta name="robots" content="max-snippet:-1, max-image-preview:large" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=KZ" hreflang="ru-kz" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=IN" hreflang="en-IN" /><meta property="fb:app_id" content="102628213125203" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457" hreflang="x-default" /><title>Headlight Set For 99-2000 GMC Yukon Denali Cadillac Escalade LH RH w/ bulb  | eBay</title><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=UY" hreflang="es-uy" /><meta name="twitter:card" content="summary" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=BR" hreflang="pt-br" /><meta name="twitter:description" content="Find many great new &amp; used options and get the best deals for Headlight Set For 99-2000 GMC Yukon Denali Cadillac Escalade LH RH w/ bulb at the best online prices at eBay! Free shipping for many products!" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=MX" hreflang="es-mx" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=VE" hreflang="es-ve" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=CR" hreflang="es-cr" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=CN" hreflang="zh-CN" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=SV" hreflang="es-sv" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=PT" hreflang="pt-PT" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=BY" hreflang="ru-by" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=BO" hreflang="es-bo" /><link rel="alternate" href="https://www.ebay.com/itm/372749825457?_ul=IL" hreflang="en-IL" /><!-- NGMARS SIGNATURE --><!--[if IE]><link/><![endif]-->\n\t<!--[if lt IE 8]>\n\t\t<![endif]-->\n\t<!-- adding lens js -->\n<link href="https://ir.ebaystatic.com/rs/v/lezupbyvbi4xxgg5ybmres5aeij.css" type="text/css" rel="stylesheet"><link href="https://ir.ebaystatic.com/rs/v/jjqjxks3ge3wnavflblugnta4iz.css?proc=DU:N" type="text/css" rel="stylesheet"><link href="https://ir.ebaystatic.com/rs/v/uezdpo5r5qzmrljwfdhqdx3tdqv.css" type="text/css" rel="stylesheet"><style type="text/css">body .is.vi-ppc-main .mm-dp {\nwidth:35%;\n}\n\n#vi-snippet-description-main.u-padB20 {\n    padding-top:10px;\n    float:left;\n}\n\n.vi-descsnpt-feedbacklnk {\n    position: relative;\n    top: -20px;\n    width: 500px;\n    margin-left: 250px;\n}\n\n.asqMain {\n    clear:both;\n}\n\ndiv#bsi-c {\nclear: both;\n}\n.vi-pco-bboxtxt-Ins * {\n\tfont-weight: normal !important;\n\tcolor: #0654ba !important;\n}\ndiv.addonyes{ background: url(\'//ir.ebaystatic.com/cr/v/c1/addonwrty.png\') no-repeat 0 -54px; background-size: 16px; } \ndiv.addonno{ background: url(\'//ir.ebaystatic.com/cr/v/c1/addonwrty.png\') no-repeat 0 -72px; background-size: 16px; }\n.adninc{width:620px}.imgtitle{background-color:#fff;height:76px;padding-top:16px}.adnimg{float:left;padding:0 16px 0 24px;height:60px;width:60px;line-height:60px}.adnlogoimg{max-width:60px;max-height:60px;vertical-align:middle}#adndesctbl{margin-bottom:10px}.adnlabel{font-size:17px;vertical-align:middle;font-family:HelveticaNeue,Helvetica Neue,Helvetica,Arial,sans-serif;font-weight:500;font-stretch:normal;color:#5ba71b;padding-top:10px}.adntitle{font-size:13px;vertical-align:middle;font-family:HelveticaNeue,Helvetica Neue,Helvetica,Arial,sans-serif;font-weight:500;font-stretch:normal;color:#333;padding-top:8px}.adnactions{padding-top:24px}.adnlrnmore{display:block;float:left;font-size:14px;color:#00489f;padding:16px 0 0 16px;text-decoration:none;outline:0 none!important;font-weight:400}.addonBtn{float:right}.adndesclbl{font-family:HelveticaNeue,Helvetica Neue,Helvetica,Arial,sans-serif;font-size:20px;font-weight:400;font-style:normal;font-stretch:normal;color:#555;padding:0 0 16px 16px}.adndesc{border-top:solid 1px #ddd;padding:24px;background-color:#f6f6f6}.addondescdetails{border-collapse:collapse;border:1px solid #DDD;background-color:#fff;border-radius:5px}.wrttitle{padding:16px;font-family:HelveticaNeue,Helvetica Neue,Helvetica,Arial,sans-serif;font-size:15px;font-weight:500;font-style:normal;font-stretch:normal;text-align:left;color:#333}.addontr{height:25px;vertical-align:middle}.addyesno{padding:6px 12px 6px 16px;width:16px}.addonyes{background:url(//ir.ebaystatic.com/cr/v/c1/addonwrty.png) no-repeat 0 -54px;height:16px;width:16px;background-size:16px}.addonno{background:url(//ir.ebaystatic.com/cr/v/c1/addonwrty.png) no-repeat 0 -72px;height:16px;width:16px;background-size:16px}.addondesc{font-size:13px;line-height:15px;font-family:HelveticaNeue,Helvetica Neue,Helvetica,Arial,sans-serif;width:528px;padding:6px 12px 6px 0}.addonbtn{padding:.5em 1.2em;border:1px solid transparent;border-radius:3px;vertical-align:baseline;text-align:center;text-decoration:none;white-space:nowrap;font-weight:500;font-size:16px;cursor:pointer;zoom:1;display:inline-block;*display:inline;width:129px;font-family:HelveticaNeue,Helvetica Neue,Helvetica,Arial,sans-serif}.adnclr{clear:both}.addonbtn{padding:.5em 1.2em;border:1px solid transparent;border-radius:3px;vertical-align:baseline;text-align:center;text-decoration:none;white-space:nowrap;font-weight:500;font-size:16px;cursor:pointer;zoom:1;display:inline-block;*display:inline;width:129px;font-family:HelveticaNeue,Helvetica Neue,Helvetica,Arial,sans-serif}.addonbtn:hover{background-color:#eee;background-position:0 -15px;-webkit-box-shadow:0 0 0 rgba(0,0,0,.2);-moz-box-shadow:0 0 0 rgba(0,0,0,.2);box-shadow:0 0 0 rgba(0,0,0,.2);text-decoration:none;-moz-transition:background-position .1s linear 0}.addonbtn:active{position:relative;top:1px}.addonaddplan{background:#00509d;background:-webkit-gradient(linear,left top,left bottom,from(#0079bc),to(#00509d));background:-moz-linear-gradient(top,#0079bc,#00509d);text-decoration:none;filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=\'#0079bc\',endColorstr=\'#00509d\');color:#fff;margin-right:16px;font-family:HelveticaNeue,Helvetica Neue,Helvetica,Arial,sans-serif}.addonaddplan:hover,.addonaddplan:focus,.addonaddplan:active{background:#00509d;filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=\'#00509d\',endColorstr=\'#00509d\')}.addonnothx{border:1px solid #ddd;background:#f8f8f8;background:-webkit-gradient(linear,left top,left bottom,from(#fefefe),to(#f8f8f8));background:-moz-linear-gradient(top,#fefefe,#f8f8f8);text-decoration:none;filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=\'#fefefe\',endColorstr=\'#f8f8f8\');color:#0654ba;margin-right:16px;font-family:HelveticaNeue,Helvetica Neue,Helvetica,Arial,sans-serif}.addonnothx:hover,.addonnothx:focus,.addonnothx:active{border:1px solid #aaa;background:#fafafa}.ui-hlp-hidden{width:0;height:0;z-index:-1;overflow:hidden;line-height:0;position:absolute}.outline{outline:0 none!important}div .calc_ec-a3 {background-image: url(//pics.ebaystatic.com/aw/pics/cmp/ds3/sprds3_18.png);}\n.similar-items-panel .similar-items-title {font-family: "Helvetica neue",Helvetica,Verdana,Sans-serif !important;}\n#Body .app-mtp-theme-tabs * {font-family: "Helvetica neue",Helvetica,Verdana,Sans-serif}\n#Body .theme-details * {font-family: "Helvetica neue",Helvetica,Verdana,Sans-serif}\nh1#ProductTitle {font-family: "Helvetica neue",Helvetica,Verdana,Sans-serif}</style><style type="text/css">\n\t\t\t\thtml a:link{\n\t\t\t\t\tcolor: #0654ba;\n\t\t\t\t}\n\t\t\t\tul#bc a:link{\n\t\t\t\t\tcolor: #0654ba;\n\t\t\t\t}\n\t\t\t\t.mbg a:link{\n\t\t\t\t\tcolor: #0654ba !important;\n\t\t\t\t}\n\t\t\t\t.mbg-l a:link{\n\t\t\t\t\tcolor: #0654ba !important;\n\t\t\t\t}\n\t\t\t\t#Body .nav-tabs-m a:link{\n\t\t\t\t\tcolor: #0654ba;\n\t\t\t\t}\n\t\t\t</style>\n\t\t<link rel="stylesheet" href="https://ir.ebaystatic.com/rs/c/vimoduleapi-async-jLtE0kwS.css" type="text/css" />\n    <link rel="stylesheet" href="https://ir.ebaystatic.com/rs/c/vimoduleapi-_x48H5Ur.css" type="text/css" />\n    </head>\n\n<body class=" vi-contv2  lhdr-ie- vi-hd-ops  vi-wide-watch-btn  vi-ds3-global  vi-bb-flex  label-right-align  vi-bb-btnclr1  vi-ds6  vi-bb-r-btn  vi-white-spacing  vi-rounded-btns  vi-long-cta"> <div id="Head">\n\t\t</div>\n\n\t<div id="Body" class=" sz940 sz1280 ">\n\t\t<div id="maskDiv"></div>\n\t\t<div id="TopPanelDF"><div id="Top">\n<div id="TopPanel" class="">\n\t\t\t\t<style>.gh-hide-if-nocss{display:none;}.gh-ar-hdn{color:#fff}</style> <div class="gh-acc-exp-div gh-hide-if-nocss"><a id=gh-hdn-stm class=gh-acc-a href="#mainContent">Skip to main content</a></div><!--[if lt IE 9]><div id="gh" role="banner" class="gh-IE8 gh-flex gh-pre-js gh-w "><![endif]--><!--[if (gte IE 9)|!(IE)]><!--><header id=gh role="banner"class="gh-ui-6-5 gh-flex gh-pre-js gh-w gh-sch-prom " data-treatment=><!--<![endif]--><table class="gh-tbl" role="presentation"><tbody><tr><td class="gh-td"><a href="https://www.ebay.com/" _sp="m570.l2586" id="gh-la"><img width=250 height=200 style=\'clip:rect(47px, 118px, 95px, 0px); position:absolute; top:-47px;left:0\' alt="eBay Logo" src="https://ir.ebaystatic.com/rs/v/fxxj3ttftm5ltcqnto1o4baovyl.png" id="gh-logo"></a><!--<![endif]--></td><td class="gh-td"></td><td class="gh-td"></td><td class="gh-td"><div id=gh-shop class=gh-hide-if-nocss><button id=gh-shop-a aria-expanded="false" class=gh-control aria-controls=gh-sbc-o> Shop by category<i id="gh-shop-ei" class="gh-sprRetina"></i></button><div id=gh-sbc-o><h2 class="gh-ar-hdn">Shop by category</h2></div></div></td><td class="gh-td-s"><form id="gh-f" method="get" action="https://www.ebay.com/sch/i.html"><input type="hidden" value="R40" name="_from"><input type="hidden" name="_trksid" value="m570.l1313"><table class="gh-tbl2" role="presentation"><tbody><tr><td class="gh-td-s" ><div id=gh-ac-box><div id=gh-ac-box2><label for=gh-ac class="gh-ar-hdn">Enter your search keyword</label><input type="text" class="gh-tb ui-autocomplete-input" aria-autocomplete= "list" aria-expanded="false" size="50" maxlength="300" aria-label="Search for anything" placeholder="Search for anything" id="gh-ac" name="_nkw" autocapitalize="off" autocorrect="off" spellcheck="false" autocomplete="off"><input style="display:none"/><script> if(document.getElementById(\'gh-ac\').value.length !== 0) { document.getElementById(\'gh-ac-box\').classList.add(\'gh-ac-box-focus\'); document.getElementById(\'gh\').classList.add(\'gh-sch-focus\'); } </script><svg aria-hidden="true" class="icon icon--search gh-search__icon" focusable="false" height="14" width="14"><use xlink:href="#icon-search"></use></svg> </div></div></td><td class="gh-td" id=gh-cat-td><div id=gh-cat-box><select aria-label="Select a category for search" class="gh-sb " size=1 id=gh-cat name="_sacat"><option selected=selected value="0">All Categories</option></select></div></td><td class="gh-td gh-sch-btn" ><input type="submit" class="btn btn-ter gh-spr" id="gh-btn" value="Search"><svg aria-hidden="true" class="icon icon--search gh-search-btn__icon" focusable="false" height="22" width="22"><use xlink:href="#icon-search"></use></svg></td><td class="gh-td" id=gh-as-td><a title="Advanced Search" href="https://www.ebay.com/sch/ebayadvsearch" aria-label="Advanced Search" _sp=m570.l2614 id=gh-as-a>Advanced</a></td></tr></tbody></table></form></td><td class="gh-td"></td><td class="sticky_placeholder"><ul></ul></td></tr></tbody></table><div id=gh-top class=gh-hide-if-nocss role="navigation" aria-label="Account"><ul id="gh-topl"><li class="gh-t " id=gh-eb-u><script> var supressUserGreeting = true; </script><script>(function(){try{ var sup = !!(supressUserGreeting && typeof window.GHpre !== \'undefined\' && !window.GHpre.si); var d=document.cookie,a=((a=d.match(/u1f[^a-zA-Z0-9]([^^]*)[0-9a-z]{8}/))?a[1].replace(/\\+/g," "):"").replace(/(.{12}).*/,"$1...");if(/[<>%&\'\\/]/.test(a)){throw(1)}document.write("<span id=gh-ug"+(!a||/u1p.QEBfX/.test(d)?\' class=gh-ug-guest>Hi! <a href="https://signin.ebay.com/ws/eBayISAPI.dll?SignIn&amp;_trksid=m570.l1524" rel="nofollow" _sp="m570.l1524">Sign in</a>\xa0<span id="gh-ug-flex">or <a href="https://signup.ebay.com/pa/crte?_trksid=m570.l2621" rel="nofollow" _sp="m570.l2621">register</a></span>\':\' style="margin-right:3px">Hi <b>-User-</b>!\'.replace(/-User-/,sup ? \'\' : decodeURIComponent(escape(a))))+"</span>")}catch(b){document.write("<style>#gh-topl{display:none}</style>")}})();</script><noscript class=\'gh-t gh-spr\'>Hi (<a href="https://signin.ebay.com/ws/eBayISAPI.dll?SignIn&amp;_trksid=m570.l3348">Sign in</a> to bid or buy)</noscript></li><li class="gh-t gh-divider-l" id=gh-p-1><a href="https://www.ebay.com/deals" _sp=m570.l3188 data-sp=m570.l3188 class="gh-p" > Daily Deals</a></li><li class="gh-t gh-divider-l" id=gh-p-4><a href="https://www.ebay.com/b/Brand-Outlet/bn_7115532402" _sp=m570.l47233 data-sp=m570.l47233 class="gh-p" > Brand Outlet</a></li><li class="gh-t gh-divider-l" id=gh-p-3><a href="https://ocsnext.ebay.com/ocs/home" _sp=m570.l1545 data-sp=m570.l1545 class="gh-p" > Help & Contact</a></li></ul><ul id="gh-eb"><li id=gh-p-2 class="gh-eb-li gh-t-rt gh--link__divider" ><a href="https://www.ebay.com/sl/sell" _sp=m570.l1528 data-sp=m570.l1528 class="gh-p" > Sell</a></li><li id=gh-wl-click class="gh-eb-li gh-margin rt" ><div class="gh-menu gh--link__divider"><a href="https://www.ebay.com/mye/myebay/watchlist" _sp=m570.l47137 title="Watchlist" class="gh-eb-li-a gh-rvi-menu watchlist-menu" >Watchlist<i class="gh-sprRetina gh-eb-arw gh-rvi-chevron" data-sp=m570.l47137></i></a><a href="#gh-wl-click" role=button aria-expanded=false data-controlTarget=gh-wl-click-o class="gh-acc-exp-a gh-acc-a2 gh-control">Expand Watch List</a><div class="gh-sublayer gh-flyout__menu" id="gh-wl-click-flyout" role="dialog" aria-label="Watchlist"><button id="gh-wl-click-close" class="gh_flyout__close" aria-label="Close dialog"><svg aria-hidden="true" focusable="false" height="17" width="17"><use xlink:href="#icon-close"/></svg></button><div id="gh-wl-click-body"><div class="gh-loading"><span class="gh-spinner" aria-label="Loading" role="img"></span><span class="gh-state">Loading...</span></div><div class="gh-wl-click-gen-error"><span><a href="https://signin.ebay.com/ws/eBayISAPI.dll?SignIn&amp;ru=ru">Sign in</a> to see your user information</span></div></div> </div></div></li><li id=gh-eb-My class="gh-eb-li gh-hvr gh-dd rt" data-imp=10><div class="gh-menu"><a href="https://www.ebay.com/mys/home?source=GBH" _sp=m570.l2919 title="My eBay" class="gh-eb-li-a gh-rvi-menu" >My eBay<i class="gh-sprRetina gh-eb-arw gh-rvi-chevron" data-sp=m570.l2919></i></a><a href="#gh-eb-My" role=button aria-expanded=false data-controlTarget=gh-eb-My-o class="gh-acc-exp-a gh-acc-a2 gh-control">Expand My eBay</a><div class="gh-submenu gh-eb-o" id="gh-eb-My-o"><ul role=navigation id="gh-ul-nav"><li ><a href="https://www.ebay.com/mye/myebay/summary" _sp=m570.l1533 data-sp=m570.l1533 class="gh-eb-oa thrd" > Summary</a></li><li ><a href="https://www.ebay.com/mye/myebay/rvi" _sp=m570.l9225 data-sp=m570.l9225 class="gh-eb-oa thrd" > Recently Viewed</a></li><li ><a href="https://www.ebay.com/mye/myebay/v2/bidsoffers" _sp=m570.l1535 data-sp=m570.l1535 class="gh-eb-oa thrd" > Bids/Offers</a></li><li ><a href="https://www.ebay.com/mye/myebay/watchlist" _sp=m570.l1534 data-sp=m570.l1534 class="gh-eb-oa thrd" > Watchlist</a></li><li ><a href="https://www.ebay.com/mye/myebay/purchase" _sp=m570.

In [5]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(resp, 'lxml')

print(soup.prettify())

<!DOCTYPE html>
<html lang="en" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://opengraphprotocol.org/schema/">
 <head>
  <link href="//i.ebayimg.com" rel="dns-prefetch"/>
  <link href="//thumbs.ebaystatic.com" rel="dns-prefetch"/>
  <link href="//vi.vipr.ebaydesc.com" rel="dns-prefetch"/>
  <link href="//p.ebaystatic.com" rel="dns-prefetch"/>
  <link href="//q.ebaystatic.com" rel="dns-prefetch"/>
  <link href="//pics.ebaystatic.com" rel="dns-prefetch"/>
  <link href="//ir.ebaystatic.com" rel="dns-prefetch"/>
  <link href="//srx.main.ebayrtm.com" rel="dns-prefetch"/>
  <link href="//rover.ebay.com" rel="dns-prefetch"/>
  <link href="//reco.ebay.com" rel="dns-prefetch"/>
  <link href="//i.ebayimg.cn" rel="dns-prefetch"/>
  <link href="//ir.ebaystatic.cn" rel="dns-prefetch"/>
  <link href="https://i.ebayimg.cn" rel="preconnect"/>
  <link href="https://ir.ebaystatic.cn" rel="preconnect"/>
  <!--  fix for IE freezing.  -->
  <style type="text/css">
   body #Body .btn, body #Body c-std {
filter:none;
-ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr='#0079bc',endColorstr='#00509d')";
}
  </style>
  <meta name="viewport"/>
  <meta content="main" name="layout"/>
  <!-- Use ?ForceSiteSpeedGauge=true for forcing -->
  <link href="//secureir.ebaystatic.com" rel="dns-prefetch"/>
  <link href="//i.ebayimg.com" rel="dns-prefetch"/>
  <link href="https://ir.ebaystatic.com" rel="preconnect"/>
  <meta content="@eBay" name="twitter:site"/>
  <meta content="Find many great new &amp; used options and get the best deals for Headlight Set For 99-2000 GMC Yukon Denali Cadillac Escalade LH RH w/ bulb at the best online prices at eBay! Free shipping for many products!" property="og:description"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=CO" hreflang="es-co" rel="alternate"/>
  <meta content="ebay-objects:item" property="og:type"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=PY" hreflang="es-py" rel="alternate"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=EC" hreflang="es-ec" rel="alternate"/>
  <meta content="8kHr3jd3Z43q1ovwo0KVgo_NZKIEMjthBxti8m8fYTg" name="google-site-verification"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=PA" hreflang="es-pa" rel="alternate"/>
  <meta content="en-US" http-equiv="content-language"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=GT" hreflang="es-gt" rel="alternate"/>
  <meta content="eBay" property="og:site_name"/>
  <meta content="6e11485a66d91eff" name="yandex-verification"/>
  <meta content="acf32e2a69cbc2b0" name="y_key"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=AR" hreflang="es-ar" rel="alternate"/>
  <link href="android-app://com.ebay.mobile/ebay/link/?nav=item.view&amp;id=372749825457&amp;referrer=http%3A%2F%2Frover.ebay.com%2Froverns%2F1%2F711-13271-9788-0%3Fmpcl%3Dhttp%253A%252F%252Fwww.ebay.com%252Fitm%252F372749825457" rel="alternate"/>
  <link href="https://i.ebayimg.com" rel="preconnect"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=DO" hreflang="es-do" rel="alternate"/>
  <meta content="Find many great new &amp; used options and get the best deals for Headlight Set For 99-2000 GMC Yukon Denali Cadillac Escalade LH RH w/ bulb at the best online prices at eBay! Free shipping for many products!" name="description"/>
  <meta content="https://i.ebayimg.com/images/g/ugQAAOSwF5VksbNW/s-l500.jpg" property="og:image"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=HN" hreflang="es-hn" rel="alternate"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=RU" hreflang="ru-ru" rel="alternate"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=PE" hreflang="es-pe" rel="alternate"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=NI" hreflang="es-ni" rel="alternate"/>
  <meta content="https://www.ebay.com/itm/372749825457" property="og:url"/>
  <meta content="Headlight Set For 99-2000 GMC Yukon Denali Cadillac Escalade LH RH w/ bulb" name="twitter:title"/>
  <meta content="https://i.ebayimg.com/images/g/ugQAAOSwF5VksbNW/s-l500.jpg" name="twitter:image"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=PR" hreflang="es-pr" rel="alternate"/>
  <meta content="unsafe-url" name="referrer"/>
  <meta content="Headlight Set For 99-2000 GMC Yukon Denali Cadillac Escalade LH RH w/ bulb  | eBay" property="og:title"/>
  <meta content="34E98E6F27109BE1A9DCF19658EEEE33" name="msvalidate.01"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=CL" hreflang="es-cl" rel="alternate"/>
  <link href="https://www.ebay.com/itm/372749825457" rel="canonical"/>
  <meta content="max-snippet:-1, max-image-preview:large" name="robots"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=KZ" hreflang="ru-kz" rel="alternate"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=IN" hreflang="en-IN" rel="alternate"/>
  <meta content="102628213125203" property="fb:app_id"/>
  <link href="https://www.ebay.com/itm/372749825457" hreflang="x-default" rel="alternate"/>
  <title>
   Headlight Set For 99-2000 GMC Yukon Denali Cadillac Escalade LH RH w/ bulb  | eBay
  </title>
  <link href="https://www.ebay.com/itm/372749825457?_ul=UY" hreflang="es-uy" rel="alternate"/>
  <meta content="summary" name="twitter:card"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=BR" hreflang="pt-br" rel="alternate"/>
  <meta content="Find many great new &amp; used options and get the best deals for Headlight Set For 99-2000 GMC Yukon Denali Cadillac Escalade LH RH w/ bulb at the best online prices at eBay! Free shipping for many products!" name="twitter:description"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=MX" hreflang="es-mx" rel="alternate"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=VE" hreflang="es-ve" rel="alternate"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=CR" hreflang="es-cr" rel="alternate"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=CN" hreflang="zh-CN" rel="alternate"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=SV" hreflang="es-sv" rel="alternate"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=PT" hreflang="pt-PT" rel="alternate"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=BY" hreflang="ru-by" rel="alternate"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=BO" hreflang="es-bo" rel="alternate"/>
  <link href="https://www.ebay.com/itm/372749825457?_ul=IL" hreflang="en-IL" rel="alternate"/>
  <!-- NGMARS SIGNATURE -->
  <!--[if IE]><link/><![endif]-->
  <!--[if lt IE 8]>
		<![endif]-->
  <!-- adding lens js -->
  <link href="https://ir.ebaystatic.com/rs/v/lezupbyvbi4xxgg5ybmres5aeij.css" rel="stylesheet" type="text/css"/>
  <link href="https://ir.ebaystatic.com/rs/v/jjqjxks3ge3wnavflblugnta4iz.css?proc=DU:N" rel="stylesheet" type="text/css"/>
  <link href="https://ir.ebaystatic.com/rs/v/uezdpo5r5qzmrljwfdhqdx3tdqv.css" rel="stylesheet" type="text/css"/>
  <style type="text/css">
   body .is.vi-ppc-main .mm-dp {
width:35%;
}

#vi-snippet-description-main.u-padB20 {
    padding-top:10px;
    float:left;
}

.vi-descsnpt-feedbacklnk {
    position: relative;
    top: -20px;
    width: 500px;
    margin-left: 250px;
}

.asqMain {
    clear:both;
}

div#bsi-c {
clear: both;
}
.vi-pco-bboxtxt-Ins * {
	font-weight: normal !important;
	color: #0654ba !important;
}
div.addonyes{ background: url('//ir.ebaystatic.com/cr/v/c1/addonwrty.png') no-repeat 0 -54px; background-size: 16px; }
div.addonno{ background: url('//ir.ebaystatic.com/cr/v/c1/addonwrty.png') no-repeat 0 -72px; background-size: 16px; }
.adninc{width:620px}.imgtitle{background-color:#fff;height:76px;padding-top:16px}.adnimg{float:left;padding:0 16px 0 24px;height:60px;width:60px;line-height:60px}.adnlogoimg{max-width:60px;max-height:60px;vertical-align:middle}#adndesctbl{margin-bottom:10px}.adnlabel{font-size:17px;vertical-align:middle;font-family:HelveticaNeue,Helvetica Neue,Helvetica,Arial,sans-serif;font-weight:500;font-stretch:normal;color:#5ba71b;padding-top:10px}.adntitle{font-size:13px;vertical-align:middle;font-family:HelveticaNeue,Helvetica Neue,Helvetica,Arial,sans-serif;font-weight:500;font-stretch:normal;color:#333;padding-top:8px}.adnactions{padding-top:24px}.adnlrnmore{display:block;float:left;font-size:14px;color:#00489f;padding:16px 0 0 16px;text-decoration:none;outline:0 none!important;font-weight:400}.addonBtn{float:right}.adndesclbl{font-family:HelveticaNeue,Helvetica Neue,Helvetica,Arial,sans-serif;font-size:20px;font-weight:400;font-style:normal;font-stretch:normal;color:#555;padding:0 0 16px 16px}.adndesc{border-top:solid 1px #ddd;padding:24px;background-color:#f6f6f6}.addondescdetails{border-collapse:collapse;border:1px solid #DDD;background-color:#fff;border-radius:5px}.wrttitle{padding:16px;font-family:HelveticaNeue,Helvetica Neue,Helvetica,Arial,sans-serif;font-size:15px;font-weight:500;font-style:normal;font-stretch:normal;text-align:left;color:#333}.addontr{height:25px;vertical-align:middle}.addyesno{padding:6px 12px 6px 16px;width:16px}.addonyes{background:url(//ir.ebaystatic.com/cr/v/c1/addonwrty.png) no-repeat 0 -54px;height:16px;width:16px;background-size:16px}.addonno{background:url(//ir.ebaystatic.com/cr/v/c1/addonwrty.png) no-repeat 0 -72px;height:16px;width:16px;background-size:16px}.addondesc{font-size:13px;line-height:15px;font-family:HelveticaNeue,Helvetica Neue,Helvetica,Arial,sans-serif;width:528px;padding:6px 12px 6px 0}.addonbtn{padding:.5em 1.2em;border:1px solid transparent;border-radius:3px;vertical-align:baseline;text-align:center;text-decoration:none;white-space:nowrap;font-weight:500;font-size:16px;cursor:pointer;zoom:1;display:inline-block;*display:inline;width:129px;font-family:HelveticaNeue,Helvetica Neue,Helvetica,Arial,sans-serif}.adnclr{clear:both}.addonbtn{padding:.5em 1.2em;border:1px solid transparent;border-radius:3px;vertical-align:baseline;text-align:center;text-decoration:none;white-space:nowrap;font-weight:500;font-size:16px;cursor:pointer;zoom:1;display:inline-block;*display:inline;width:129px;font-family:HelveticaNeue,Helvetica Neue,Helvetica,Arial,sans-serif}.addonbtn:hover{background-color:#eee;background-position:0 -15px;-webkit-box-shadow:0 0 0 rgba(0,0,0,.2);-moz-box-shadow:0 0 0 rgba(0,0,0,.2);box-shadow:0 0 0 rgba(0,0,0,.2);text-decoration:none;-moz-transition:background-position .1s linear 0}.addonbtn:active{position:relative;top:1px}.addonaddplan{background:#00509d;background:-webkit-gradient(linear,left top,left bottom,from(#0079bc),to(#00509d));background:-moz-linear-gradient(top,#0079bc,#00509d);text-decoration:none;filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#0079bc',endColorstr='#00509d');color:#fff;margin-right:16px;font-family:HelveticaNeue,Helvetica Neue,Helvetica,Arial,sans-serif}.addonaddplan:hover,.addonaddplan:focus,.addonaddplan:active{background:#00509d;filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#00509d',endColorstr='#00509d')}.addonnothx{border:1px solid #ddd;background:#f8f8f8;background:-webkit-gradient(linear,left top,left bottom,from(#fefefe),to(#f8f8f8));background:-moz-linear-gradient(top,#fefefe,#f8f8f8);text-decoration:none;filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#fefefe',endColorstr='#f8f8f8');color:#0654ba;margin-right:16px;font-family:HelveticaNeue,Helvetica Neue,Helvetica,Arial,sans-serif}.addonnothx:hover,.addonnothx:focus,.addonnothx:active{border:1px solid #aaa;background:#fafafa}.ui-hlp-hidden{width:0;height:0;z-index:-1;overflow:hidden;line-height:0;position:absolute}.outline{outline:0 none!important}div .calc_ec-a3 {background-image: url(//pics.ebaystatic.com/aw/pics/cmp/ds3/sprds3_18.png);}
.similar-items-panel .similar-items-title {font-family: "Helvetica neue",Helvetica,Verdana,Sans-serif !important;}
#Body .app-mtp-theme-tabs * {font-family: "Helvetica neue",Helvetica,Verdana,Sans-serif}
#Body .theme-details * {font-family: "Helvetica neue",Helvetica,Verdana,Sans-serif}
h1#ProductTitle {font-family: "Helvetica neue",Helvetica,Verdana,Sans-serif}
  </style>
  <style type="text/css">
   html a:link{
					color: #0654ba;
				}
				ul#bc a:link{
					color: #0654ba;
				}
				.mbg a:link{
					color: #0654ba !important;
				}
				.mbg-l a:link{
					color: #0654ba !important;
				}
				#Body .nav-tabs-m a:link{
					color: #0654ba;
				}
  </style>
  <link href="https://ir.ebaystatic.com/rs/c/vimoduleapi-async-jLtE0kwS.css" rel="stylesheet" type="text/css"/>
  <link href="https://ir.ebaystatic.com/rs/c/vimoduleapi-_x48H5Ur.css" rel="stylesheet" type="text/css"/>
 </head>
 <body class="vi-contv2 lhdr-ie- vi-hd-ops vi-wide-watch-btn vi-ds3-global vi-bb-flex label-right-align vi-bb-btnclr1 vi-ds6 vi-bb-r-btn vi-white-spacing vi-rounded-btns vi-long-cta">
  <div id="Head">
  </div>
  <div class="sz940 sz1280" id="Body">
   <div id="maskDiv">
   </div>
   <div id="TopPanelDF">
    <div id="Top">
     <div class="" id="TopPanel">
      <style>
       .gh-hide-if-nocss{display:none;}.gh-ar-hdn{color:#fff}
      </style>
      <div class="gh-acc-exp-div gh-hide-if-nocss">
       <a class="gh-acc-a" href="#mainContent" id="gh-hdn-stm">
        Skip to main content
       </a>
      </div>
      <!--[if lt IE 9]><div id="gh" role="banner" class="gh-IE8 gh-flex gh-pre-js gh-w "><![endif]-->
      <!--[if (gte IE 9)|!(IE)]><!-->
      <header class="gh-ui-6-5 gh-flex gh-pre-js gh-w gh-sch-prom" data-treatment="" id="gh" role="banner">
       <!--<![endif]-->
       <table class="gh-tbl" role="presentation">
        <tbody>
         <tr>
          <td class="gh-td">
           <a _sp="m570.l2586" href="https://www.ebay.com/" id="gh-la">
            <img alt="eBay Logo" height="200" id="gh-logo" src="https://ir.ebaystatic.com/rs/v/fxxj3ttftm5ltcqnto1o4baovyl.png" style="clip:rect(47px, 118px, 95px, 0px); position:absolute; top:-47px;left:0" width="250"/>
           </a>
           <!--<![endif]-->
          </td>
          <td class="gh-td">
          </td>
          <td class="gh-td">
          </td>
          <td class="gh-td">
           <div class="gh-hide-if-nocss" id="gh-shop">
            <button aria-controls="gh-sbc-o" aria-expanded="false" class="gh-control" id="gh-shop-a">
             Shop by category
             <i class="gh-sprRetina" id="gh-shop-ei">
             </i>
            </button>
            <div id="gh-sbc-o">
             <h2 class="gh-ar-hdn">
              Shop by category
             </h2>
            </div>
           </div>
          </td>
          <td class="gh-td-s">
           <form action="https://www.ebay.com/sch/i.html" id="gh-f" method="get">
            <input name="_from" type="hidden" value="R40"/>
            <input name="_trksid" type="hidden" value="m570.l1313"/>
            <table class="gh-tbl2" role="presentation">
             <tbody>
              <tr>
               <td class="gh-td-s">
                <div id="gh-ac-box">
                 <div id="gh-ac-box2">
                  <label class="gh-ar-hdn" for="gh-ac">
                   Enter your search keyword
                  </label>
                  <input aria-autocomplete="list" aria-expanded="false" aria-label="Search for anything" autocapitalize="off" autocomplete="off" autocorrect="off" class="gh-tb ui-autocomplete-input" id="gh-ac" maxlength="300" name="_nkw" placeholder="Search for anything" size="50" spellcheck="false" type="text"/>
                  <input style="display:none"/>
                  <script>
                   if(document.getElementById('gh-ac').value.length !== 0) { document.getElementById('gh-ac-box').classList.add('gh-ac-box-focus'); document.getElementById('gh').classList.add('gh-sch-focus'); }
                  </script>
                  <svg aria-hidden="true" class="icon icon--search gh-search__icon" focusable="false" height="14" width="14">
                   <use xlink:href="#icon-search">
                   </use>
                  </svg>
                 </div>
                </div>
               </td>
               <td class="gh-td" id="gh-cat-td">
                <div id="gh-cat-box">
                 <select aria-label="Select a category for search" class="gh-sb" id="gh-cat" name="_sacat" size="1">
                  <option selected="selected" value="0">
                   All Categories
                  </option>
                 </select>
                </div>
               </td>
               <td class="gh-td gh-sch-btn">
                <input class="btn btn-ter gh-spr" id="gh-btn" type="submit" value="Search"/>
                <svg aria-hidden="true" class="icon icon--search gh-search-btn__icon" focusable="false" height="22" width="22">
                 <use xlink:href="#icon-search">
                 </use>
                </svg>
               </td>
               <td class="gh-td" id="gh-as-td">
                <a _sp="m570.l2614" aria-label="Advanced Search" href="https://www.ebay.com/sch/ebayadvsearch" id="gh-as-a" title="Advanced Search">
                 Advanced
                </a>
               </td>
              </tr>
             </tbody>
            </table>
           </form>
          </td>
          <td class="gh-td">
          </td>
          <td class="sticky_placeholder">
           <ul>
           </ul>
          </td>
         </tr>
        </tbody>
       </table>
       <div aria-label="Account" class="gh-hide-if-nocss" id="gh-top" role="navigation">
        <ul id="gh-topl">
         <li class="gh-t" id="gh-eb-u">
          <script>
           var supressUserGreeting = true;
          </script>
          <script>
           (function(){try{ var sup = !!(supressUserGreeting && typeof window.GHpre !== 'undefined' && !window.GHpre.si); var d=document.cookie,a=((a=d.match(/u1f[^a-zA-Z0-9]([^^]*)[0-9a-z]{8}/))?a[1].replace(/\+/g," "):"").replace(/(.{12}).*/,"$1...");if(/[<>%&'\/]/.test(a)){throw(1)}document.write("<span id=gh-ug"+(!a||/u1p.QEBfX/.test(d)?' class=gh-ug-guest>Hi! <a href="https://signin.ebay.com/ws/eBayISAPI.dll?SignIn&amp;_trksid=m570.l1524" rel="nofollow" _sp="m570.l1524">Sign in</a> <span id="gh-ug-flex">or <a href="https://signup.ebay.com/pa/crte?_trksid=m570.l2621" rel="nofollow" _sp="m570.l2621">register</a></span>':' style="margin-right:3px">Hi <b>-User-</b>!'.replace(/-User-/,sup ? '' : decodeURIComponent(escape(a))))+"</span>")}catch(b){document.write("<style>#gh-topl{display:none}</style>")}})();
          </script>
          <noscript class="gh-t gh-spr">
           Hi (
           <a href="https://signin.ebay.com/ws/eBayISAPI.dll?SignIn&amp;_trksid=m570.l3348">
            Sign in
           </a>
           to bid or buy)
          </noscript>
         </li>
         <li class="gh-t gh-divider-l" id="gh-p-1">
          <a _sp="m570.l3188" class="gh-p" data-sp="m570.l3188" href="https://www.ebay.com/deals">
           Daily Deals
          </a>
         </li>
         <li class="gh-t gh-divider-l" id="gh-p-4">
          <a _sp="m570.l47233" class="gh-p" data-sp="m570.l47233" href="https://www.ebay.com/b/Brand-Outlet/bn_7115532402">
           Brand Outlet
          </a>
         </li>
         <li class="gh-t gh-divider-l" id="gh-p-3">
          <a _sp="m570.l1545" class="gh-p" data-sp="m570.l1545" href="https://ocsnext.ebay.com/ocs/home">
           Help &amp; Contact
          </a>
         </li>
        </ul>
        <ul id="gh-eb">
         <li class="gh-eb-li gh-t-rt gh--link__divider" id="gh-p-2">
          <a _sp="m570.l1528" class="gh-p" data-sp="m570.l1528" href="https://www.ebay.com/sl/sell">
           Sell
          </a>
         </li>
         <li class="gh-eb-li gh-margin rt" id="gh-wl-click">
          <div class="gh-menu gh--link__divider">
           <a _sp="m570.l47137" class="gh-eb-li-a gh-rvi-menu watchlist-menu" href="https://www.ebay.com/mye/myebay/watchlist" title="Watchlist">
            Watchlist
            <i class="gh-sprRetina gh-eb-arw gh-rvi-chevron" data-sp="m570.l47137">
            </i>
           </a>

In [6]:
from lxml import etree
html = etree.HTML(str(soup))

iframe = html.xpath('//iframe[@id="desc_ifr"]/@src')[0]

iframe

'https://vi.vipr.ebaydesc.com/ws/eBayISAPI.dll?ViewItemDescV4&item=372749825457&t=1689367301000&category=33710&seller=carpartswholesale&excSoj=1&excTrk=1&lsite=100&ittenable=true&domain=ebay.com&descgauge=1&cspheader=1&oneClk=2&secureDesc=1'

In [7]:
df_temp = pd.DataFrame([{'Url': list_url[i],
                         'iframe': iframe,
                         'status': 'ok'}])

df = pd.concat([df, df_temp], ignore_index=True).fillna('')

df

,Url,iframe,status
0,https://www.ebay.com/itm/372749825457?hash=ite...,https://vi.vipr.ebaydesc.com/ws/eBayISAPI.dll?...,ok